// Resource-library adapter. No audio/video element or independent playback clock.
(()=>{
 let latest={queue:[],currentId:null,status:'idle',position:0,volume:80,muted:false},revision=-1;
 const mini=document.createElement('section');mini.id='audioMini';mini.className='hidden';const name=document.createElement('button'),toggle=document.createElement('button'),previous=document.createElement('button'),next=document.createElement('button'),time=document.createElement('span');name.className='audio-now';const cover=document.createElement('img'),info=document.createElement('span'),song=document.createElement('span'),artist=document.createElement('span'),volume=document.createElement('input'),mute=document.createElement('button'),mode=document.createElement('button');cover.className='audio-mini-cover';cover.alt='封面';cover.onerror=()=>{if(!cover.src.endsWith('/assets/icon.svg'))cover.src='assets/icon.svg';};info.className='audio-mini-info';song.className='audio-mini-title';artist.className='audio-mini-artist';info.append(song,artist);name.append(cover,info);time.className='audio-time';volume.type='range';volume.min=0;volume.max=100;volume.step=1;volume.className='audio-volume';volume.setAttribute('aria-label','音量');volume.oninput=()=>run(()=>native.playerCommand({type:'volume',value:Number(volume.value),muted:latest.muted}));mute.onclick=()=>run(()=>native.playerCommand({type:'volume',value:latest.volume,muted:!latest.muted}));mode.dataset.command='mode';mode.onclick=()=>run(()=>native.playerAction('mode',latest.shuffle?'none':latest.repeat==='none'?'all':latest.repeat==='all'?'one':'shuffle'));PlaybackControls.set(previous,'previous','上一项');PlaybackControls.set(next,'next','下一项');const seek=document.createElement('input');seek.type='range';seek.className='audio-mini-seek';seek.setAttribute('aria-label','播放进度');const updateSeek=PlaybackControls.bindSeek(seek,time,seconds=>run(()=>native.playerCommand({type:'seek',seconds})));mini.append(name,previous,toggle,next,mode,seek,time,mute,volume);(document.querySelector('.window-shell')||document.body).append(mini);
 const run=fn=>Promise.resolve().then(fn).catch(e=>showToast(e.message,'error'));
 name.onclick=()=>run(()=>native.playerShow());toggle.onclick=()=>run(()=>latest.status==='paused'||latest.status==='playing'?native.playerCommand({type:'pause',paused:latest.status==='playing'}):latest.currentId?native.playerCommand({type:'play',id:latest.currentId}):Promise.resolve());previous.onclick=()=>run(()=>native.playerAction('previous'));next.onclick=()=>run(()=>native.playerAction('next'));
 const render=s=>{if(s.viewRevision<=revision)return;revision=s.viewRevision;latest=s;const entry=s.queue.find(e=>e.queueEntryId===s.currentId),active=!!entry&&!settings.disguiseEnabled;mini.classList.toggle('hidden',!active);document.body.classList.toggle('has-audio-session',active);song.textContent=entry?.title||'播放器';song.title=song.textContent;const item=state.items?.find(i=>i.id===entry?.resourceId),track=item?.audio?.tracks?.find(t=>t.id===entry?.memberId);artist.textContent=entry?.artist||(item?.audio?.artists||[]).join(' / ')||(item?.type==='movie'?'影视':item?.type==='anime'?'番剧':'未知艺术家');artist.title=artist.textContent;const src=track?.cover||(item?coverFor(item,'portrait'):'')||'assets/icon.svg';if(cover.getAttribute('src')!==src)cover.src=src;PlaybackControls.set(mute,s.muted?'muted':'volume',s.muted?'取消静音':'静音');mute.setAttribute('aria-pressed',String(s.muted));if(document.activeElement!==volume)volume.value=s.volume;volume.title=s.volume+'%';PlaybackControls.mode(mini,s);PlaybackControls.set(toggle,s.status==='playing'?'pause':'play',s.status==='playing'?'暂停':'播放');toggle.setAttribute('aria-pressed',String(s.status==='playing'));updateSeek(s)};
 native.onPlayerState(render);native.playerSnapshot().then(render).catch(()=>{});
 window.audioPlayer={
  playItem:item=>native.launchReader(item.id),
  command:(mode,refs,source)=>native.playerResource(refs.map(ref=>LibraryRelations.resolve(state,ref)),mode,source),
  resumeContext:kind=>native.playerAction('context',kind),
  importDialog:dropped=>window.audioImportUI.open(dropped||[]),
  reloadLyrics:()=>native.playerAction('reloadLyrics'),
  pause:()=>native.playerCommand({type:'pause',paused:true}),
  getSession:()=>({queue:latest.queue.map(e=>({queueEntryId:e.queueEntryId,itemId:e.resourceId,trackId:e.memberId})),index:latest.queue.findIndex(e=>e.queueEntryId===latest.currentId),position:latest.position,volume:latest.volume/100,muted:latest.muted,bookmarks:latest.bookmarks||[],progress:[]}),
  media:{pause:()=>native.playerCommand({type:'pause',paused:true}),get paused(){return latest.status!=='playing'}}
 };
})();
