(()=>{
 const api=window.player,kind=new URLSearchParams(location.search).get('kind')||'main',root=document.getElementById('app'),error=document.getElementById('error');let state=null,revision=-1,dragId=null,lyricKey='',activeLine=-2,queueKey='';
 document.body.dataset.kind=kind;
 const button=(label,fn)=>{const b=document.createElement('button');const icon=({'上一项':'previous','下一项':'next','播放':'play','停止':'stop','静音':'volume','歌词':'lyrics','列表':'queue','EQ':'eq','全屏':'fullscreen'})[label];if(icon)PlaybackControls.set(b,icon,label);else b.textContent=label;b.onclick=()=>run(fn);return b};
 const run=fn=>Promise.resolve().then(fn).catch(e=>{error.textContent=e.message});
 const action=(name,value)=>api.action(name,value),command=value=>api.command(value);
 const chrome=document.createElement('div');chrome.className='player-titlebar';const brand=document.createElement('span');brand.textContent=kind==='main'?'媒体播放器 · 悦森盒 YueDen':({'lyrics':'歌词','queue':'播放列表','eq':'均衡器','lyricsSearch':'搜索歌词'})[kind]+' · 悦森盒 YueDen';chrome.append(brand);const windowButtons={};for(const [id,label]of [['minimize','最小化'],['maximize','最大化'],['close','关闭']]){const b=button(label,()=>api.window(id));PlaybackControls.set(b,id,label);b.classList.add('window-button');windowButtons[id]=b;chrome.append(b);}chrome.ondblclick=e=>{if(!e.target.closest('button'))run(()=>api.window('maximize'))};document.body.prepend(chrome);
 const title=document.createElement('p');title.className='status';root.append(title);
 const clock=n=>`${Math.floor((n||0)/60)}:${String(Math.floor((n||0)%60)).padStart(2,'0')}`;
 let fullscreen=false,overlay,hideTimer,cursorTimer,interaction=false,viewportUpdate=()=>{};const wakeCursor=()=>{if(!fullscreen)return;document.body.classList.remove('cursor-idle');clearTimeout(cursorTimer);cursorTimer=setTimeout(()=>{if(!interaction&&!overlay?.querySelector('select:focus'))document.body.classList.add('cursor-idle');},1800);};const reveal=()=>{if(!fullscreen)return;document.body.classList.add('controls-visible');wakeCursor();api.overlay(overlay.getBoundingClientRect().height);clearTimeout(hideTimer);hideTimer=setTimeout(()=>{if(interaction||overlay.querySelector('select:focus'))return;document.body.classList.remove('controls-visible');api.overlay(0)},1800)};
 let updateQueueFamily=()=>{};let updateLyricFullscreen=()=>{};let updateLyricView=()=>{};let resetLyricsSearch=()=>{},lyricsTrackGeneration=-1;
 const trackLabel=(b,t)=>{b.classList.add('title');b.replaceChildren();const name=document.createElement('span'),meta=document.createElement('small');name.textContent=t.title;meta.textContent=(t.context==='video'?(t.album||'视频'):(t.artist||'未知艺术家'))+' · '+(Number.isFinite(t.duration)&&t.duration>0?clock(t.duration):'时长未知');b.append(name,meta);return b;};
 let queueNotice,queueReorder,libraryHost,libraryView='queue',libraryTicket=0;
 let updateSeek,video,seek,toggle,volume,mute,rows,lyricLines,eqEnable,preamp,eqInputs=[],aux={},rate,modeButton,mainFull,trackSelect,bookmarks,trackKey='',bookmarkKey='',eqTimer;
 if(kind==='main'){
  const header=document.createElement('header');header.append(button('打开文件',()=>action('files',true)));for(const [k,label]of [['lyrics','歌词'],['queue','列表'],['eq','EQ']]){aux[k]=button(label,()=>action('aux',k));header.append(aux[k])}mainFull=button('全屏',()=>action('fullscreen'));mainFull.classList.add('titlebar-fullscreen');chrome.insertBefore(mainFull,windowButtons.minimize);root.append(header);
  video=document.createElement('div');video.id='video';video.textContent='选择本地媒体开始播放';root.append(video);
  const progress=document.createElement('div');progress.className='seek';seek=document.createElement('input');seek.type='range';seek.min=0;seek.max=1;seek.step=.1;seek.setAttribute('aria-label','播放进度');const time=document.createElement('span');time.id='time';updateSeek=PlaybackControls.bindSeek(seek,time,seconds=>run(()=>command({type:'seek',seconds})));progress.append(seek,time);root.append(progress);
  const controls=document.createElement('div');controls.className='controls';toggle=button('播放',()=>state?.status==='paused'||state?.status==='playing'?command({type:'pause',paused:state.status==='playing'}):state?.currentId?command({type:'play',id:state.currentId}):action('files',true));mute=button('静音',()=>command({type:'volume',value:state.volume,muted:!state.muted}));volume=document.createElement('input');volume.type='range';volume.min=0;volume.max=100;volume.className='volume';volume.setAttribute('aria-label','音量');volume.oninput=()=>run(()=>command({type:'volume',value:Number(volume.value),muted:state.muted}));controls.append(button('上一项',()=>action('previous')),toggle,button('停止',()=>command({type:'stop'})),button('下一项',()=>action('next')),mute,volume,button('书签',()=>action('bookmark')));
  modeButton=button('播放模式',()=>action('mode',state.shuffle?'none':state.repeat==='none'?'all':state.repeat==='all'?'one':'shuffle'));modeButton.dataset.modeControl='combined';modeButton.dataset.command='mode';controls.append(modeButton);overlay=document.createElement('div');overlay.className='player-transport';overlay.append(progress,controls);root.append(overlay);overlay.addEventListener('pointerdown',()=>{interaction=true;reveal()});window.addEventListener('pointerup',()=>{interaction=false;reveal()});overlay.addEventListener('pointercancel',()=>{interaction=false;reveal()});overlay.addEventListener('focusout',reveal);overlay.addEventListener('keydown',()=>{interaction=true;reveal()});overlay.addEventListener('keyup',()=>{interaction=false;reveal()});const pointer=p=>{if(!fullscreen)return;wakeCursor();if(p.y>=innerHeight-110)reveal()};document.addEventListener('pointermove',pointer);api.pointer(pointer);const advanced=document.createElement('details');advanced.className='advanced';const summary=document.createElement('summary');summary.textContent='睡眠、字幕、书签';advanced.append(summary);root.append(advanced);
  const options=document.createElement('div');options.className='controls';const sleep=document.createElement('input');sleep.type='number';sleep.min=0;sleep.max=1440;sleep.placeholder='睡眠分钟';sleep.setAttribute('aria-label','睡眠分钟');sleep.style.width='100px';options.append(sleep,button('定时',()=>action('sleep',Number(sleep.value))),button('本项结束休眠',()=>action('sleep','end')));
  rate=document.createElement('select');rate.setAttribute('aria-label','播放速度');for(const n of [.5,.75,1,1.25,1.5,2,3])rate.add(new Option(n+'×',n));rate.onchange=()=>run(()=>action('rate',Number(rate.value)));trackSelect=document.createElement('select');trackSelect.setAttribute('aria-label','音轨与字幕');trackSelect.onchange=()=>{if(trackSelect.value)run(()=>action('track',JSON.parse(trackSelect.value)))};controls.append(rate);options.append(trackSelect,button('外挂字幕',()=>action('subtitle')));advanced.append(options);
  bookmarks=document.createElement('select');bookmarks.id='bookmarks';bookmarks.setAttribute('aria-label','时间书签');const note=document.createElement('input');note.placeholder='书签备注';note.setAttribute('aria-label','书签备注');note.maxLength=1000;note.style.width='100px';options.append(bookmarks,button('跳转',()=>action('bookmarkPlay',bookmarks.value)),button('删书签',()=>action('bookmarkDelete',bookmarks.value)),note,button('存备注',()=>action('bookmarkNote',{id:bookmarks.value,note:note.value})));
  const viewport=viewportUpdate=()=>{const r=video.getBoundingClientRect();api.viewport({x:r.x,y:r.y,width:r.width,height:r.height})};new ResizeObserver(viewport).observe(video);window.addEventListener('resize',viewport);setInterval(viewport,250);
  const blocked=()=>!!document.querySelector('[data-app-modal]')||document.activeElement?.matches('input:not([type=range]),select,textarea,[contenteditable=true]');
  const input=key=>{if(blocked())return;const commands={ArrowLeft:['seek',-1],ArrowRight:['seek',1],ArrowUp:['volume',1],ArrowDown:['volume',-1],Toggle:['toggle',0]};if(commands[key]){const [kind,step]=commands[key];run(()=>action('input',{kind,step}));}else if(key==='Escape'&&fullscreen)run(()=>action('fullscreen'));else if(key==='f')run(()=>action('fullscreen'));else if(key===' ')toggle.click();};
  document.addEventListener('keydown',e=>{if(e.ctrlKey||e.altKey||e.metaKey||e.shiftKey||e.target.closest?.('input,select,textarea,[contenteditable=true]')||blocked())return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','f','Escape'].includes(e.key)){e.preventDefault();if(!e.repeat||e.key.startsWith('Arrow'))input(e.key);}});
  document.addEventListener('wheel',e=>{if(!e.deltaY||e.ctrlKey||e.target.closest?.('input,select,textarea,.advanced,[data-app-modal]')||blocked())return;e.preventDefault();input(e.deltaY<0?'ArrowUp':'ArrowDown');},{passive:false});
  video.addEventListener('dblclick',e=>{e.preventDefault();input('Toggle');});
  api.nativeInput(key=>{if(key==='Focus'){document.activeElement?.blur();return;}input(({Left:'ArrowLeft',Right:'ArrowRight',Up:'ArrowUp',Down:'ArrowDown',WheelUp:'ArrowUp',WheelDown:'ArrowDown',Space:' ',F:'f'})[key]||key);});
 }else if(kind==='queue'){
  const nav=document.createElement('nav');nav.className='queue-tabs';nav.setAttribute('aria-label','播放列表和声音资料库');
  const picker=document.createElement('select');picker.className='queue-picker';picker.hidden=true;picker.setAttribute('aria-label','选择专辑或歌单');
  rows=document.createElement('ul');rows.id='rows';libraryHost=document.createElement('div');libraryHost.className='player-library';libraryHost.hidden=true;root.append(nav,picker,rows,libraryHost);
  queueReorder=installQueueReorder(rows,ids=>command({type:'reorder',ids}),e=>error.textContent=e.message);
  queueNotice=document.createElement('p');queueNotice.className='queue-notice';queueNotice.setAttribute('role','status');root.append(queueNotice);
  const selectedGroups={},sorting={},expandedGroups=new Set();let groups=[],manualOrders={},libraryReorders=[];
  const O=PlayerLibraryOrder;
  const ordered=(tracks,groupId)=>{const items=O.tracks(tracks),preference=sorting[libraryView];return manualOrders[O.scope(libraryView,groupId)]?O.apply(items,manualOrders[O.scope(libraryView,groupId)],t=>t.orderId):preference?PlayerQueue.sorted(items,preference.field,preference.order):items;};
  const draggable=(node,id)=>{node.dataset.id=id;node.draggable=true;node.tabIndex=0;node.setAttribute('aria-label','可拖动排序，Alt 加上下键移动');};
  const bind=(host,groupId)=>{const view=libraryView;libraryReorders.push(installQueueReorder(host,async ids=>{await action('libraryOrder',{view,groupId,ids});manualOrders[O.scope(view,groupId)]=ids;},e=>error.textContent=e.message));};
  const draw=()=>ReorderMotion.preserve(libraryHost,()=>{for(const r of libraryReorders)r.destroy();libraryReorders=[];libraryHost.replaceChildren();let filtered=['albums','playlists'].includes(libraryView)?groups.filter(g=>g.id===picker.value):groups;
    if(!['albums','playlists','songs'].includes(libraryView)){const saved=manualOrders[O.scope(libraryView,null)];if(saved)filtered=O.apply(filtered,saved,g=>g.id);else if(sorting[libraryView]){const {field,order}=sorting[libraryView];filtered=PlayerQueue.sorted(filtered.map(g=>({...g,artist:g.tracks[0]?.artist,album:g.tracks[0]?.album})),field,order);}}
    const addTrack=(host,track,dragKey,source)=>{const row=document.createElement('div');row.className='row';row.dataset.resource=track.ref.itemId;row.dataset.track=track.ref.trackId||track.ref.file;row.dataset.ref=JSON.stringify(track.ref);if(dragKey)draggable(row,dragKey);const name=trackLabel(button(track.title,()=>{}),track);name.title='双击播放';name.ondblclick=()=>run(()=>api.resource([track.ref],'play',source));row.append(name,button('加入',()=>api.resource([track.ref],'append',source)));host.append(row);};
    if(libraryView==='songs'){for(const track of ordered(filtered.flatMap(g=>g.tracks),null))addTrack(libraryHost,track,track.orderId);bind(libraryHost,null);}
    else for(const group of filtered){
      const collections=['asmr','radio','other','movie','anime'].includes(libraryView),source=libraryView==='playlists'?{kind:'playlist',id:group.id}:undefined;
      if(collections&&group.tracks.length===1){addTrack(libraryHost,group.tracks[0],group.id,source);continue;}
      const section=document.createElement('section');section.className='library-group';const tracks=ordered(group.tracks,group.id),trackHost=document.createElement('div');trackHost.className='library-tracks';
      if(collections){draggable(section,group.id);const heading=document.createElement('h3'),key=O.scope(libraryView,group.id),fold=button('',()=>{if(expandedGroups.has(key))expandedGroups.delete(key);else expandedGroups.add(key);update();});fold.className='collection-toggle';const update=()=>{const open=expandedGroups.has(key);section.classList.toggle('collapsed',!open);fold.textContent=(open?'▾ ':'▸ ')+group.title+' · '+tracks.length;fold.setAttribute('aria-expanded',String(open));};update();heading.append(fold);section.append(heading);}
      for(const [label,mode]of [['播放全部','play'],['加入队列','append']]){const b=button(label,()=>{const refs=[...trackHost.children].map(row=>JSON.parse(row.dataset.ref));return api.resource(refs,mode,source);});b.disabled=!tracks.length;section.append(b);}
      for(const track of tracks)addTrack(trackHost,track,libraryView==='albums'?null:track.orderId,source);section.append(trackHost);if(libraryView!=='albums')bind(trackHost,group.id);libraryHost.append(section);
    }
    if(!['songs','albums','playlists'].includes(libraryView))bind(libraryHost,null);
    if(!filtered.length)libraryHost.textContent=groups.length?'请选择专辑或歌单':'此资料库暂无内容';});
  const refreshLibrary=async()=>{const ticket=++libraryTicket;rows.hidden=libraryView!=='queue';libraryHost.hidden=libraryView==='queue';picker.hidden=!['albums','playlists'].includes(libraryView);for(const b of nav.children)b.setAttribute('aria-pressed',String(b.dataset.view===libraryView));if(libraryView==='queue')return;const result=await api.library(libraryView);if(ticket!==libraryTicket)return;groups=result.groups;manualOrders=result.orders||{};picker.replaceChildren(new Option(libraryView==='albums'?'选择专辑':'选择歌单',''));for(const group of groups)picker.add(new Option(group.title+' · '+group.tracks.length,group.id));picker.value=groups.some(g=>g.id===selectedGroups[libraryView])?selectedGroups[libraryView]:'';draw();};
  picker.onchange=()=>{selectedGroups[libraryView]=picker.value;draw()};
  const options=(id,label)=>{const d=workspaceDialog(label+'排序'),saved=sorting[id]||{field:'title',order:'asc'};d.host.classList.add('queue-options');
    const radios=(name,caption,values,selected)=>{const field=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=caption;field.append(legend);for(const [value,text]of values){const l=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name=name;input.value=value;input.checked=value===selected;l.append(input,document.createTextNode(text));field.append(l);}d.body.append(field);};
    radios('field','排序字段',[['title','名称'],...(['movie','anime'].includes(id)||id==='queue'&&state?.context==='video'?[]:[['artist','艺术家'],...(id==='albums'?[]:[['album','专辑名']])])],saved.field);
    radios('order','排序类型',[['asc','升序'],['desc','降序'],['random','随机乱序']],saved.order);
    if(id==='queue'){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=state.allowDuplicates;input.onchange=()=>run(async()=>{try{await action('queueDuplicates',input.checked);}catch(e){input.checked=state.allowDuplicates;throw e;}});label.append(input,document.createTextNode('允许队列存在重复资源'));d.body.append(label);const tools=document.createElement('div');tools.className='controls';for(const [mode,text]of [['clear','清空队列'],['duplicates','清理重复项']])tools.append(button(text,async()=>{try{const plan=await action('queueCleanPreview',mode);if(!plan.count){d.status.textContent='没有可清理的队列项';return;}const confirm=workspaceDialog('确认清理队列');confirm.host.classList.add('queue-clean-confirm');const message=document.createElement('p');message.textContent='即将清理 '+plan.count+' 项资源，是否继续？';const detail=document.createElement('p');detail.textContent='只移除队列项，不删除媒体文件或资料库资源。';confirm.body.append(message,detail);confirm.actions.append(button('取消',confirm.close),button('确认清理',async()=>{try{await action('queueClean',plan.token);confirm.close();d.status.textContent='';}catch(e){confirm.status.textContent=e.message;}}));}catch(e){d.status.textContent=e.message;}}));d.body.append(tools);}
    d.actions.append(button('取消',d.close),button('应用排序',async()=>{const field=d.body.querySelector('[name=field]:checked').value,order=d.body.querySelector('[name=order]:checked').value;try{if(id==='queue')await command({type:'reorder',ids:PlayerQueue.sorted(state.queue,field,order).map(e=>e.queueEntryId)});if(id!=='queue')await action('libraryOrderReset',id);sorting[id]={field,order};for(const key of Object.keys(manualOrders)){if(JSON.parse(key)[0]===id)delete manualOrders[key];}if(libraryView===id&&id!=='queue')draw();d.close();}catch(e){d.status.textContent=e.message;}}));};
  let family=null;updateQueueFamily=context=>{const next=context==='video'?'video':'audio';if(family===next)return;family=next;const views=[['queue','队列'],...(family==='video'?[['movie','影视'],['anime','番剧']]:[['albums','专辑'],['songs','歌曲'],['playlists','歌单'],['asmr','音声'],['radio','电台'],['other','其他']])];if(!views.some(([id])=>id===libraryView))libraryView='queue';nav.replaceChildren();for(const [id,label]of views){const b=button(label,async()=>{libraryView=id;await refreshLibrary();});b.dataset.view=id;b.title=label+' · 右键排序';b.oncontextmenu=e=>{e.preventDefault();b.focus();options(id,label)};b.setAttribute('aria-pressed',String(id===libraryView));nav.append(b);}run(refreshLibrary);};
  api.libraryChanged(()=>run(refreshLibrary));
 }else if(kind==='lyricsSearch'){
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();run(()=>api.window('close'));}});
  const tools=document.createElement('div');tools.className='lyrics-search';
  const song=document.createElement('input'),artist=document.createElement('input'),preview=document.createElement('textarea'),choices=document.createElement('select'),source=document.createElement('select'),notice=document.createElement('p');
  song.placeholder='歌名';song.setAttribute('aria-label','歌曲名称');artist.placeholder='歌手';artist.setAttribute('aria-label','艺术家');source.setAttribute('aria-label','歌词来源');
  for(const [id,label]of [['auto','全部来源'],['lrclib','LRCLIB'],['netease','网易云音乐'],['qq','QQ 音乐'],['kugou','酷狗音乐'],['ovh','lyrics.ovh']])source.add(new Option(label,id));
  choices.hidden=true;choices.setAttribute('aria-label','候选版本');preview.readOnly=true;preview.setAttribute('aria-label','在线歌词预览');notice.setAttribute('role','status');let ticket=0;
  const save=button('替换',async()=>{await api.lyrics('save',{replace:true});notice.textContent='已保存所选歌词';});save.disabled=true;save.title='保存所选歌词并替换当前歌词';
  const search=async(candidateId='')=>{const mine=++ticket;save.disabled=true;notice.textContent='正在搜索…';try{const result=await api.lyrics('search',{title:song.value,artist:artist.value,source:source.value,candidateId});if(mine!==ticket)return;preview.value=[result.text,result.translation].filter(Boolean).join('\n\n');if(!candidateId){choices.replaceChildren(new Option('选择歌词版本',''));for(const row of result.choices||[])choices.add(new Option([row.title,row.artist||'未知歌手',row.album||'未知专辑',row.duration+'秒',({lrclib:'lr',netease:'wy',qq:'qq',ovh:'ly',kugou:'kg'})[row.provider]||row.provider].join(' · '),row.id));choices.hidden=!result.choices?.length;}save.disabled=!result.text;notice.textContent=(result.choices?.length||((result.text||candidateId)?1:0))+' 条结果'+(result.mismatch?' · 请核对版本':'')+(result.source?' · '+result.source:'')+(result.message?' · '+result.message:'')+(!result.message&&result.failures?.length?' · '+result.failures.map(f=>f.message).join('；'):'');}catch(e){if(mine===ticket){preview.value='';notice.textContent=e.message;}}};
  choices.onchange=()=>{if(choices.value)run(()=>search(choices.value))};tools.append(song,artist,source,button('在线搜索 / 重新搜索',()=>search()),choices,preview,save,notice);root.append(tools);
  resetLyricsSearch=()=>{const mine=++ticket;preview.value='';choices.hidden=true;save.disabled=true;api.lyrics('info').then(info=>{if(mine!==ticket)return;song.value=info.title;artist.value=info.artist;return search();}).catch(e=>{if(mine===ticket)notice.textContent=e.message});};
 }else if(kind==='lyrics'){
  lyricLines=document.createElement('div');lyricLines.id='lyricLines';root.append(lyricLines);
  const tools=document.createElement('div');tools.className='lyrics-toolbar';tools.setAttribute('aria-label','歌词显示工具');
  const icon=(label,name,fn)=>{const b=button(label,fn);PlaybackControls.set(b,name,label);return b};
  const zoom=document.createElement('input');zoom.type='number';zoom.min=20;zoom.max=400;zoom.step=5;zoom.setAttribute('aria-label','歌词缩放百分比');zoom.onchange=()=>run(()=>action('lyricView',{zoom:Number(zoom.value)}));
  const offset=document.createElement('input');offset.type='number';offset.step=10;offset.setAttribute('aria-label','歌词偏移毫秒');offset.title='正值延迟歌词，负值提前歌词';offset.onchange=()=>run(()=>action('lyricView',{offset:Number(offset.value)}));
  const group=(...children)=>{const g=document.createElement('span');g.className='lyric-tool-group';g.append(...children);return g};
  const align=icon('歌词居中','alignCenter',()=>action('lyricView',{align:['left','center','right'][(['left','center','right'].indexOf(state.lyricView.align)+1)%3]}));
  tools.append(icon('搜索歌词','search',()=>action('lyricsSearch')),icon('选择本地歌词','folder',()=>action('lyrics')),group(icon('缩小歌词','minus',()=>action('lyricView',{zoom:state.lyricView.zoom-5})),zoom,document.createTextNode('%'),icon('放大歌词','plus',()=>action('lyricView',{zoom:state.lyricView.zoom+5}))),group(icon('歌词提前 10ms','backward',()=>action('lyricView',{offset:state.lyricView.offset-10})),offset,document.createTextNode('ms'),icon('歌词延迟 10ms','forward',()=>action('lyricView',{offset:state.lyricView.offset+10}))),align);root.append(tools);
  const full=icon('全屏歌词','fullscreen',()=>api.window('fullscreen'));full.classList.add('lyrics-fullscreen-button');chrome.insertBefore(full,windowButtons.minimize);
  let idleTimer;const revealLyrics=()=>{clearTimeout(idleTimer);document.body.classList.remove('lyrics-controls-idle');if(fullscreen)idleTimer=setTimeout(()=>{if(!tools.contains(document.activeElement)||!document.activeElement.matches('input'))document.body.classList.add('lyrics-controls-idle');},3000);};
  document.addEventListener('pointermove',revealLyrics);document.addEventListener('pointerdown',revealLyrics);document.addEventListener('keydown',e=>{revealLyrics();if(e.key==='Escape'&&fullscreen){e.preventDefault();run(()=>api.window('fullscreen'));}});tools.addEventListener('focusout',revealLyrics);window.addEventListener('beforeunload',()=>clearTimeout(idleTimer));
  updateLyricFullscreen=value=>{if(fullscreen===value)return;fullscreen=value;document.body.classList.toggle('lyrics-fullscreen',value);PlaybackControls.set(full,value?'exitFullscreen':'fullscreen',value?'退出歌词全屏':'全屏歌词');revealLyrics();};
  updateLyricView=v=>{lyricLines.style.fontSize=v.zoom+'%';lyricLines.style.textAlign=v.align;if(document.activeElement!==zoom)zoom.value=v.zoom;if(document.activeElement!==offset)offset.value=v.offset;PlaybackControls.set(align,{left:'alignLeft',center:'alignCenter',right:'alignRight'}[v.align],'歌词'+{left:'左对齐',center:'居中',right:'右对齐'}[v.align]+' · 点击切换');};
 }else if(kind==='eq'){
  const tools=document.createElement('header');eqEnable=button('启用 EQ',()=>action('eq',{enabled:!state.eq.enabled,gains:state.eq.gains,preamp:state.eq.preamp||0}));tools.append(eqEnable,button('恢复默认',()=>action('eq',{enabled:state.eq.enabled,gains:Array(10).fill(0),preamp:0})));preamp=document.createElement('input');preamp.type='range';preamp.min=-24;preamp.max=12;preamp.step=.5;preamp.setAttribute('aria-label','前置增益 dB');preamp.onchange=()=>run(()=>action('eq',{enabled:state.eq.enabled,gains:state.eq.gains,preamp:Number(preamp.value)}));const preampLabel=document.createElement('label');preampLabel.textContent='前置增益 ';preampLabel.append(preamp);tools.append(preampLabel);root.append(tools);const bands=document.createElement('div');bands.className='bands';
  [31.25,62.5,125,250,500,'1k','2k','4k','8k','16k'].forEach((f,i)=>{const label=document.createElement('label');label.className='band';const output=document.createElement('output');const input=document.createElement('input');input.type='range';input.min=-12;input.max=12;input.step=.5;input.value=0;input.setAttribute('aria-label',`${f} Hz 增益`);const update=()=>run(()=>action('eq',{enabled:state.eq.enabled,gains:eqInputs.map(v=>Number(v.input.value)),preamp:Number(preamp.value)}));input.oninput=()=>{output.textContent=input.value+' dB';clearTimeout(eqTimer);eqTimer=setTimeout(update,60)};input.onchange=()=>{clearTimeout(eqTimer);update()};label.append(document.createTextNode(String(f)),input,output);eqInputs.push({input,output});bands.append(label)});root.append(bands);const hint=document.createElement('p');hint.className='hint';hint.textContent='禁用保留数值。峰值限幅保护开启；各频段独立增益，前置增益可单独调整。';root.append(hint);
 }
 for(const name of ['dragover','drop'])root.addEventListener(name,e=>{e.preventDefault();if(name==='drop'&&e.dataTransfer.files.length)run(()=>action('drop',[...e.dataTransfer.files].map(api.filePath).filter(Boolean)))});
 function render(s){if(!s||s.viewRevision<=revision)return;revision=s.viewRevision;state=s;YueDenAppearance.apply(s.appearance);const maximized=s.windowState?.[kind]?.maximized;PlaybackControls.set(windowButtons.maximize,maximized?'restore':'maximize',maximized?'还原':'最大化');windowButtons.maximize.setAttribute('aria-pressed',String(!!maximized));error.textContent=s.error||'';const entry=s.queue.find(e=>e.queueEntryId===s.currentId);title.textContent=(entry?.title||'尚未选择媒体')+' · '+({idle:'待播放',loading:'正在打开',playing:'播放中',paused:'已暂停',stopped:'已停止',error:'播放出错'}[s.status]||s.status);
  if(kind==='main'){const nextFullscreen=!!s.windowState?.main?.fullscreen;PlaybackControls.set(mainFull,nextFullscreen?'exitFullscreen':'fullscreen',nextFullscreen?'退出全屏':'全屏');if(fullscreen!==nextFullscreen){fullscreen=nextFullscreen;document.body.classList.toggle('player-fullscreen',fullscreen);if(fullscreen)reveal();else{clearTimeout(hideTimer);clearTimeout(cursorTimer);document.body.classList.remove('cursor-idle','controls-visible');}requestAnimationFrame(viewportUpdate);}PlaybackControls.set(toggle,s.status==='playing'?'pause':'play',s.status==='playing'?'暂停':'播放');PlaybackControls.set(mute,s.muted?'muted':'volume',s.muted?'取消静音':'静音');toggle.setAttribute('aria-pressed',String(s.status==='playing'));updateSeek(s);if(document.activeElement!==volume)volume.value=s.volume;mute.setAttribute('aria-pressed',String(s.muted));for(const k of Object.keys(aux))aux[k].setAttribute('aria-pressed',String(s.visible[k]));video.textContent=s.hasVideo?'':entry?'音频 · '+entry.title:'选择本地媒体开始播放';PlaybackControls.mode(overlay,s);modeButton.disabled=false;if(document.activeElement!==rate)rate.value=s.rate;const tk=JSON.stringify(s.tracks);if(tk!==trackKey){trackKey=tk;trackSelect.replaceChildren(new Option('选择音轨/字幕',''),new Option('关闭字幕',JSON.stringify({type:'sub',id:'no'})));for(const t of s.tracks.filter(t=>['audio','sub'].includes(t.type)))trackSelect.add(new Option((t.type==='audio'?'音轨 ':'字幕 ')+t.id+' '+(t.title||t.lang||''),JSON.stringify({type:t.type,id:t.id})))}const bk=JSON.stringify(s.bookmarks);if(bk!==bookmarkKey){bookmarkKey=bk;const prior=bookmarks.value;bookmarks.replaceChildren(new Option('选择书签',''));for(const b of s.bookmarks)bookmarks.add(new Option((b.note||b.title)+' '+clock(b.position),b.id));bookmarks.value=prior}}
  if(kind==='queue'){updateQueueFamily(s.context);queueNotice.textContent=s.queueNotice||'';for(const row of libraryHost.querySelectorAll('[data-track]'))row.classList.toggle('selected',row.dataset.resource===entry?.resourceId&&row.dataset.track===entry?.memberId);const queue=s.queue.map(e=>e.queueEntryId===s.currentId&&!e.duration&&s.duration>0?{...e,duration:s.duration}:e);const key=JSON.stringify(queue);if(key!==queueKey){const previous=queueKey?JSON.parse(queueKey):[],orderChanged=previous.length!==queue.length||previous.some((e,i)=>e.queueEntryId!==queue[i].queueEntryId);if(orderChanged)queueReorder.cancel();queueKey=key;ReorderMotion.preserve(rows,()=>{const existing=new Map([...rows.children].map(row=>[row.dataset.id,row])),next=[];for(const entry of queue){let row=existing.get(entry.queueEntryId);if(!row){row=document.createElement('li');row.className='row';row.dataset.id=entry.queueEntryId;row.draggable=true;row.tabIndex=0;const name=button(entry.title,()=>{});name.title='双击播放';name.ondblclick=()=>run(()=>command({type:'play',id:entry.queueEntryId}));row.append(name,button('删除',()=>command({type:'remove',id:entry.queueEntryId})));}row.setAttribute('aria-label',entry.title+'，Alt 加上下键排序');const labelKey=JSON.stringify([entry.title,entry.artist,entry.duration]);if(row.dataset.labelKey!==labelKey){trackLabel(row.firstElementChild,entry);row.dataset.labelKey=labelKey;}next.push(row);existing.delete(entry.queueEntryId);}for(const row of existing.values())row.remove();if(!queueReorder.isDragging())ReorderMotion.move(rows,next);});}for(const row of rows.children)row.classList.toggle('selected',row.dataset.id===s.currentId)}
  if(kind==='lyricsSearch'&&lyricsTrackGeneration!==s.generation){lyricsTrackGeneration=s.generation;resetLyricsSearch();}
  if(kind==='lyrics'){updateLyricFullscreen(!!s.windowState?.lyrics?.fullscreen);updateLyricView(s.lyricView);if(lyricsTrackGeneration!==s.generation){lyricsTrackGeneration=s.generation;resetLyricsSearch();}const key=JSON.stringify(s.lyrics);if(key!==lyricKey){lyricKey=key;activeLine=-2;lyricLines.replaceChildren();if(s.lyrics.status!=='synced')lyricLines.textContent=s.lyrics.message;else for(const line of s.lyrics.lines){const p=document.createElement('div');p.className='line';const original=document.createElement('div');original.className='lyric-original';original.textContent=line.text;p.append(original);if(line.translation){const translation=document.createElement('div');translation.className='lyric-translation';translation.textContent=line.translation;p.append(translation);}lyricLines.append(p)}}let index=-1;s.lyrics.lines.forEach((line,i)=>{if(line.time+(s.lyricView?.offset||0)/1000<=s.position)index=i});if(index!==activeLine){activeLine=index;[...lyricLines.children].forEach((p,i)=>p.classList.toggle('active',i===index));lyricLines.children[index]?.scrollIntoView({block:'center',behavior:'smooth'})}}
  if(kind==='eq'){if(document.activeElement!==preamp)preamp.value=s.eq.preamp||0;preamp.title=preamp.value+' dB';eqEnable.textContent=s.eq.enabled?'禁用 EQ':'启用 EQ';eqEnable.setAttribute('aria-pressed',String(s.eq.enabled));eqInputs.forEach(({input,output},i)=>{if(document.activeElement!==input)input.value=s.eq.gains[i];output.textContent=input.value+' dB'})}
 }
 api.subscribe(render);api.snapshot().then(render).catch(e=>error.textContent=e.message);
})();
