const {test}=require('node:test'),assert=require('node:assert/strict'),Policy=require('../app/jikan-policy'),Network=require('../app/metadata-network');
test('5xx Jikan upstream diagnostics are specific, 429 remains rate limit',()=>{for(const status of [500,502,503,504]){const result=Network.classify(status,'','api.jikan.moe');assert.equal(result.kind,'upstream');assert.match(result.message,/Jikan.*MyAnimeList.*上游故障/);}assert.equal(Network.classify(429,'','api.jikan.moe').kind,'quota');assert.equal(Network.classify(504,'','other.example').kind,'server');});
test('breaker suppresses repeated outage then automatically probes recovery',()=>{let now=0;const p=Policy.create({now:()=>now,cooldown:30}),url='https://api.jikan.moe/v4/anime';p.observe(url,504);assert.equal(p.blocked(url),504);assert.equal(p.blocked('https://api.bgm.tv/v0/search'),0);now=31;assert.equal(p.blocked(url),0);p.observe(url,200);assert.equal(p.blocked(url),0);});
test('native requests stop retrying 504, cached outage retains diagnostics',async()=>{let count=0;const {nativeJson}=require('../app/native-json'),Runtime=require('../app/metadata-runtime');const url='https://api.jikan.moe/v4/anime';await Runtime.withDiagnostics(async issues=>{for(let i=0;i<3;i++)assert.equal(await nativeJson(async()=>{count++;return new Response('gateway',{status:504})},url,500),null);assert.equal(count,1);assert.equal(issues[0].kind,'upstream');});Policy.observe(url,200);});

test('504 不阻断独立 AniList，恢复后重新获取 Jikan',async()=>{
 const {createSourceSearch}=require('../app/metadata-sources'),Runtime=require('../app/metadata-runtime');let outage=true,malCalls=0;
 const api=createSourceSearch({pace:0,text:async()=>'',json:async(url)=>{if(url.includes('jikan')){malCalls++;if(outage){Network.fail(504,'',url);return null;}return {data:[]};}if(url.includes('graphql.anilist'))return {data:{Page:{media:[{id:1,title:{native:'Fixture'},genres:[],siteUrl:'https://anilist.co/anime/1'}]}}};return {};}});
 const first=await api.search('anime','Fixture');assert.equal(first.sources.find(s=>s.id==='anilist').items.length,1);assert.match(first.sources.find(s=>s.id==='myanimelist').message,/Jikan/);assert.ok(first.integrated.length);const previous=malCalls;outage=false;Runtime.clearCache();const next=await api.search('anime','Fixture');assert.ok(malCalls>previous);assert.equal(next.sources.find(s=>s.id==='myanimelist').state,'empty');
});
