const {test}=require('node:test'),assert=require('node:assert/strict'),{create}=require('../app/audio-lyrics-providers');
const item={audio:{kind:'music',artists:['Artist']}},track={title:'Song',artists:['Artist'],durationSeconds:100};
test('QQ candidates include artist, album, duration and actual provider; public lyric decodes',async()=>{const urls=[];const api=create({music:{},json:async(u,signal)=>{urls.push(u);assert.ok(signal);return u.includes('client_search')?{data:{song:{list:[1,2].map(id=>({songmid:'m'+id,songname:'Song',singer:[{name:'Artist'}],albumname:'Album '+id,interval:100}))}}}:{req_0:{code:0,data:{crypt:0,lyric:Buffer.from('[00:01]fixture').toString('base64')}}}}});const c=await api(item,track,new AbortController().signal,'qq');assert.equal(c.kind,'review');assert.deepEqual(c.choices[0],{id:'qq:m1',title:'Song',artist:'Artist',album:'Album 1',duration:100,provider:'qq'});const r=await api(item,track,new AbortController().signal,'qq','qq:m2');assert.equal(r.text,'[00:01]fixture');assert.equal(r.album,'Album 2');assert.ok(urls.some(u=>u.includes('u.y.qq.com')));});
test('Kugou follows public hash search and returned download grant without exposing access key',async()=>{const api=create({music:{},json:async u=>u.includes('song_search')?{status:1,data:{lists:[{MixSongID:1,SongName:'Song',Singers:[{name:'Artist'}],FileHash:'a'.repeat(32),AlbumName:'Album',Duration:100}]}}:u.includes('/search?')?{status:200,candidates:[{id:'lyric',accesskey:'public-result-grant',song:'Song',singer:'Artist'}]}:{status:200,content:Buffer.from('[00:01]fixture').toString('base64')}});const r=await api(item,track,undefined,'kugou');assert.equal(r.text,'[00:01]fixture');assert.equal(r.choices[0].provider,'kugou');assert.equal(r.choices[0].album,'Album');assert.ok(!JSON.stringify(r).includes('public-result-grant'));});
test('all sources routes explicit prefixed candidate to correct provider',async()=>{const api=create({music:{lyrics:async()=>{throw Error('must not query LRCLIB')}},json:async u=>u.includes('client_search')?{data:{song:{list:[{songmid:'m',songname:'Song',singer:[{name:'Artist'}],interval:100}]}}}:{req_0:{code:0,data:{lyric:Buffer.from('fixture').toString('base64')}}}});assert.equal((await api(item,track,undefined,'auto','qq:m')).text,'fixture');await assert.rejects(api(item,track,undefined,'kugou','qq:m'),/不属于/);});
test('new lyric sources retain error classification and real abort',async()=>{for(const [error,label]of [[new SyntaxError('bad'),'解析错误'],[Object.assign(Error(),{status:429}),'被限流'],[Object.assign(Error(),{status:403}),'HTTP 错误'],[Object.assign(Error(),{status:503}),'上游故障'],[new DOMException('timeout','TimeoutError'),'请求超时']]){const api=create({music:{},json:async()=>{throw error}});await assert.rejects(api(item,track,undefined,'qq'),new RegExp(label));}const c=new AbortController();let seen;const api=create({music:{},json:async(u,signal)=>{seen=signal;c.abort();signal.throwIfAborted()}});await assert.rejects(api(item,track,c.signal,'kugou'),{name:'AbortError'});assert.equal(seen,c.signal);});
test('LRCLIB and lyrics.ovh single results also expose consistent candidate fields',async()=>{const api=create({music:{lyrics:async()=>({kind:'plain',text:'fixture',title:'Song',artist:'Artist',duration:100,source:'LRCLIB'})},json:async()=>({lyrics:'fixture'})});for(const source of ['lrclib','ovh']){const r=await api(item,{...track,albumTitle:'Album'},undefined,source);assert.equal(r.choices[0].provider,source);assert.equal(r.choices[0].artist,'Artist');assert.equal(r.choices[0].album,'Album');}});


test('protected QQ content is explicitly skipped and malformed content is a parse error',async()=>{const api=crypt=>create({music:{},json:async u=>u.includes('client_search')?{data:{song:{list:[{songmid:'m',songname:'Song',singer:[{name:'Artist'}]}]}}}:{req_0:{code:0,data:crypt?{crypt:1,lyric:'protected'}:{lyric:'!invalid'}}}});const skipped=await api(true)(item,track,undefined,'qq');assert.equal(skipped.state,'skipped');assert.match(skipped.message,/未执行/);await assert.rejects(api(false)(item,track,undefined,'qq'),/解析错误/);});
