const {test}=require('node:test'),assert=require('node:assert/strict'),H=require('../app/metadata-html'),E=require('../app/metadata-enrichment'),N=require('../app/metadata-network'),B=require('../app/book-catalog-sources'),R=require('../app/metadata-runtime');
test('Douban nested full intro survives nested div/span and does not include author intro',()=>{const html='<div id="info">作者: 测试<br>ISBN: 9787536692930</div><div id="link-report"><div class="intro">短版</div><div class="all hidden"><div class="intro"><p>第一段<div>嵌套说明</div></p><p>第二段</p></div></div></div><div class="intro">作者的长简介不能进入摘要'.repeat(1)+'</div>';const d=E.doubanBook(html,{});assert.equal(d.description,'第一段嵌套说明\n第二段');assert.equal(d.isbn,'9787536692930');assert.ok(!d.description.includes('作者'));assert.equal(d.detailsUnavailable,false);});
test('summary is retained without info and supports public structured data',()=>{const html='<div id="link-report"><div class="intro">仅有简介</div></div>';assert.equal(E.doubanBook(html,{}).description,'仅有简介');assert.equal(E.doubanBook(html,{}).detailsUnavailable,true);assert.equal(H.summary('<script type="application/ld+json">{"@type":"Movie","description":"结构化简介"}</script>','movie'),'结构化简介');assert.equal(H.summary('<div id="link-report"><span property="v:summary">短摘要</span><span class="all hidden">完整<span>摘要</span>第二段</span></div>','movie'),'完整摘要第二段');});
test('Douban and 1lib browser challenges are unavailable instead of empty or synopsis',async()=>{for(const [host,body,status]of [['movie.douban.com','<form name="sec" id="sec" method="POST" action="/c">token</form>',200],['zh.1lib.sk','<title>Checking your browser ...</title>',503]])await R.withDiagnostics(async issues=>{assert.equal(await N.readResponse(new Response(body,{status}),'https://'+host+'/',true),'');assert.equal(issues[0].kind,'verification');});});
const book='<script type="application/ld+json">'+JSON.stringify({'@type':'Book',name:'测试书',description:'结构化摘要',author:{name:'作者'},publisher:{name:'出版社'},isbn:'9787536692930',datePublished:'2008',numberOfPages:302})+'</script><p itemprop="description">完整的公开简介</p>';
test('book catalogue parses only result cards and metadata, never download URLs',()=>{const page='<a href="/book/ad">推荐广告</a><div id="sr-0"><a href="../book/123"><b>测试书</b></a></div>';const rows=B.parseSearch(page,'tstrs');assert.equal(rows.length,1);const v=B.parseDetail(book,rows[0]);assert.equal(v.name,'测试书');assert.equal(v.description,'完整的公开简介');assert.equal(v.developer,'作者');assert.equal(v.pages,302);assert.equal(v.resourceUrl,undefined);assert.throws(()=>B.parseSearch('<html>登录</html>','tstrs'),SyntaxError);assert.deepEqual(B.parseSearch('没有找到相关书籍','tstrs'),[]);assert.throws(()=>B.parseDetail('invalid',rows[0]),SyntaxError);});
test('book sources are independent, registered only for books and preserve cancellation',async()=>{const Search=require('../app/metadata-sources').createSourceSearch({pace:0,json:async()=>null,text:async url=>url.startsWith('https://tstrs.me/search')?'<div id="sr-0"><a href="/book/123"><b>测试书</b></a></div>':url.startsWith('https://tstrs.me/book')?book:''});const b=await Search.search('book','测试书');assert.equal(b.sources.find(s=>s.id==='tstrs').items[0].description,'完整的公开简介');assert.equal(b.sources.find(s=>s.id==='onelib').state,'unavailable');assert.equal((await Search.search('manga','测试书')).sources.some(s=>['tstrs','onelib'].includes(s.id)),false);const request=R.run('240','cancel',()=>B.search({html:()=>new Promise((_,reject)=>R.signal().addEventListener('abort',()=>reject(R.signal().reason),{once:true}))},'name','tstrs'));R.cancel('240','cancel');await assert.rejects(request);});

test("catalogue missing-field placeholders stay empty and partial",()=>{const v=B.parseDetail(`<script type="application/ld+json">{"@type":"Book","name":"Book","description":"未找到信息","author":{"name":"【未找到作者信息】"}}</script>`,{});assert.equal(v.description,"");assert.equal(v.developer,"");assert.equal(v.detailsUnavailable,true);});
