const electron=require('electron'),{app,BrowserWindow,ipcMain}=electron,fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'yueden-234-')),out=path.resolve('test-artifacts/release-2.25.34');fs.mkdirSync(out,{recursive:true});app.setPath('userData',root);app.on('window-all-closed',()=>{});const checks=[],errors=[];let service,done=false;
const js=(w,s)=>w.webContents.executeJavaScript(s),win=k=>BrowserWindow.getAllWindows().find(w=>w.umPlayerKind===k),check=(name,ok)=>{assert.ok(ok,name);checks.push(name)};
async function until(fn,label){for(let i=0;i<120;i++){if(await fn())return;await new Promise(r=>setTimeout(r,50))}throw Error('Timeout '+label)}
async function finish(e){if(done)return;done=true;clearTimeout(deadline);await service?.close();fs.writeFileSync(path.join(out,'native-ui.json'),JSON.stringify({root,checks,errors,error:e?.stack,gesture:'DOM click/drag events; actual Electron, IPC and mpv; no physical mouse automation'},null,2));app.exit(e?1:0)}const deadline=setTimeout(()=>finish(Error('deadline')),90000);
app.on('browser-window-created',(_,w)=>w.webContents.on('console-message',(_e,level,m)=>{if(level===3)errors.push(m)}));
app.whenReady().then(async()=>{try{
 const file=JSON.parse(fs.readFileSync('app/player/test-artifacts/formats/manifest.json')).find(x=>x.name==='wav').file;
 const item=(id,kind='music',count=2)=>({id,type:'audio',name:id,audio:{kind,collectionKind:'album',artists:['Singer'],sources:[{id:'s',kind:'local',localPath:file}],tracks:Array.from({length:count},(_,i)=>({id:id+i,title:'Track '+String(i).padStart(3,'0')+' '+id,sourceRefs:['s'],durationSeconds:3}))}});
 const single=item('single','music',1);delete single.audio.kind;
 const lib={items:[item('a','music',120),item('b'),single,...['asmr','radio','other'].flatMap(k=>[item(k,k),item(k+'single',k,1)])],playlists:[{id:'mixed',name:'Cross album and legacy single',entries:[{itemId:'a',trackId:'a0'},{itemId:'b',trackId:'b0'},{itemId:'single',trackId:'single0'}]},{id:'historic',name:'Reclassified member',entries:[{itemId:'a',trackId:'a0'},{itemId:'asmr',trackId:'asmr0'}]}]},before=JSON.stringify(lib);
 const lyric={text:'[00:00]Original one\n[00:01]Original two\n[00:02]Original three',translation:'[00:00]第一行译文\n[00:01]第二行译文\n[00:02]第三行译文',source:'用户选择'};
 service=require('../app/player/dist/service').createPlayerService({electron,ipcMain,loadLibrary:()=>lib,dataRoot:()=>root,disguised:()=>false,audioLyrics:()=>({read:()=>lyric})});await service.show();const main=win('main');await js(main,'player.action("aux","queue")');const q=win('queue');
 await js(q,'player.resource('+JSON.stringify(lib.playlists[0].entries)+',"append",{kind:"playlist",id:"mixed"})');check('append playlist to inactive music context does not switch or start playback',service.snapshot().context==='video'&&service.snapshot().queue.length===0&&service.snapshot().status==='idle');
 await js(main,'player.action("context","music")');check('inactive music queue retains all album and single references',service.snapshot().queue.length===3);await js(main,'player.snapshot().then(s=>player.command({type:"play",id:s.queue[0].queueEntryId}))');await js(main,'player.command({type:"pause",paused:true})');
 const tab=async id=>{await js(q,'document.querySelector("[data-view='+id+']").click()');await until(()=>js(q,'document.querySelector("[data-view='+id+']").getAttribute("aria-pressed")==="true"'),'tab '+id);};
 await tab('songs');await until(()=>js(q,'document.querySelectorAll(".player-library>.row").length===123'),'songs');let generation=service.snapshot().generation;
 await js(q,'document.querySelector("[data-track=a1] .title").click();player.snapshot()');check('library single click never starts playback',service.snapshot().generation===generation);
 await js(q,'document.querySelector("[data-track=a1] .title").dispatchEvent(new MouseEvent("dblclick",{bubbles:true}))');await until(()=>service.snapshot().queue.find(e=>e.queueEntryId===service.snapshot().currentId)?.memberId==='a1','double play');await js(main,'player.command({type:"pause",paused:true})');check('library double click plays selected track',true);
 const drag=async(host,from,to,cancel=false)=>js(q,'(()=>{const h=document.querySelector('+JSON.stringify(host)+'),a=h.children['+from+'],b=h.children['+to+'];h.scrollTop=a.offsetTop-h.offsetTop-70;a.querySelector(".title")?.focus({preventScroll:true});window.testFocus=document.activeElement;const before=h.scrollTop,dt=new DataTransfer();a.dispatchEvent(new DragEvent("dragstart",{bubbles:true,dataTransfer:dt}));const r=b.getBoundingClientRect();b.dispatchEvent(new DragEvent("dragover",{bubbles:true,cancelable:true,dataTransfer:dt,clientY:r.bottom-1}));const preview=h.scrollTop;'+(cancel?'a.dispatchEvent(new DragEvent("dragend",{bubbles:true,dataTransfer:dt}));':'b.dispatchEvent(new DragEvent("drop",{bubbles:true,cancelable:true,dataTransfer:dt}));')+'return {before,preview,after:h.scrollTop,id:a.dataset.id};})()');
 let movement=await drag('.player-library',60,62,true);check('long library cancelled drag preserves scroll through preview and rollback',movement.before>300&&movement.before===movement.preview&&movement.before===movement.after);check('drag preserves focused resource',await js(q,'document.activeElement===window.testFocus'));
 movement=await drag('.player-library',60,62);await until(async()=>!!(await js(q,'player.library("songs")')).orders['["songs",null]'],'saved song order');check('library committed reorder preserves scroll after IPC acknowledgment',await js(q,'document.querySelector(".player-library").scrollTop')===movement.before);
 await js(q,'player.resource('+JSON.stringify(lib.items[0].audio.tracks.map(t=>({itemId:'a',trackId:t.id})))+',"append")');await tab('queue');await until(()=>js(q,'document.querySelectorAll("#rows>li").length===124'),'long queue');generation=service.snapshot().generation;await js(q,'document.querySelector("#rows .title").click();player.snapshot()');check('queue single click never starts playback',service.snapshot().generation===generation);
 movement=await drag('#rows',60,62);await until(()=>service.snapshot().queue[62]?.queueEntryId===movement.id,'queue backend order');await until(async()=>await js(q,'document.querySelector("#rows").children[62].dataset.id')===movement.id,'queue render acknowledgement');check('queue scroll and focus survive preview, commit and state render',movement.before>300&&movement.preview===movement.before&&await js(q,'document.querySelector("#rows").scrollTop')===movement.before&&await js(q,'document.activeElement===window.testFocus'));
 await js(q,'document.querySelector("#rows").children[62].dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,altKey:true,key:"ArrowUp"}))');await until(()=>service.snapshot().queue[61]?.queueEntryId===movement.id,'keyboard reorder');check('keyboard reorder preserves scroll',await js(q,'document.querySelector("#rows").scrollTop')===movement.before);
 for(const kind of ['asmr','radio','other']){await tab(kind);await until(()=>js(q,'document.querySelector(".player-library>.row")?.dataset.resource==='+JSON.stringify(kind+'single')),'flat singleton '+kind);check(kind+' singleton ignores historical collection flag',await js(q,'document.querySelectorAll(".player-library>.library-group").length===1'));check(kind+' collection initially shows only first resource',await js(q,'(()=>{const s=document.querySelector(".library-group");return s.classList.contains("collapsed")&&s.querySelector(".collection-toggle").getAttribute("aria-expanded")==="false"&&[...s.querySelectorAll(".row")].filter(n=>n.getClientRects().length).length===1})()'));await js(q,'document.querySelector(".collection-toggle").click()');await until(()=>js(q,'document.querySelector(".collection-toggle").getAttribute("aria-expanded")==="true"'),'expand');check(kind+' expanded tracks usable',await js(q,'[...document.querySelectorAll(".library-tracks>.row")].filter(n=>n.getClientRects().length).length===2'));}
 await tab('playlists');await until(()=>js(q,'document.querySelector(".queue-picker").options.length===3'),'playlists');await js(q,'const p=document.querySelector(".queue-picker");p.value="historic";p.dispatchEvent(new Event("change"));[...document.querySelectorAll(".library-group>button")].find(b=>b.textContent==="播放全部").click()');await until(()=>service.snapshot().generation>generation&&service.snapshot().queue.at(-1)?.memberId==='asmr0','mixed playlist play');await js(main,'player.command({type:"pause",paused:true})');check('playlist play-all accepts cross-album/reclassified members in music context',service.snapshot().context==='music');const count=service.snapshot().queue.length;await js(q,'[...document.querySelectorAll(".library-group>button")].find(b=>b.textContent==="加入队列").click()');await until(()=>service.snapshot().queue.length===count+2,'playlist append');check('playlist append retains all selected members',true);
 await js(q,'document.querySelector(".library-tracks [data-track=asmr0] .title").dispatchEvent(new MouseEvent("dblclick",{bubbles:true}))');await until(()=>service.snapshot().queue.find(e=>e.queueEntryId===service.snapshot().currentId)?.memberId==='asmr0','playlist track play');check('individual playlist track preserves playlist music context',service.snapshot().context==='music');await js(main,'player.command({type:"pause",paused:true})');
 await js(main,'player.action("aux","lyrics")');const lyrics=win('lyrics');await until(()=>js(lyrics,'document.querySelectorAll(".line").length===3'),'lyric groups');check('translation and original share one stacked group',await js(lyrics,'(()=>{const p=document.querySelector(".line"),a=p.querySelector(".lyric-original"),b=p.querySelector(".lyric-translation");return a&&b&&b.getBoundingClientRect().top>=a.getBoundingClientRect().bottom&&p.textContent.includes("第一行译文")})()'));
 await js(lyrics,'player.action("lyricView",{zoom:200})');await until(()=>js(lyrics,'document.querySelector("#lyricLines").style.fontSize==="200%"'),'zoom');check('translation font is 80 percent with weaker synchronized highlight',await js(lyrics,'(()=>{const p=document.querySelector(".line.active"),a=getComputedStyle(p.querySelector(".lyric-original")),b=getComputedStyle(p.querySelector(".lyric-translation"));return Math.abs(parseFloat(b.fontSize)-parseFloat(a.fontSize)*.8)<.1&&a.color!==b.color&&Number(a.fontWeight)>Number(b.fontWeight)})()'));
 await js(lyrics,'player.action("lyricView",{zoom:20})');await until(()=>js(lyrics,'document.querySelector("#lyricLines").style.fontSize==="20%"'),'small zoom');check('translation minimum is 14px',await js(lyrics,'getComputedStyle(document.querySelector(".lyric-translation")).fontSize==="14px"'));await js(main,'player.command({type:"seek",seconds:1.5})');await until(()=>js(lyrics,'document.querySelectorAll(".line")[1].classList.contains("active")'),'next lyric');check('previous group original and translation deactivate together',await js(lyrics,'(()=>{const p=document.querySelector(".line"),a=getComputedStyle(p.querySelector(".lyric-original")),b=getComputedStyle(p.querySelector(".lyric-translation"));return !p.classList.contains("active")&&a.color===b.color})()'));await js(lyrics,'player.action("lyricView",{zoom:200})');fs.writeFileSync(path.join(out,'bilingual-lyrics.png'),(await lyrics.webContents.capturePage()).toPNG());
 await js(main,'player.resource([{itemId:"asmr",trackId:"asmr0"},{itemId:"asmr",trackId:"asmr1"}],"play")');await js(main,'player.snapshot().then(s=>player.command({type:"play",id:s.queue.at(-1).queueEntryId}))');await js(main,'player.command({type:"pause",paused:true})');await js(main,'player.action("mode","all")');await until(()=>js(main,'!document.querySelector("[data-mode-control]").disabled'),'mode enabled');check('mode remains enabled on final ASMR entry',service.snapshot().repeat==='all');const first=service.snapshot().queue[0].queueEntryId;await js(main,'player.command({type:"seek",seconds:2.8})');await js(main,'player.command({type:"pause",paused:false})');await until(()=>service.snapshot().currentId===first,'actual EOF list loop');await js(main,'player.command({type:"pause",paused:true})');check('actual mpv EOF loops final track to first',true);
 const asmrState=service.snapshot();await js(main,'player.resource('+JSON.stringify(lib.playlists[0].entries)+',"append",{kind:"playlist",id:"mixed"})');check('append music playlist leaves ASMR session and queue untouched',service.snapshot().context==='asmr'&&service.snapshot().currentId===asmrState.currentId&&service.snapshot().queue.length===asmrState.queue.length&&service.snapshot().generation===asmrState.generation);
 check('library remains unchanged',JSON.stringify(lib)===before);check('no renderer errors',errors.length===0);await finish();
 }catch(e){await finish(e)}});
