const electron=require('electron'),{app,BrowserWindow,ipcMain}=electron,fs=require('fs'),os=require('os'),path=require('path'),cp=require('child_process'),assert=require('assert/strict');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'yueden-235-')),out=path.resolve('test-artifacts/release-2.25.35');fs.mkdirSync(out,{recursive:true});app.setPath('userData',root);app.on('window-all-closed',()=>{});const checks=[],errors=[];let service,done=false,hwnd;
const Surface=require('../app/player/dist/surface').NativeSurface,open=Surface.prototype.open;Surface.prototype.open=async function(...args){hwnd=await open.apply(this,args);return hwnd};
const js=(w,s)=>w.webContents.executeJavaScript(s),win=k=>BrowserWindow.getAllWindows().find(w=>w.umPlayerKind===k),check=(name,ok)=>{assert.ok(ok,name);checks.push(name)};async function until(fn,label){for(let i=0;i<120;i++){if(await fn())return;await new Promise(r=>setTimeout(r,50))}throw Error('Timeout '+label)}
async function finish(e){if(done)return;done=true;clearTimeout(deadline);await service?.close();fs.writeFileSync(path.join(out,'native-ui.json'),JSON.stringify({root,checks,errors,error:e?.stack,nativeInput:'Messages delivered to verified YueDenVideoSurface HWND; no global hooks or physical mouse automation'},null,2));app.exit(e?1:0)}const deadline=setTimeout(()=>finish(Error('deadline')),90000);app.on('browser-window-created',(_,w)=>w.webContents.on('console-message',(_e,l,m)=>{if(l===3)errors.push(m)}));
app.whenReady().then(async()=>{try{
 const formats=JSON.parse(fs.readFileSync('app/player/test-artifacts/formats/manifest.json')),video=path.join(out,'long-video.mp4'),second=path.join(out,'second-video.mp4'),audio=formats.find(x=>x.name==='wav').file;cp.execFileSync(path.resolve('app/codec/bin/ffmpeg.exe'),['-v','error','-y','-stream_loop','9','-i',formats.find(x=>x.name==='h264').file,'-t','20','-c','copy',video],{windowsHide:true,timeout:20000});fs.copyFileSync(video,second);
 const lib={items:[{id:'collection',type:'movie',name:'Film collection',localFiles:[{path:video,name:'Part A'},{path:second,name:'Part B'}]},{id:'single',type:'movie',name:'Single film',localPath:video},{id:'anime',type:'anime',name:'Anime collection',localFiles:[{path:video,name:'Episode 1'},{path:second,name:'Episode 2'}]},{id:'audio',type:'audio',name:'Audio',audio:{kind:'music',collectionKind:'single',sources:[{id:'s',kind:'local',localPath:audio}],tracks:[{id:'t',title:'Audio track',sourceRefs:['s']}]}}]},before=JSON.stringify(lib);
 service=require('../app/player/dist/service').createPlayerService({electron,ipcMain,loadLibrary:()=>lib,dataRoot:()=>root,disguised:()=>false});await service.openResource('collection');const main=win('main');await until(()=>service.snapshot().status==='playing'&&service.snapshot().duration>10,'video');await js(main,'player.command({type:"pause",paused:true})');await until(()=>service.snapshot().status==='paused','pause');await js(main,'player.action("aux","queue")');const q=win('queue');await until(()=>js(q,'document.querySelectorAll(".queue-tabs>button").length===3'),'video tabs');check('video family has only queue movie and anime tabs',await js(q,'[...document.querySelectorAll(".queue-tabs>button")].map(b=>b.dataset.view).join(",")==="queue,movie,anime"'));
 await js(q,'document.querySelector("[data-view=movie]").click()');await until(()=>js(q,'document.querySelectorAll(".player-library>.row").length===1'),'movie view');check('video singleton flat and collection collapsed showing first actual file',await js(q,'document.querySelector(".player-library>.row").dataset.resource==="single"&&document.querySelector(".library-group.collapsed")&&[...document.querySelectorAll(".library-tracks>.row")].filter(n=>n.getClientRects().length).length===1'));
 await js(q,'document.querySelector("[data-view=movie]").dispatchEvent(new MouseEvent("contextmenu",{bubbles:true,cancelable:true}))');check('video right-click sort uses name and all three order choices',await js(q,'document.querySelectorAll("[name=field]").length===1&&document.querySelectorAll("[name=order]").length===3'));await js(q,'document.querySelector("[name=order][value=desc]").click();[...document.querySelectorAll(".app-dialog-actions button")].find(b=>b.textContent==="应用排序").click()');await until(()=>js(q,'!document.querySelector(".queue-options")'),'sort saved');check('video sort changes presentation only',JSON.stringify(lib)===before&&await js(q,'document.querySelector(".player-library").firstElementChild.dataset.resource==="single"'));
 await js(q,'document.querySelector(".collection-toggle").click()');await until(()=>js(q,'document.querySelector(".collection-toggle").getAttribute("aria-expanded")==="true"'),'expanded');await js(q,'document.querySelector(".library-tracks").firstElementChild.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowDown",altKey:true,bubbles:true,cancelable:true}))');await until(async()=>!!(await js(q,'player.library("movie")')).orders['["movie","collection"]'],'video track order');check('video stable file identities reorder independently',await js(q,'JSON.parse(document.querySelector(".library-tracks").firstElementChild.dataset.ref).file==='+JSON.stringify(video)));
 await js(q,'[...document.querySelectorAll(".library-group>button")].find(b=>b.textContent==="播放全部").click()');await until(()=>service.snapshot().queue.find(e=>e.queueEntryId===service.snapshot().currentId)?.path===video&&service.snapshot().queue.length===4,'group play order');await js(main,'player.command({type:"pause",paused:true})');check('play-all uses displayed video file order',true);
 await js(q,'document.querySelector("[data-view=anime]").click()');await until(()=>js(q,'document.querySelector(".library-group")?.textContent.includes("Anime collection")'),'anime');check('anime uses its own main-library items and same collapsed presentation',await js(q,'document.querySelector(".library-group").classList.contains("collapsed")&&document.querySelector(".library-tracks>.row").dataset.resource==="anime"'));lib.items.push({id:'new',type:'anime',name:'New anime',localPath:video});require('../app/library-events').changed();await until(()=>js(q,'document.querySelector(".player-library>.row")?.dataset.resource==="new"'),'live source update');check('library change refreshes video list without a second library',true);lib.items.pop();
 await js(main,'document.querySelector(".advanced").open=true');check('sleep and bookmark inputs use theme tokens and accessible labels',await js(main,'(()=>{const a=document.querySelector("input[aria-label=睡眠分钟]"),b=document.querySelector("input[aria-label=书签备注]");return getComputedStyle(a).backgroundColor===getComputedStyle(b).backgroundColor&&getComputedStyle(a).borderRadius!=="0px"})()'));
 await js(main,'player.command({type:"seek",seconds:5})');await until(()=>service.snapshot().position>4.8,'seek baseline');await js(main,'document.activeElement.blur();for(let i=0;i<5;i++)document.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowRight",repeat:i>0,bubbles:true,cancelable:true}))');await until(()=>service.snapshot().position>9.8,'held right');check('five keydown events advance five seconds before any keyup',Math.abs(service.snapshot().position-10)<.15);
 await js(main,'player.command({type:"volume",value:50,muted:false})');await js(main,'for(let i=0;i<7;i++)document.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowUp",repeat:i>0,bubbles:true,cancelable:true}))');await until(()=>service.snapshot().volume===57,'held up');check('held up changes volume in one-percent steps',true);await js(main,'document.getElementById("video").dispatchEvent(new WheelEvent("wheel",{deltaY:100,bubbles:true,cancelable:true}))');await until(()=>service.snapshot().volume===56,'wheel');check('renderer wheel changes volume immediately',true);
 await js(main,'const note=document.querySelector("input[aria-label=书签备注]");note.focus();note.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowRight",bubbles:true}));player.snapshot()');check('editing bookmark does not seek',Math.abs(service.snapshot().position-10)<.15);
 const native=commands=>require('util').promisify(cp.execFile)(path.resolve('tests/InputProbe.exe'),[hwnd,commands],{windowsHide:true,timeout:5000});await native('focus,37,37,37');await until(()=>service.snapshot().position<7.2,'native held left');check('native video key repeats clear stale editor focus and seek before release',Math.abs(service.snapshot().position-7)<.15);await native('38,38,wheelup');await until(()=>service.snapshot().volume===59,'native volume');check('native video keyboard and wheel share exact volume state',true);await native('wheeldown,40');await until(()=>service.snapshot().volume===57,'native down');await native('double');await until(()=>service.snapshot().status==='playing','native double play');await native('double');await until(()=>service.snapshot().status==='paused','native double pause');check('native double-click toggles playback through one mpv session',true);
 await js(main,'player.action("fullscreen")');await until(()=>main.isFullScreen(),'fullscreen');await native('focus,39,wheelup');await until(()=>service.snapshot().volume===58,'fullscreen input');check('native shortcuts work in fullscreen',true);await js(main,'player.action("fullscreen")');await until(()=>!main.isFullScreen(),'exit fullscreen');
 await js(main,'player.resource([{itemId:"audio",trackId:"t"}],"play")');await js(main,'player.command({type:"pause",paused:true})');await until(()=>js(q,'document.querySelectorAll(".queue-tabs>button").length===7'),'audio family');await until(()=>service.snapshot().status==='paused'&&service.snapshot().duration>0,'audio backend paused');check('switch to audio restores all seven original tabs',await js(q,'!document.querySelector("[data-view=movie]")&&!!document.querySelector("[data-view=playlists]")'));await js(main,'document.activeElement.blur();document.getElementById("video").dispatchEvent(new MouseEvent("dblclick",{bubbles:true}))');await until(()=>service.snapshot().status==='playing','audio double');check('audio viewport double-click also toggles playback',true);await js(main,'player.command({type:"pause",paused:true})');check('library unchanged by playback and sorting',JSON.stringify(lib)===before);check('no renderer errors',errors.length===0);fs.writeFileSync(path.join(out,'main-controls.png'),(await main.webContents.capturePage()).toPNG());await finish();
 }catch(e){fs.writeFileSync(path.join(out,'native-failure-state.json'),JSON.stringify({snapshot:service?.snapshot(),dom:win('main')&&!win('main').isDestroyed()?await js(win('main'),'({focus:document.activeElement?.outerHTML,modals:document.querySelectorAll("[data-app-modal]").length,error:document.getElementById("error").textContent})'):null},null,2));await finish(e)}});
