const electron=require('electron'),{app,BrowserWindow,ipcMain}=electron,fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'yueden-230-ui-'));app.setPath('userData',root);app.on('window-all-closed',()=>{});const checks=[],errors=[],saved=new Map(),signals=[];let service,done=false;
const js=(w,s)=>w.webContents.executeJavaScript(s),win=kind=>BrowserWindow.getAllWindows().find(w=>w.umPlayerKind===kind);
const until=async(fn,label)=>{for(let n=0;n<100;n++){if(await fn())return;await new Promise(r=>setTimeout(r,50))}throw Error('Timeout '+label)};
const check=(name,value)=>{assert.ok(value,name);checks.push(name)};
async function finish(error){if(done)return;done=true;clearTimeout(deadline);await service?.close();fs.mkdirSync('test-artifacts/release-2.25.30',{recursive:true});fs.writeFileSync('test-artifacts/release-2.25.30/native-ui.json',JSON.stringify({checks,errors,root,error:error?.stack,lyricsProvider:'controlled fixture; not an online result'},null,2));app.exit(error?1:0)}
const deadline=setTimeout(()=>finish(Error('timeout')),45000);
app.on('browser-window-created',(_,w)=>w.webContents.on('console-message',(_e,level,message)=>{if(level===3)errors.push(message)}));
app.whenReady().then(async()=>{try{
 const audio=JSON.parse(fs.readFileSync('app/player/test-artifacts/formats/manifest.json')).find(v=>v.name==='wav').file;
 const item={id:'a',type:'audio',name:'Album A',audio:{kind:'music',collectionKind:'album',artists:['Artist'],sources:[{id:'src',kind:'local',localPath:audio}],tracks:[{id:'t',title:'Track A',artists:['Artist'],sourceRefs:['src']}]}};
 const lib={items:[item],playlists:[{id:'p',name:'Playlist A',entries:[{itemId:'a',trackId:'t'}]}]};
 service=require('../app/player/dist/service').createPlayerService({electron,ipcMain,loadLibrary:()=>lib,dataRoot:()=>root,disguised:()=>false,audioLyrics:()=>({preferences:()=>({online:true}),read:id=>saved.get(id),save:(id,value)=>saved.set(id,value),query:async(item,track,signal)=>{signals.push(signal);return {kind:'synced',source:'fixture',text:'[00:00]Fixture line\n[00:01]Second line'}}})});
 await service.show();const main=win('main');await js(main,'player.resource([{itemId:"a",trackId:"t"}],"play")');await js(main,'player.command({type:"pause",paused:true})');
 for(const kind of ['lyrics','queue'])await js(main,'player.action("aux",'+JSON.stringify(kind)+')');const lyrics=win('lyrics'),queue=win('queue');
 await until(()=>js(queue,'document.querySelectorAll("#rows>li").length===1'),'queue');check('actual queue renders',true);check('append file control removed',await js(queue,'!document.body.textContent.includes("添加文件（追加）")'));
 const clickAt=await js(queue,'(()=>{const s=document.querySelector(".queue-picker"),original=s.showPicker.bind(s);window.pickerOpened=0;s.showPicker=()=>{window.pickerOpened++;return original()};const r=document.querySelector("[data-view=albums]").getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()');queue.show();queue.focus();queue.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...clickAt});queue.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...clickAt});await until(()=>js(queue,'document.querySelector("[data-view=albums]").getAttribute("aria-pressed")=="true"'),'album tab selected');check('album tab does not automatically open dropdown on real click',await js(queue,'window.pickerOpened===0'));await until(()=>js(queue,'document.querySelector(".queue-picker").options.length===2'),'album picker');await js(queue,'(()=>{const s=document.querySelector(".queue-picker");s.value="a";s.dispatchEvent(new Event("change"))})()');check('selected album displays actual track reference',await js(queue,'document.querySelector(".player-library [data-track]").dataset.track==="t"'));
 await js(queue,'document.querySelector("[data-view=playlists]").click()');await until(()=>js(queue,'document.querySelector(".queue-picker").textContent.includes("Playlist A")'),'playlist');await js(queue,'(()=>{const s=document.querySelector(".queue-picker");s.value="p";s.dispatchEvent(new Event("change"))})()');check('playlist tracks match same library',await js(queue,'document.querySelector(".player-library [data-track]").dataset.track==="t"'));lib.playlists=[];require('../app/library-events').changed();await until(()=>js(queue,'!document.querySelector(".queue-picker").textContent.includes("Playlist A")'),'live delete');check('playlist changes sync',true);
 queue.setSize(320,300);check('narrow tabs remain single scrollable row',await js(queue,'(()=>{const n=document.querySelector(".queue-tabs");return getComputedStyle(n).overflowX==="auto"&&new Set([...n.children].map(b=>b.offsetTop)).size===1})()'));
 check('lyrics window no longer contains search inputs',await js(lyrics,'!document.querySelector("[aria-label=歌曲名称]")'));
 await js(lyrics,'player.action("lyricView",{zoom:400,offset:10,align:"right"})');await until(()=>js(lyrics,'document.querySelector("[aria-label=歌词缩放百分比]").value==="400"'),'zoom');await js(lyrics,'document.querySelector("[aria-label=放大歌词]").click()');check('zoom clamps at 400',await js(lyrics,'player.snapshot().then(s=>s.lyricView.zoom===400)'));await js(lyrics,'player.action("lyricView",{zoom:20})');await js(lyrics,'document.querySelector("[aria-label=缩小歌词]").click()');check('zoom clamps at 20',await js(lyrics,'player.snapshot().then(s=>s.lyricView.zoom===20)'));await js(lyrics,'player.action("lyricView",{zoom:100})');await js(lyrics,'document.querySelector("[aria-label=放大歌词]").click()');await until(()=>js(lyrics,'player.snapshot().then(s=>s.lyricView.zoom===105)'),'zoom step');check('zoom step is 5 percent',true);await js(lyrics,'document.querySelector("[aria-label="+JSON.stringify("歌词提前 10ms")+"]").click()');await until(()=>js(lyrics,'player.snapshot().then(s=>s.lyricView.offset===0)'),'offset');check('offset step is 10ms',true);
 lyrics.setSize(300,300);fs.writeFileSync('test-artifacts/release-2.25.30/lyrics-narrow.png',(await lyrics.webContents.capturePage()).toPNG());check('toolbar below lyrics and horizontally reachable',await js(lyrics,'(()=>{const a=document.getElementById("lyricLines").getBoundingClientRect(),b=document.querySelector(".lyrics-toolbar");return a.bottom<=b.getBoundingClientRect().top+1&&getComputedStyle(b).overflowX==="auto"})()'));
 for(let i=0;i<3;i++){await js(lyrics,'document.querySelector("[aria-label=搜索歌词]").click()');await until(()=>win('lyricsSearch'),'search window');const search=win('lyricsSearch');await until(()=>js(search,'document.querySelector("textarea").value.includes("Fixture line")'),'automatic search');check('separate native modal search '+i,search!==lyrics&&search.getParentWindow()===lyrics&&search.isModal());check('search uses current track '+i,await js(search,'document.querySelector("[aria-label=歌曲名称]").value==="Track A"'));if(i===0)fs.writeFileSync('test-artifacts/release-2.25.30/lyrics-search.png',(await search.webContents.capturePage()).toPNG());check('result count visible '+i,await js(search,'document.querySelector("[role=status]").textContent.includes("1 条结果")'));await js(search,'[...document.querySelectorAll("button")].find(b=>b.textContent==="替换").click()');await until(()=>saved.has('t'),'replace saved');search.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});await until(()=>!win('lyricsSearch'),'search closed');check('closing search cancels request signal '+i,signals.at(-1).aborted);}
 check('lyrics replaced and visible',await js(lyrics,'document.getElementById("lyricLines").textContent.includes("Fixture line")'));check('parent lyrics remains open',lyrics.isVisible());check('no renderer errors',errors.length===0);
 await service.close();await service.show();check('lyric display preferences survive reopen',service.snapshot().lyricView.zoom===105&&service.snapshot().lyricView.align==='right');await finish();
 }catch(e){await finish(e)}});
