module.exports=async({w,js,check,until,root})=>{
const fs=require('fs'),path=require('path'),out=path.resolve('test-artifacts/release-2.25.41');fs.mkdirSync(out,{recursive:true});const records={},items=[];for(const [n,type]of ['game','movie','anime','manga','book','audio'].entries())for(let i=0;i<7;i++){const id=type+i;items.push({id,type,name:({game:'星海远航',movie:'山间来信',anime:'风与旅人',manga:'花园日记',book:'时间与书页',audio:'雨夜钢琴'})[type]+' · '+(i+1),playtime:type==='book'?null:(7-i)*(n+1)/2,cover:'data:image/svg+xml;base64,'+Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="50" height="70"><rect width="50" height="70" fill="'+['#56bba0','#638cda','#af80d1','#d99a4d','#cb738e','#53adbf'][n]+'"/><circle cx="25" cy="28" r="15" fill="white" opacity=".4"/></svg>').toString('base64')});records[id]={seconds:(7-i)*(n+1)*1800,openedAt:new Date(Date.UTC(2026,8,1+i)).toISOString()};}fs.writeFileSync(path.join(root,'usage-records.json'),JSON.stringify(records));
await js(w,'(async()=>{state=await native.saveLibrary({...state,items:'+JSON.stringify(items)+'});await refreshUsage();activeView="dashboard";render();})()');w.setContentSize(1360,960);await js(w,'new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
check('heading and all six categories present',await js(w,'$("usagePanel").querySelector("h2").textContent==="时长统计"&&$("usagePanel").querySelectorAll(".usage-legend button").length===6&&$("usagePanel").querySelectorAll(".usage-segment").length===6'));
await js(w,'$("usagePanel").querySelector("button[data-usage-type=book]").click()');check('legend click switches both rankings',await js(w,'[...$("usagePanel").querySelectorAll(".usage-ranking h3")].every(e=>e.textContent.includes("书籍"))'));
check('recent five order differs from longest five',await js(w,'(()=>{const groups=[...$("usagePanel").querySelectorAll(".usage-ranking")].map(g=>[...g.querySelectorAll(".usage-resource")].map(e=>e.textContent.trim()));return groups[0].length===5&&groups[1].length===5&&groups[0][0].endsWith("7")&&groups[1][0].endsWith("1")})()'));
check('resource names and covers share left half with cover nearest axis',await js(w,'(()=>{const e=$("usagePanel").querySelector(".usage-resource"),name=e.firstElementChild.getBoundingClientRect(),cover=e.querySelector("img").getBoundingClientRect(),bar=e.nextElementSibling.getBoundingClientRect();return cover.left>=name.right&&cover.right<=bar.left&&Math.abs(cover.y-name.y)<20})()'));
await js(w,'$("usagePanel").querySelector("path[data-usage-type=movie]").dispatchEvent(new PointerEvent("pointerenter"))');check('ring hover highlights segment and switches rankings',await js(w,'$("usagePanel").querySelector("path[data-usage-type=movie]").classList.contains("selected")&&$("usagePanel").querySelector(".usage-ranking h3").textContent.includes("影视")'));
check('two charts right of ring and vertically stacked',await js(w,'(()=>{const ring=$("usagePanel").querySelector(".usage-overview").getBoundingClientRect(),charts=[...$("usagePanel").querySelectorAll(".usage-ranking")].map(e=>e.getBoundingClientRect());return charts[0].left>ring.right&&charts[1].top>charts[0].bottom})()'));
check('bar and resource entry animations configured',await js(w,'getComputedStyle($("usagePanel").querySelector(".usage-bar")).animationName==="usage-grow"&&getComputedStyle($("usagePanel").querySelector(".usage-resource")).animationName==="usage-pop"'));
check('duration precision and editor 0.1h step',await js(w,'$("fieldPlaytime").step==="0.1"&&[...$("usagePanel").querySelectorAll(".usage-bar-area strong")].every(e=>/^\\d+\\.\\dh$/.test(e.textContent))'));
await js(w,'openEditor("book0")');check('automatic reading duration appears in editor',await js(w,'$("fieldPlaytime").value==="17.5"&&editorMetadata.playtimeSource==="本机记录"'));await js(w,'$("fieldPlaytime").value="0";$("fieldPlaytime").dispatchEvent(new Event("input",{bubbles:true}));saveEditor({preventDefault(){}})');await until(()=>js(w,'$("editorBackdrop").classList.contains("hidden")'));await js(w,'(async()=>{state=await native.loadLibrary();openEditor("book0")})()');check('manual zero remains after reload',await js(w,'$("fieldPlaytime").value==="0"&&editorMetadata.playtimeSource==="手动"'));await js(w,'closeEditor();renderUsageChart();$("usagePanel").scrollIntoView({block:"center"});document.getAnimations().forEach(a=>a.finish())');fs.writeFileSync(path.join(out,'overview-dark.png'),(await w.webContents.capturePage()).toPNG());
await js(w,'settings.appearance.theme="paper";YueDenAppearance.apply(settings.appearance);document.getAnimations().forEach(a=>a.finish())');fs.writeFileSync(path.join(out,'overview-light.png'),(await w.webContents.capturePage()).toPNG());
await js(w,'window.usageSavedItems=state.items;window.usageSavedRecords=window.usageData;state.items=[];window.usageData={};renderUsageChart()');check('empty six-type overview has finite values and empty rankings',await js(w,'$("usagePanel").querySelectorAll(".usage-legend button").length===6&&$("usagePanel").querySelectorAll(".usage-empty").length===2&&!/NaN|Infinity/.test($("usagePanel").textContent)'));await js(w,'state.items=window.usageSavedItems;window.usageData=window.usageSavedRecords;renderUsageChart();document.body.classList.add("no-animations")');check('user animation preference is respected',await js(w,'parseFloat(getComputedStyle($("usagePanel").querySelector(".usage-bar")).animationDuration)<.001'));w.setMinimumSize(700,600);w.setSize(850,900);await js(w,'new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');check('narrow overview does not overflow horizontally',await js(w,'document.body.scrollWidth<=innerWidth&&$("usagePanel").scrollWidth<=$("usagePanel").clientWidth'));
};
