const electron=require('electron'),{app,BrowserWindow,ipcMain}=electron,fs=require('fs'),os=require('os'),path=require('path'),cp=require('child_process'),assert=require('assert/strict');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'yueden-233-')),out=path.resolve('test-artifacts/release-2.25.33');fs.mkdirSync(out,{recursive:true});app.setPath('userData',root);app.on('window-all-closed',()=>{});const checks=[],errors=[];let service,done=false,peer;
const js=(w,s)=>w.webContents.executeJavaScript(s),win=k=>BrowserWindow.getAllWindows().find(w=>w.umPlayerKind===k),check=(name,ok)=>{assert.ok(ok,name);checks.push(name)},handle=w=>w.getNativeWindowHandle().readBigUInt64LE().toString();
async function until(fn,label){for(let i=0;i<100;i++){if(await fn())return;await new Promise(r=>setTimeout(r,50))}throw Error('Timeout '+label)}
async function finish(e){if(done)return;done=true;clearTimeout(deadline);peer?.destroy();await service?.close();fs.writeFileSync(path.join(out,'native-ui.json'),JSON.stringify({root,checks,errors,error:e?.stack,gesture:'DOM drag events; real Electron windows, input hover and native z-order'},null,2));app.exit(e?1:0)}const deadline=setTimeout(()=>finish(Error('deadline')),60000);
app.on('browser-window-created',(_,w)=>w.webContents.on('console-message',(_e,level,m)=>{if(level===3)errors.push(m)}));
app.whenReady().then(async()=>{try{
 const file=JSON.parse(fs.readFileSync('app/player/test-artifacts/formats/manifest.json')).find(x=>x.name==='wav').file;
 const item=(id,kind='music',collection='album')=>({id,type:'audio',name:id,audio:{kind,collectionKind:collection,artists:['Singer'],sources:[{id:'s',kind:'local',localPath:file}],tracks:[{id:id+'1',title:'First '+id,sourceRefs:['s'],durationSeconds:123},...(collection==='single'?[]:[{id:id+'2',title:'Second '+id,sourceRefs:['s'],durationSeconds:234}])]}});
 const lib={items:[item('a'),item('set','asmr'),item('single','asmr','single'),item('radio','radio'),item('other','other')],playlists:[{id:'list',name:'List',entries:[{itemId:'a',trackId:'a1'},{itemId:'a',trackId:'a1'},{itemId:'a',trackId:'a2'}]}]},before=JSON.stringify(lib);
 service=require('../app/player/dist/service').createPlayerService({electron,ipcMain,loadLibrary:()=>lib,dataRoot:()=>root,disguised:()=>false});await service.show();const main=win('main');await js(main,'player.resource([{itemId:"a",trackId:"a1"}],"play")');await js(main,'player.command({type:"pause",paused:true})');for(const k of ['queue','lyrics','eq'])await js(main,'player.action("aux",'+JSON.stringify(k)+')');const q=win('queue');
 check('fullscreen precedes minimize in titlebar',await js(main,'document.querySelector("[aria-label=全屏]").nextElementSibling.getAttribute("aria-label")==="最小化"&&!document.querySelector("#app>header [aria-label=全屏]")'));check('speed and combined mode share transport row; old selector removed',await js(main,'document.querySelector("[aria-label=播放速度]").parentElement===document.querySelector("[data-mode-control]").parentElement&&document.querySelectorAll("[data-mode-control]").length===1&&!document.querySelector("select[aria-label=播放模式]")&&document.querySelector(".advanced summary").textContent==="睡眠、字幕、书签"'));
 for(const [repeat,shuffle,icon]of [['all',false,'repeat'],['one',false,'single'],['none',true,'shuffle'],['none',false,'order']]){await js(main,'document.querySelector("[data-mode-control]").click()');await until(()=>service.snapshot().repeat===repeat&&service.snapshot().shuffle===shuffle,'mode '+icon);await until(()=>js(main,'document.querySelector("[data-mode-control]").dataset.playbackIcon==='+JSON.stringify(icon)),'mode icon');}check('one control cycles all four playback modes',true);
 await js(main,'const rate=document.querySelector("[aria-label=播放速度]");rate.value="1.25";rate.dispatchEvent(new Event("change"))');await until(()=>service.snapshot().rate===1.25,'speed');check('transport speed changes actual session',true);fs.writeFileSync(path.join(out,'main-controls.png'),(await main.webContents.capturePage()).toPNG());
 const tab=async id=>{await js(q,'document.querySelector("[data-view='+id+']").click()');await until(()=>js(q,'document.querySelector("[data-view='+id+']").getAttribute("aria-pressed")==="true"'),'tab');if(id!=='queue')await js(q,'player.library('+JSON.stringify(id)+')');};
 const drag=async(host,from,to,cancel=false)=>js(q,'(async()=>{const h=document.querySelector('+JSON.stringify(host)+'),a=h.children['+from+'],b=h.children['+to+'],dt=new DataTransfer();a.dispatchEvent(new DragEvent("dragstart",{bubbles:true,dataTransfer:dt}));const r=b.getBoundingClientRect();b.dispatchEvent(new DragEvent("dragover",{bubbles:true,cancelable:true,dataTransfer:dt,clientY:r.bottom-1}));const preview=[...h.children].map(n=>n.dataset.id);'+(cancel?'a.dispatchEvent(new DragEvent("dragend",{bubbles:true,dataTransfer:dt}));':'b.dispatchEvent(new DragEvent("drop",{bubbles:true,cancelable:true,dataTransfer:dt}));')+'return preview;})()');
 await tab('songs');await until(()=>js(q,'document.querySelectorAll(".player-library>.row").length===2'),'songs');const original=await js(q,'[...document.querySelector(".player-library").children].map(n=>n.dataset.id)');const preview=await drag('.player-library',0,1,true);check('cancelled song drag previews and restores',preview[0]!==original[0]&&JSON.stringify(await js(q,'[...document.querySelector(".player-library").children].map(n=>n.dataset.id)'))===JSON.stringify(original));await drag('.player-library',0,1);await until(async()=>!!(await js(q,'player.library("songs")')).orders['["songs",null]'],'save song order');await tab('albums');await tab('songs');await until(()=>js(q,'document.querySelector(".player-library>.row").dataset.track==="a2"'),'song order restored');check('song drag survives view changes without library mutation',JSON.stringify(lib)===before);
 await tab('playlists');await until(()=>js(q,'document.querySelector(".queue-picker").options.length===2'),'list picker');await js(q,'const p=document.querySelector(".queue-picker");p.value="list";p.dispatchEvent(new Event("change"))');await drag('.library-tracks',0,2);await until(async()=>!!(await js(q,'player.library("playlists")')).orders['["playlists","list"]'],'playlist order');fs.writeFileSync(path.join(out,'playlist-reorder.png'),(await q.webContents.capturePage()).toPNG());check('playlist duplicate references reorder independently',await js(q,'new Set([...document.querySelector(".library-tracks").children].map(n=>n.dataset.id)).size===3'));
 await tab('asmr');await until(()=>js(q,'document.querySelector(".player-library>.library-group")'),'mixed view');await drag('.player-library',0,1);await until(async()=>!!(await js(q,'player.library("asmr")')).orders['["asmr",null]'],'collection order');check('whole collection moves alongside single item',await js(q,'document.querySelector(".player-library").lastElementChild.classList.contains("library-group")'));await js(q,'document.querySelector(".collection-toggle").click()');await until(()=>js(q,'!document.querySelector(".library-group").classList.contains("collapsed")'),'expand collection');await drag('.library-tracks',0,1);await until(async()=>!!(await js(q,'player.library("asmr")')).orders['["asmr","set"]'],'inner order');await js(q,'document.querySelector(".library-tracks").lastElementChild.dispatchEvent(new KeyboardEvent("keydown",{bubbles:true,cancelable:true,altKey:true,key:"ArrowDown"}))');check('nested keyboard boundary does not move collection',await js(q,'document.querySelector(".player-library").lastElementChild.classList.contains("library-group")'));check('nested track drag leaves collection grouping intact',await js(q,'document.querySelectorAll(".player-library>.library-group").length===1&&document.querySelector(".library-tracks").firstElementChild.dataset.track==="set2"'));
 for(const view of ['radio','other']){await tab(view);await until(()=>js(q,'!!document.querySelector(".library-tracks")'),'track group');await js(q,'document.querySelector(".collection-toggle").click()');await until(()=>js(q,'!document.querySelector(".library-group").classList.contains("collapsed")'),'expand '+view);await drag('.library-tracks',0,1);await until(async()=>!!(await js(q,'player.library('+JSON.stringify(view)+')')).orders[JSON.stringify([view,view])],'order '+view);}check('radio and other reuse same reorder implementation',true);
 await tab('queue');await js(q,'player.resource([{itemId:"a",trackId:"a1"}],"append")');await js(q,'document.querySelector("[data-view=queue]").dispatchEvent(new MouseEvent("contextmenu",{bubbles:true,cancelable:true}));[...document.querySelectorAll(".queue-options button")].find(b=>b.textContent==="清理重复项").click()');await until(()=>js(q,'!!document.querySelector(".queue-clean-confirm")'),'confirmation');fs.writeFileSync(path.join(out,'cleanup-confirmation.png'),(await q.webContents.capturePage()).toPNG());check('cleanup uses themed child dialog with exact count and focus',await js(q,'document.querySelector(".queue-clean-confirm").textContent.includes("1 项")&&document.querySelector(".queue-clean-confirm").contains(document.activeElement)&&document.querySelector(".queue-options").inert'));q.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});await until(()=>js(q,'!document.querySelector(".queue-clean-confirm")'),'cancel');check('Escape cancels only confirmation and retains duplicates',service.snapshot().queue.length===2&&await js(q,'!!document.querySelector(".queue-options")&&!document.querySelector(".queue-options").inert'));
 await js(q,'[...document.querySelectorAll(".queue-options button")].find(b=>b.textContent==="清理重复项").click()');await until(()=>js(q,'!!document.querySelector(".queue-clean-confirm")'),'confirm again');await js(q,'[...document.querySelectorAll(".queue-clean-confirm button")].find(b=>b.textContent==="确认清理").click()');await until(()=>service.snapshot().queue.length===1,'cleanup');check('confirmed cleanup preserves playback',service.snapshot().currentId!==null);await js(q,'document.querySelector(".queue-options .app-dialog-close").click()');const plan=await js(q,'player.action("queueCleanPreview","clear")');await js(q,'player.resource([{itemId:"a",trackId:"a1"}],"append")');const stale=await js(q,'player.action("queueClean",'+JSON.stringify(plan.token)+').then(()=>"bad",e=>e.message)');check('stale cleanup token refuses changed queue',stale.includes('队列已变化'));
 for(const k of ['main','lyrics','queue','eq']){const w=win(k);w.show();w.focus();const pt=await js(w,'(()=>{const r=document.querySelector("[aria-label=关闭]").getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()');w.webContents.sendInputEvent({type:'mouseMove',...pt});check(k+' close hover does not grow document',await js(w,'document.documentElement.scrollWidth===innerWidth&&document.documentElement.scrollHeight===innerHeight&&getComputedStyle(document.querySelector("[aria-label=关闭]")).transform==="none"'));}
 peer=new BrowserWindow({x:90,y:90,width:500,height:400,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false}});await peer.loadURL('data:text/html,unrelated test window');peer.show();peer.focus();main.focus();await until(()=>main.isFocused(),'main focus');const members=['main','lyrics','queue','eq'].map(k=>handle(win(k))),peerId=handle(peer);const z=JSON.parse(cp.execFileSync(path.resolve('tests/WindowProbe.exe'),[handle(main),'stack',[...members,peerId].join(',')],{windowsHide:true,encoding:'utf8'})).order.map(String);check('main activation raises all visible auxiliaries above unrelated window',members.every(h=>z.indexOf(h)<z.indexOf(peerId)));check('auxiliary ownership never uses always-on-top', ['lyrics','queue','eq'].every(k=>win(k).getParentWindow()===main&&!win(k).isAlwaysOnTop()));peer.destroy();peer=null;
 main.minimize();await until(()=>!win('queue').isVisible(),'aux hidden');main.restore();main.focus();await until(()=>win('queue').isVisible(),'aux restored');check('owned auxiliaries still follow minimize and restore',true);
 check('library remains byte-for-byte unchanged',JSON.stringify(lib)===before);check('no renderer errors',errors.length===0);await service.close();await service.show();const restored=await js(win('main'),'player.library("songs")');check('manual display order survives player reopening',restored.orders['["songs",null]'][0]!==original[0]);await finish();
 }catch(e){await finish(e)}});
