const {test}=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),{fromText}=require('../app/player/dist/lyrics'),{prepareAppend}=require('../app/player/dist/session'),Request=require('../app/player-resource-request'),Library=require('../app/player-library');
const item=(id,kind)=>({id,type:'audio',name:id,audio:{kind,collectionKind:'album',tracks:[{id:id+'1',title:id}],sources:[]}}),lib={items:[item('a','music'),item('b','music'),item('single'),item('old','asmr'),{id:'video',type:'movie'}],playlists:[{id:'p',entries:['a','b','single','old'].map(id=>({itemId:id,trackId:id+'1'}))}],referenceRedirects:[{from:{itemId:'deleted',trackId:'old'},to:{itemId:'b',trackId:'b1'}}]},refs=lib.playlists[0].entries;
test('cross-album and legacy single music references share canonical music context',()=>{const before=JSON.stringify(lib);assert.equal(Request.resolve(lib,refs.slice(0,3)).context,'music');assert.equal(Library.browse(lib,'songs').length,3);assert.equal(JSON.stringify(lib),before);});
test('validated playlist retains reclassified members and stable redirects without weakening ordinary partition guard',()=>{assert.equal(Request.resolve(lib,refs,{kind:'playlist',id:'p'}).context,'music');assert.deepEqual(Request.resolve(lib,[{itemId:'deleted',trackId:'old'}],{kind:'playlist',id:'p'}).refs,[refs[1]]);assert.throws(()=>Request.resolve(lib,refs),/同一分区/);assert.throws(()=>Request.resolve(lib,refs,{kind:'playlist',id:'missing'}),/不存在/);assert.throws(()=>Request.resolve(lib,[{itemId:'video'}],{kind:'playlist',id:'p'}),/不属于/);assert.throws(()=>Request.resolve(lib,[{itemId:'b',trackId:'not-member'}],{kind:'playlist',id:'p'}),/不属于/);});
test('saved and active queues use identical duplicate, path and size validation without input mutation',()=>{const e={path:path.resolve('fixture.wav'),title:'One',resourceId:'a',memberId:'a1'},queue=[{...e,queueEntryId:'old'}];assert.deepEqual(prepareAppend(queue,[e,e],false),[]);const added=prepareAppend([], [e,e],true);assert.equal(added.length,2);assert.notEqual(added[0].queueEntryId,added[1].queueEntryId);assert.equal(queue.length,1);assert.throws(()=>prepareAppend([], [{...e,path:'relative.wav'}],true),/授权/);assert.throws(()=>prepareAppend(Array(10000).fill(queue[0]),[e],true),/过长/);});
test('same-time bilingual LRC forms one group, deduplicates repeated text and respects global offset',()=>{assert.deepEqual(fromText('[offset:100]\n[00:01]Original\n[00:01.000]译文\n[00:01]译文\n[00:02]Next',50).lines,[{time:1.15,text:'Original',translation:'译文'},{time:2.15,text:'Next'}]);});
test('separate translation aligns timestamps, supports repeated tags and does not invent alignment',()=>{assert.deepEqual(fromText('[00:01][00:03]Original\n[00:02]Second',0,'[00:01][00:03]译文\n[00:02]第二行\n[00:09]Unmatched').lines,[{time:1,text:'Original',translation:'译文'},{time:2,text:'Second',translation:'第二行'},{time:3,text:'Original',translation:'译文'}]);assert.equal(fromText('[00:01]Original',0,'untimed').lines[0].translation,undefined);assert.equal(fromText('Original',0,'译文').message,'Original\n\n译文');assert.equal(fromText('').status,'empty');});
test('provider translations survive public QQ and NetEase responses',async()=>{const {create}=require('../app/audio-lyrics-providers'),track={title:'Song',artists:['Artist'],durationSeconds:100},item={audio:{kind:'music',artists:['Artist']}};for(const provider of ['qq','netease']){const query=create({music:{},json:async u=>u.includes('client_search')?{data:{song:{list:[{songmid:'m',songname:'Song',singer:[{name:'Artist'}],interval:100}]}}}:u.includes('search/get')?{code:200,result:{songs:[{id:1,name:'Song',artists:[{name:'Artist'}],duration:100000}]}}:provider==='qq'?{req_0:{code:0,data:{lyric:Buffer.from('[00:01]Original').toString('base64'),trans:Buffer.from('[00:01]译文').toString('base64')}}}:{lrc:{lyric:'[00:01]Original'},tlyric:{lyric:'[00:01]译文'}}});const result=await query(item,track,new AbortController().signal,provider);assert.equal(result.translation,'[00:01]译文');assert.equal(fromText(result.text,0,result.translation).lines[0].translation,'译文');}});

test('invalid translated provider payload remains a parse error',async()=>{const {create}=require('../app/audio-lyrics-providers'),query=create({music:{},json:async u=>u.includes('search/get')?{code:200,result:{songs:[{id:1,name:'Song',artists:[{name:'Artist'}],duration:100000}]}}:{lrc:{lyric:'[00:01]Original'},tlyric:{lyric:{invalid:true}}}});await assert.rejects(query({audio:{kind:'music',artists:['Artist']}},{title:'Song',artists:['Artist'],durationSeconds:100},undefined,'netease'),/解析错误/);});
