// Launches ONLY the independently built trial package. Uses no formal user data.
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),assert=require('node:assert/strict');
const built=path.resolve(__dirname,'../release/Unified Manager 改版试用'),root=process.env.UM_TRIAL_PACKAGE_DIR?path.resolve(process.env.UM_TRIAL_PACKAGE_DIR):fs.existsSync(built)?built:path.resolve(__dirname,'../../..'),artifact=path.resolve(__dirname,'../test-artifacts'),report={started:new Date().toISOString(),package:root,checks:[]};fs.mkdirSync(artifact,{recursive:true});
const pause=ms=>new Promise(r=>setTimeout(r,ms)),record=(name,value)=>{assert.ok(value,name);report.checks.push(name);};let ws,seq=0,pending=new Map();
const port=19391;
async function connect(){for(let i=0;i<150;i++){try{const rows=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json(),page=rows.find(v=>v.url.endsWith('/index.html'));if(page){assert.ok(decodeURIComponent(page.url).startsWith('file:///'+root.replace(/\\/g,'/')),'不能连接其他应用');ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});ws.onmessage=e=>{const v=JSON.parse(e.data),p=pending.get(v.id);if(p){pending.delete(v.id);v.error?p.reject(Error(v.error.message)):p.resolve(v.result);}};return;}}catch(e){if(/其他应用/.test(e.message))throw e;}await pause(150);}throw Error('独立试用包启动超时');}
async function js(expression){const id=++seq,r=await new Promise((resolve,reject)=>{pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method:'Runtime.evaluate',params:{expression,awaitPromise:true,returnByValue:true}}));setTimeout(()=>{if(pending.has(id)){pending.delete(id);reject(Error('执行超时'));}},20000).unref();});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
async function until(fn){for(let i=0;i<100;i++){if(await fn())return;await pause(100);}throw Error('界面条件未达到');}
async function launch(){cp.spawn(path.join(root,'Unified Manager.exe'),[],{cwd:root,windowsHide:true,stdio:'ignore',env:{...process.env,UM_DEBUG_PORT:String(port)}}).unref();await connect();await until(()=>js("document.readyState==='complete'&&!!window.audioPlayer&&Array.isArray(state.items)"));}
async function close(){await js('native.close();true').catch(()=>{});ws?.close();for(let i=0;i<100;i++){try{await fetch('http://127.0.0.1:'+port+'/json/list');}catch{return;}await pause(100);}throw Error('试用窗口未正常退出');}
(async()=>{try{assert.ok(!fs.existsSync(path.join(root,'user-data/library.json')),'只允许首次测试干净独立包');const audio=path.join(artifact,'便携播放测试.wav');cp.execFileSync(path.join(root,'程序/resources/app/codec/bin/ffmpeg.exe'),['-v','error','-f','lavfi','-i','sine=frequency=220:duration=6','-ac','2','-y',audio],{windowsHide:true});await launch();record('根目录启动器加载独立包实际页面并显示试用标记',await js("document.body.textContent.includes('改版试用 · 独立数据')"));record('首次启动空库且声音位于书籍下方',await js("state.items.length===0&&document.querySelector('[data-view=book]').nextElementSibling.dataset.view==='audio'"));await js(`(async()=>{const preview=await native.audioScanDropped([${JSON.stringify(audio)}],'music');state=(await native.audioImport(preview.items.map(i=>i.id))).library;state.items[0].review='重启保留的评价';state=await native.saveLibrary(LibraryRelations.playlist(state,'create',{name:'重启测试歌单'}));state=await native.saveLibrary(LibraryRelations.playlist(state,'add',{id:state.playlists[0].id,entries:[{itemId:state.items[0].id,trackId:state.items[0].audio.tracks[0].id}]}));activeView='audio';render();audioPlayer.media.muted=true;await audioPlayer.playItem(state.items[0]);})()`);await until(()=>js('audioPlayer.media.currentTime>.5'));record('独立包真实本地扫描、保存、静音解码推进',await js('audioPlayer.media.duration>5&&!audioPlayer.media.paused'));await js("(async()=>{audioPlayer.pause();await native.audioSessionSave(audioPlayer.getSession());localStorage.setItem('librarySort:audio:all',JSON.stringify({field:'name',direction:'desc'}));})()");const before=JSON.parse(fs.readFileSync(path.join(root,'user-data/library.json')));record('独立数据目录记录真实资源和歌单',before.items.length===1&&before.playlists[0].entries.length===1);await close();await launch();await until(()=>js('audioPlayer.getSession().queue.length===1'));record('重启保留条目评价歌单与来源，默认不出声',await js("state.items.length===1&&state.items[0].review==='重启保留的评价'&&state.playlists[0].entries.length===1&&audioPlayer.media.paused"));record('重启保留队列位置及排序偏好',await js("audioPlayer.getSession().position>0&&JSON.parse(localStorage.getItem('librarySort:audio:all')).direction==='desc'"));await close();report.ok=true;}catch(e){report.ok=false;report.error=e.stack;ws?.close();}finally{report.finished=new Date().toISOString();fs.writeFileSync(path.join(artifact,'portable-smoke-result.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));process.exitCode=report.ok?0:1;}})();
