const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),Model=require('../app/usage-model'),Tracker=require('../app/usage-tracker');
function fixture(){let time=0;const rows={},opens=[],t=Tracker.create({now:()=>time,opened:id=>opens.push(id),record:async(id,d)=>{rows[id]||={seconds:0,windowSeconds:0,playbackSeconds:0};for(const k of ['seconds','windowSeconds','playbackSeconds'])rows[id][k]+=d[k];}});return {rows,opens,t,step:(ms,s)=>{time+=ms;t.sample(s)}};}
test('media windows allocate time per resource and overlap playback only once',async()=>{const f=fixture(),a={id:'movie',generation:1,active:true,playing:true,position:0};f.t.sample(a);f.step(2000,{...a,position:2});f.step(0,{...a,id:'audio',generation:2,active:false,position:0});f.step(3000,{...a,id:'audio',generation:2,active:false,position:3});await f.t.stop();assert.deepEqual(f.rows.movie,{seconds:2,windowSeconds:2,playbackSeconds:2});assert.deepEqual(f.rows.audio,{seconds:3,windowSeconds:0,playbackSeconds:3});assert.deepEqual(f.opens,['movie','audio']);});
test('paused, stalled, hidden, seeks and suspend cannot inflate playback',async()=>{const f=fixture(),s={id:'audio',generation:1,active:false,playing:true,position:0};f.t.sample(s);f.step(1000,s);assert.deepEqual(f.rows,{});f.step(1000,{...s,position:900});f.step(0,{...s,position:900,playing:false,active:true});f.step(1000,{...s,position:900,playing:false,active:true});f.step(0,{...s,position:900,playing:false,active:false});f.step(4000,{...s,position:900,playing:false,active:false});f.step(60000,{...s,position:960});await f.t.stop();assert.deepEqual(f.rows.audio,{seconds:2,windowSeconds:1,playbackSeconds:1});});
test('reader switching and close settle partial intervals without crossing resource IDs',async()=>{const f=fixture();f.t.sample({id:'bookA',active:true});f.step(1250,{id:'bookB',active:true});f.step(500,{id:'bookB',active:false});f.step(1000,{id:'bookB',active:false});await f.t.stop();assert.equal(f.rows.bookA.seconds,1.25);assert.equal(f.rows.bookB.seconds,.5);assert.equal(f.rows.bookB.playbackSeconds,0);});
test('automatic reading fields preserve manual zero and legacy values, use 0.1h precision',()=>{const records={b:{seconds:4500}};for(const v of [{playtime:0},{playtime:1},{playtime:null,playtimeSource:'手动'}]){const item={id:'b',type:'book',...v};assert.equal(Model.fill(item,records),item);}const auto=Model.fill({id:'b',type:'book',playtime:null},records);assert.equal(auto.playtime,1.3);assert.equal(auto.playtimeSource,'本机记录');assert.equal(Model.fill(auto,{b:{seconds:7200}}).playtime,2);assert.equal(Model.hours({id:'b',playtime:2},records),2);assert.equal(Model.fill({id:'b',type:'game'},records).playtime,undefined);});
test('six categories and independent recent/top-five ordering do not mutate library order',()=>{const items=Array.from({length:7},(_,i)=>({id:'b'+i,type:'book',playtime:7-i,name:'书'+i})),records=Object.fromEntries(items.map((v,i)=>[v.id,{openedAt:new Date(1000*i+1000).toISOString()}])),before=JSON.stringify(items),r=Model.rankings(items,records,'book');assert.deepEqual(r.recent.map(x=>x.item.id),['b6','b5','b4','b3','b2']);assert.deepEqual(r.longest.map(x=>x.item.id),['b0','b1','b2','b3','b4']);assert.equal(JSON.stringify(items),before);assert.deepEqual(Model.groups(items,records).map(x=>x.type),['game','movie','anime','manga','book','audio']);});
test('usage persists across service restart and library projection never rewrites hand-entered values',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'yueden-241-')),handlers={},items=[{id:'b',type:'book',playtime:null},{id:'manual',type:'manga',playtime:0}],create=()=>require('../app/usage-service').install({ipcMain:{handle:(k,f)=>handlers[k]=f},dataRoot:()=>root,loadLibrary:()=>({items}),now:()=>clock});let clock=0,read={id:'b',active:true};const svc=create(),t=svc.timeline(()=>read);t.sample();clock=1000;await t.flush();read={id:'manual',active:true};t.sample();clock=2000;await t.close();assert.equal((await handlers['usage:snapshot']()).b.seconds,1);const restart=create(),next=restart.decorate({items});assert.equal(next.items[0].playtimeSource,'本机记录');assert.equal(next.items[1].playtime,0);assert.equal(items[0].playtime,null);fs.writeFileSync(path.join(root,'usage-records.json'),'{broken');assert.throws(()=>restart.decorate({items}),/损坏/);});
test('failed duration flush retains pending increments for a later explicit attempt',async()=>{let clock=0,fail=true,result=0;const t=Tracker.create({now:()=>clock,record:async(_id,d)=>{if(fail)throw Error('disk failure');result+=d.seconds;}});t.sample({id:'a',active:true});clock=1000;t.sample(null);await assert.rejects(t.flush(),/disk failure/);fail=false;await t.flush();assert.equal(result,1);await t.flush();assert.equal(result,1);});

test("recent usage prefers resumed reading activity over the original open date",()=>{const rows=Model.rankings([{id:"a",type:"book"},{id:"b",type:"book"}],{a:{openedAt:"2026-09-01",lastUsedAt:"2026-09-03"},b:{openedAt:"2026-09-02"}},"book");assert.equal(rows.recent[0].item.id,"a");assert.equal(Model.hours({id:"a",playtime:1.3,playtimeSource:"本机记录"},{a:{seconds:4500}}),1.25);});
