// Actual packaged executable, local CDP only, generated media and disposable package data.
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),assert=require('node:assert/strict'),net=require('node:net');
const pkg=path.resolve(process.argv[2]||''),base=path.resolve(__dirname,'../test-artifacts/finish'),data=path.join(pkg,'user-data');
if(!pkg.includes('redesign\\release\\Unified Manager Player ')||fs.existsSync(data))throw Error('Requires clean independent candidate package');
const fixture=path.resolve(__dirname,'../test-artifacts'),video=path.join(fixture,'generated video.mkv'),audio=path.join(fixture,'generated audio.wav');
fs.mkdirSync(data);fs.writeFileSync(path.join(data,'library.json'),JSON.stringify({schemaVersion:4,items:[{id:'m',type:'movie',name:'测试影视',localPath:video,localFiles:[{path:video,name:'第一集'}]},{id:'a',type:'anime',name:'测试番剧',localPath:video,localFiles:[{path:video,name:'第一集'}]},{id:'s',type:'audio',name:'测试声音',audio:{kind:'music',collectionKind:'album',tracks:[{id:'t',title:'测试轨',sourceRefs:['p']}],sources:[{id:'p',kind:'local',localPath:audio}]}}],categories:[]}));
const checks=[],delay=ms=>new Promise(r=>setTimeout(r,ms));let child,ws,port,closed=false;const requests=new Map();let seq=0;
async function until(fn){for(let i=0;i<120;i++){try{const v=await fn();if(v)return v}catch{}await delay(100)}throw Error('Package wait timed out')}
async function rpc(method,params={}){const id=++seq;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{requests.delete(id);reject(Error('CDP timeout '+method))},10000);requests.set(id,{resolve:v=>{clearTimeout(timer);resolve(v)},reject:e=>{clearTimeout(timer);reject(e)}});ws.send(JSON.stringify({id,method,params}))})}
async function js(expression){const r=await rpc('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result?.value}
const snapshot=()=>js('unifiedAPI.playerSnapshot()');
function processes(){const command="Get-Process | Where-Object { $_.ProcessName -in @('mpv','VideoHost') } | Select-Object Id,Path | ConvertTo-Json -Compress";let value=cp.execFileSync(path.join(process.env.SystemRoot,'System32/WindowsPowerShell/v1.0/powershell.exe'),['-NoProfile','-Command',command],{encoding:'utf8',windowsHide:true}).trim();return value?[JSON.parse(value)].flat().filter(p=>p.Path?.startsWith(pkg)):[]}
(async()=>{const server=net.createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));port=server.address().port;await new Promise(r=>server.close(r));const env={...process.env,PATH:path.join(process.env.SystemRoot,'System32')+';'+process.env.SystemRoot};delete env.ELECTRON_RUN_AS_NODE;child=cp.spawn(path.join(pkg,'程序/Unified Manager.exe'),['--remote-debugging-address=127.0.0.1','--remote-debugging-port='+port],{cwd:pkg,env,windowsHide:true,stdio:'ignore'});child.on('exit',()=>closed=true);
 const page=await until(async()=>{const pages=await(await fetch('http://127.0.0.1:'+port+'/json')).json();return pages.find(p=>p.url.endsWith('/index.html'))});ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.addEventListener('open',r,{once:true});ws.addEventListener('error',j,{once:true})});ws.addEventListener('message',e=>{const r=JSON.parse(e.data),p=requests.get(r.id);if(p){requests.delete(r.id);r.error?p.reject(Error(r.error.message)):p.resolve(r.result)}});
 await until(()=>js('Boolean(window.audioPlayer&&window.unifiedAPI)'));assert.equal(await js('document.querySelectorAll("audio,video").length'),0);checks.push('净化PATH下，实际候选exe正常启动，无主页面音视频引擎');
 const shot=await rpc('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(base,'package-resource-ui.png'),Buffer.from(shot.data,'base64'));
 await js('unifiedAPI.launchReader("m")');await until(async()=>{const s=await snapshot();return s.status==='playing'&&s.hasVideo&&s.position>0});const first=processes(),pid=first.find(p=>p.Path.endsWith('mpv.exe'))?.Id;assert.ok(pid);checks.push('真实影视文件：mpv解码、视频参数及进度前进');
 await js('unifiedAPI.launchReader("a")');await until(async()=>{const s=await snapshot();return s.status==='playing'&&s.hasVideo&&s.position>0});assert.equal(processes().find(p=>p.Path.endsWith('mpv.exe')).Id,pid);checks.push('番剧原入口复用同一mpv');
 await js('audioPlayer.command("play",[{itemId:"s",trackId:"t"}])');await until(async()=>{const s=await snapshot();return s.status==='playing'&&!s.hasVideo&&s.position>0});assert.equal(processes().filter(p=>p.Path.endsWith('mpv.exe')).length,1);assert.equal(processes().find(p=>p.Path.endsWith('mpv.exe')).Id,pid);checks.push('声音原入口复用同一mpv；视频切音频无第二引擎');
 await js('unifiedAPI.playerCommand({type:"pause",paused:true})');await until(async()=> (await snapshot()).status==='paused');await js('unifiedAPI.playerCommand({type:"seek",seconds:2})');await until(async()=>Math.abs((await snapshot()).position-2)<.2);await js('unifiedAPI.playerCommand({type:"pause",paused:false})');checks.push('真实暂停、绝对定位、继续');
 for(const k of ['lyrics','queue','eq']){await js(`unifiedAPI.playerAction('aux','${k}')`);assert.equal((await snapshot()).visible[k],true);await js(`unifiedAPI.playerAction('aux','${k}')`);assert.equal((await snapshot()).visible[k],false)}checks.push('三个辅助窗入口切换与主进程显隐状态一致');
 await js('unifiedAPI.playerCommand({type:"stop"})');const stopped=await snapshot();assert.equal(stopped.position,0);assert.ok(stopped.currentId);checks.push('停止归零但保留当前队列项');
 await js('unifiedAPI.launchReader("m")');await until(async()=> (await snapshot()).hasVideo);checks.push('音频切回视频成功');
 await js('unifiedAPI.close()').catch(()=>{});await until(()=>closed);await delay(1000);assert.deepEqual(processes(),[]);checks.push('资源主窗口正常退出后无mpv或VideoHost残留');
 fs.writeFileSync(path.join(base,'package-result.json'),JSON.stringify({time:new Date().toISOString(),pkg,checks,error:null,manualListening:false,systemAudioCapture:false},null,2));ws.close();console.log(checks.join('\n'));
})().catch(async error=>{fs.writeFileSync(path.join(base,'package-result.json'),JSON.stringify({time:new Date().toISOString(),pkg,checks,error:error.stack},null,2));console.error(error);try{await js('unifiedAPI.close()')}catch{}ws?.close();process.exitCode=1});
