// Video-only actual package/development diagnostics. All data is isolated.
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),net=require('node:net');
const mode=process.argv[2]||'old',player=path.resolve(__dirname,'..'),base=path.join(player,'test-artifacts/video'),out=path.join(base,mode+'-'+Date.now());fs.mkdirSync(out,{recursive:true});
const source=process.argv[3]||path.resolve(player,'../../release/Unified Manager Player 2.25.29-preview.1');
const video=JSON.parse(fs.readFileSync(path.join(player,'test-artifacts/formats/manifest.json'))).find(f=>f.name==='mp4-h264')?.file||path.join(player,'test-artifacts/formats/中文 h264.mp4');
const fixture=process.env.UM_VIDEO_FILE||JSON.parse(fs.readFileSync(path.join(player,'test-artifacts/formats/manifest.json'))).find(f=>f.video&&f.streams.some(s=>s.codec==='h264')).file;
let executable,appDir,args,data;
if(mode==='dev'){
 executable=path.resolve(player,'../../../runtime-44/extracted/electron.exe');appDir=path.dirname(player);data=path.join(out,'user-data');
 // Entry code below is this same file under Electron, no generated executable script.
 args=[__filename,'entry',out];
}else if(mode==='entry'){
 const {app}=require('electron');const isolated=process.argv[3],set=app.setPath.bind(app);app.setPath=(k,v)=>set(k,k==='userData'?path.join(isolated,'user-data'):v);set('userData',path.join(isolated,'user-data'));require(path.resolve(__dirname,'../../main.js'));return;
}else{
 const copy=process.env.UM_VIDEO_ATTACH_PORT?source:path.join(out,'candidate');if(!process.env.UM_VIDEO_ATTACH_PORT){fs.mkdirSync(copy);fs.cpSync(path.join(source,'程序'),path.join(copy,'程序'),{recursive:true});fs.copyFileSync(path.join(source,'Unified Manager.exe'),path.join(copy,'Unified Manager.exe'));}else if(!copy.includes('test-artifacts'))throw Error('Attach only to this task isolated copy');
 executable=path.join(copy,'Unified Manager.exe');appDir=path.join(copy,'程序/resources/app');data=path.join(copy,'user-data');args=[];
}
fs.mkdirSync(data,{recursive:true});fs.writeFileSync(path.join(data,'library.json'),JSON.stringify({schemaVersion:4,items:[{id:'video',type:'movie',name:'H.264 画面验证',localPath:fixture,localFiles:[{path:fixture,name:'H.264 画面验证'}]}],categories:[]}));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let ws,child,client,resourceUrl;let seq=0;const requests=new Map();
async function until(fn){for(let n=0;n<150;n++){try{const v=await fn();if(v)return v}catch{}await sleep(100)}throw Error('诊断等待超时')}
async function attach(url){const socket=new WebSocket(url);await new Promise((r,j)=>{socket.addEventListener('open',r,{once:true});socket.addEventListener('error',j,{once:true})});socket.addEventListener('message',e=>{const value=JSON.parse(e.data),p=requests.get(value.id);if(p){requests.delete(value.id);value.error?p.reject(Error(value.error.message)):p.resolve(value.result)}});return socket}
function rpc(method,params={}){const id=++seq;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{requests.delete(id);reject(Error('CDP timeout'))},12000);requests.set(id,{resolve:r=>{clearTimeout(timer);resolve(r)},reject:e=>{clearTimeout(timer);reject(e)}});ws.send(JSON.stringify({id,method,params}))})}
async function js(expression){const r=await rpc('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value}
(async()=>{
 const server=net.createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=Number(process.env.UM_VIDEO_ATTACH_PORT)||server.address().port;await new Promise(r=>server.close(r));const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;env.UM_DEBUG_PORT=String(port);if(mode!=='dev')env.PATH=path.join(process.env.SystemRoot,'System32')+';'+process.env.SystemRoot;
 if(!process.env.UM_VIDEO_ATTACH_PORT)child=cp.spawn(executable,[...args,'--remote-debugging-address=127.0.0.1','--remote-debugging-port='+port,'--enable-logging=file','--log-file='+path.join(out,'electron.log')],{cwd:out,env,windowsHide:true,stdio:'ignore'});
 let pages=()=>fetch('http://127.0.0.1:'+port+'/json').then(r=>r.json());const page=await until(async()=> (await pages()).find(p=>p.url.endsWith('/index.html')));resourceUrl=page.webSocketDebuggerUrl;ws=await attach(resourceUrl);await until(()=>js('Boolean(window.unifiedAPI)'));await js('unifiedAPI.launchReader("video")');await until(async()=>{const s=await js('unifiedAPI.playerSnapshot()');return s.hasVideo&&s.position>0});await js('unifiedAPI.playerCommand({type:"pause",paused:true})');
 const processes=JSON.parse(cp.execFileSync(path.join(process.env.SystemRoot,'System32/WindowsPowerShell/v1.0/powershell.exe'),['-NoProfile','-Command',"[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new();Get-CimInstance Win32_Process -Filter \"Name = 'mpv.exe' OR Name = 'VideoHost.exe'\" | Select-Object ProcessId,ParentProcessId,ExecutablePath,CommandLine | ConvertTo-Json -Compress"],{encoding:'utf8',windowsHide:true}));const rows=[processes].flat(),mpv=rows.find(p=>p.ExecutablePath?.toLowerCase()===path.join(appDir,'player/vendor/mpv.exe').toLowerCase());if(!mpv)throw Error('Cannot locate exact candidate mpv');
 const pipe=mpv.CommandLine.match(/--input-ipc-server=([^"\s]+)/)[1];client=await require(path.join(player,'dist/mpv-client')).MpvClient.connect(pipe);const log=[];client.onEvent(e=>{if(e.event==='log-message')log.push(e)});await client.request(['request_log_messages','v']);if(process.env.UM_VIDEO_RELOAD==='1')await js('(async()=>{const s=await unifiedAPI.playerSnapshot();return unifiedAPI.playerCommand({type:"play",id:s.currentId})})()');await sleep(500);await js('unifiedAPI.playerCommand({type:"pause",paused:true})');await sleep(250);
 const properties={};for(const p of ['video-format','video-codec','vid','video-params','video-out-params','current-vo','vo-configured','estimated-frame-number','time-pos','wid','display-width','display-height']){try{properties[p]=await client.request(['get_property',p])}catch(e){properties[p]={error:e.message}}}
 if(process.env.UM_VIDEO_FRAME==='1')await client.request(['screenshot-to-file',path.join(out,'decoded-frame.png'),'video']).catch(e=>properties.screenshotError=e.message);
 const hwnd=String(properties.wid),native=JSON.parse(cp.execFileSync(path.join(__dirname,'VideoInspect.exe'),[hwnd],{encoding:'utf8',windowsHide:true}));
 ws.close();const videoPage=(await pages()).find(p=>p.url.includes('/player/window.html')&&p.url.includes('kind=main'));ws=await attach(videoPage.webSocketDebuggerUrl);
 const dom=await js('({video:document.querySelector("#video").getBoundingClientRect().toJSON(),window:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},state:await window.player.snapshot()})'.replace('state:await','state:await')).catch(async()=>js('(async()=>({video:document.querySelector("#video").getBoundingClientRect().toJSON(),window:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},state:await window.player.snapshot()}))()'));
 fs.writeFileSync(path.join(out,'diagnostics.json'),JSON.stringify({mode,executable,appDir,fixture,processes:rows,properties,native,dom},null,2));fs.writeFileSync(path.join(out,'mpv-log.json'),JSON.stringify(log,null,2));
 fs.writeFileSync(path.join(base,'active.json'),JSON.stringify({out,port,hwnd,root:native.root,videoPage:videoPage.webSocketDebuggerUrl,resourcePage:page.webSocketDebuggerUrl,mode,appDir},null,2));console.log(out);console.log(JSON.stringify({properties,native,video:dom.video}));
 await sleep(240000);await js('window.close()').catch(()=>{});ws.close();ws=await attach(page.webSocketDebuggerUrl);await js('unifiedAPI.close()').catch(()=>{});client.close();ws.close();
})().catch(async error=>{console.error(error);fs.writeFileSync(path.join(out,'error.txt'),error.stack);client?.close();ws?.close();if(resourceUrl)try{ws=await attach(resourceUrl);await js('unifiedAPI.close()');ws.close()}catch{}process.exitCode=1});
