/* One persistent HTMLAudioElement, outside all render-replaced library nodes. */
(()=>{
 const media=document.createElement('audio');media.preload='metadata';document.body.append(media);
 let externalPaused=false;let hls=null,resolved={},compatibilityTried=false;let restoring=true,queuePage=0,lyrics={kind:'none',lines:[],text:''};
 let session={queue:[],index:0,position:0,volume:1,repeat:'none',shuffle:false,bookmarks:[],progress:[],muted:false},revision=0,saveTimer=0,sleepTimer=0,sleepDeadline=0,sleepAtEnd=false,restoreAt=0,loadedTrack='',full=null;
 const mini=document.createElement('section');mini.id='audioMini';mini.className='hidden';mini.innerHTML='<button data-audio="full" class="audio-now"><img class="audio-mini-cover" alt=""><span class="audio-mini-info"><strong class="audio-mini-title">声音</strong><small class="audio-mini-artist"></small></span></button><button data-audio="mode" title="播放模式"></button><button data-audio="previous" title="上一轨">◀</button><button data-audio="toggle" title="播放或暂停">▶</button><button data-audio="next" title="下一轨">▶|</button><input class="audio-seek" type="range" min="0" max="1" step="0.1" value="0" aria-label="音频进度"><span class="audio-time">0:00</span><button data-audio="mute" title="静音">♪</button><input class="audio-volume" type="range" min="0" max="1" step="0.01" value="1" aria-label="音量"><span class="audio-error" role="status"></span>';(document.querySelector('.window-shell')||document.body).append(mini);
 const parseLyrics=(v,offset=0)=>['instrumental','not-applicable'].includes(v.kind)?{kind:'plain',lines:[],text:v.kind==='instrumental'?'纯音乐':'此音轨不适用歌曲歌词'}:AudioLyrics.parse(v.text,(Number(v.offset)||0)+offset);
 const logicalTime=()=>Number(resolved.offset||0)+(Number.isFinite(media.currentTime)?media.currentTime:0),logicalDuration=()=>resolved.compatible?Number(resolved.duration)||0:Number.isFinite(media.duration)?media.duration:0;
 function seekTo(time){if(resolved.compatible)return load(!media.paused,time,true);if(media.seekable.length)media.currentTime=Math.max(media.seekable.start(0),Math.min(media.seekable.end(media.seekable.length-1),time));}
 const current=()=>session.queue[session.index],lookup=e=>{const ref=e?LibraryRelations.resolve(state,e):{},item=state.items.find(i=>i.id===ref.itemId);return {item,track:item?.audio?.tracks?.find(t=>t.id===ref.trackId)};};
 const clock=value=>{const n=Number.isFinite(value)?Math.max(0,Math.floor(value)):0;return Math.floor(n/60)+':'+String(n%60).padStart(2,'0');};
 function persist(){if(restoring)return Promise.resolve();clearTimeout(saveTimer);saveTimer=0;if(loadedTrack)session.position=logicalTime();if(loadedTrack&&media.readyState>0){session.progress=session.progress.filter(p=>p.trackId!==loadedTrack);session.progress.push({trackId:loadedTrack,position:session.position});}session=AudioContext.normalize(session);return native.audioSessionSave(session).catch(error=>{mini.querySelector('.audio-error').textContent=error.message;});}
 function draw(){publish();const {item,track}=lookup(current());mini.classList.toggle('hidden',!current()||settings.disguiseEnabled);const hasSession=!!current()&&!settings.disguiseEnabled;if(document.body.classList.contains('has-audio-session')!==hasSession)document.body.classList.toggle('has-audio-session',hasSession);mini.querySelector('.audio-mini-title').textContent=track?.title||'文件或条目已移除';mini.querySelector('.audio-mini-artist').textContent=(({music:'音乐',asmr:'音声',radio:'电台',other:'其他音频'})[item?.audio?.kind]||'声音')+' · '+((track?.artists?.length?track.artists:item?.audio?.artists?.length?item.audio.artists:item?.audio?.performers||[]).join(' / ')||'未标注创作者');const art=mini.querySelector('.audio-mini-cover'),cover=track?.cover||(item?coverFor(item,'portrait'):'');if(art.dataset.cover!==cover){art.dataset.cover=cover;art.src=cover||'assets/icon.svg';art.onerror=()=>{art.onerror=null;art.src='assets/icon.svg';};}PlaybackControls.mode(mini,session);if(full)PlaybackControls.mode(full,session);PlaybackControls.update(mini,{paused:media.paused,muted:media.muted,volume:media.volume});const seek=mini.querySelector('.audio-seek');seek.max=logicalDuration()>0?logicalDuration():1;seek.disabled=!resolved.compatible&&!media.seekable.length;seek.value=logicalTime();mini.querySelector('.audio-time').textContent=clock(logicalTime())+' / '+(logicalDuration()?clock(logicalDuration()):'直播 / 未知时长');if(full){const times=[...full.querySelectorAll('.audio-lyrics button')];let active=-1;times.forEach((b,i)=>{if(Number(b.dataset.time)<=logicalTime())active=i;});times.forEach((b,i)=>b.classList.toggle('selected',i===active));full.querySelector('.audio-full-title').textContent=item?.name||'声音';full.querySelector('.audio-track-title').textContent=track?.title||'暂无音轨';PlaybackControls.update(full,{paused:media.paused,muted:media.muted,volume:media.volume});const fullSeek=full.querySelector('.audio-full-seek');fullSeek.max=seek.max;fullSeek.value=seek.value;fullSeek.disabled=seek.disabled;full.querySelector('.audio-full-time').textContent=clock(logicalTime())+' / '+(logicalDuration()?clock(logicalDuration()):'直播 / 未知时长');}}
 async function load(autoplay,position=0,compatibility=false){const ticket=++revision,e=current();hls?.destroy();hls=null;media.pause();loadedTrack='';media.removeAttribute('src');media.load();mini.querySelector('.audio-error').textContent='';if(!e){draw();return;}const {track}=lookup(e);if(!track){draw();return;}try{const result=await native.audioResolve(LibraryRelations.resolve(state,e).itemId,LibraryRelations.resolve(state,e).trackId,{compatibility,start:position});if(ticket!==revision)return;resolved=result;compatibilityTried=compatibility;restoreAt=result.compatible?0:position;loadedTrack=e.trackId;if(result.hls){if(!window.Hls?.isSupported())throw Error('当前环境不支持音频 HLS');hls=new Hls({enableWorker:false,manifestLoadingMaxRetry:1,fragLoadingMaxRetry:2,levelLoadingMaxRetry:1});hls.on(Hls.Events.ERROR,(_,data)=>{if(data.fatal){hls?.destroy();hls=null;mini.querySelector('.audio-error').textContent='网络流中断、授权失效或分片超出已授权范围';}});hls.loadSource(result.url);hls.attachMedia(media);}else{media.src=result.url;media.load();}native.audioLyrics(LibraryRelations.resolve(state,e).itemId,LibraryRelations.resolve(state,e).trackId).then(value=>{if(ticket!==revision)return;lyrics=parseLyrics(value,Number(track.lyricsOffsetMs)||0);renderLyrics();}).catch(()=>{if(ticket===revision){lyrics={kind:'error',lines:[],text:'歌词读取失败'};renderLyrics();}});if(autoplay&&!externalPaused)await media.play();if(ticket!==revision)return;draw();await persist();}catch(error){if(ticket===revision){mini.querySelector('.audio-error').textContent=error.message;draw();}}}
 async function playItem(item){externalPaused=false;const previousEntry=current();await persist();if(!item.audio?.tracks?.length){showToast('这部作品还没有音轨，请通过“导入声音”导入音频','error');return;}session=AudioContext.switchTo(session,item.audio.kind);session.source={kind:item.audio.collectionKind,id:item.id};session.queue=AudioContext.order(item.audio.tracks).map(track=>({queueEntryId:crypto.randomUUID(),itemId:item.id,trackId:track.id}));session.index=item.audio.resumePolicy==='resume'&&true?Math.max(0,session.queue.findIndex(e=>e.trackId===(previousEntry?.itemId===item.id?previousEntry.trackId:[...session.progress].reverse().find(p=>session.queue.some(q=>q.trackId===p.trackId))?.trackId))):0;session.shuffleOrder=session.shuffle?AudioContext.shuffled(session):[];const resume=item.audio.resumePolicy==='resume'?session.progress.find(p=>p.trackId===session.queue[session.index].trackId)?.position||0:0;await load(true,resume);renderQueue();}
 function next(delta=1){if(!session.queue.length)return;session.index=AudioContext.nextIndex(session,delta);load(true);renderQueue();}
 function action(name){if(name==='mode'){if(session.activeContext==='asmr'){showToast('音声按章节顺序播放');return;}const mode=session.shuffle?3:session.repeat==='all'?1:session.repeat==='one'?2:0,next=(mode+1)%4;session.shuffle=next===3;session.repeat=next===1?'all':next===2?'one':'none';if(session.shuffle)session.shuffleOrder=AudioContext.shuffled(session);persist();draw();return;}if(name==='full')return openFull();if(name==='lyrics'&&current())return window.audioPanels.lyrics(current().itemId,current().trackId);if(['toggle','next','previous'].includes(name))externalPaused=false;if(name==='toggle'){if(!media.src)return load(true,session.position);media.paused?media.play().catch(e=>showToast(e.message,'error')):media.pause();}if(name==='next')next();if(name==='previous')next(-1);if(name==='back')seekTo(Math.max(0,logicalTime()-10));if(name==='forward')seekTo(logicalTime()+10);if(name==='mute'){session.muted=media.muted=!media.muted;persist();}if(name==='bookmark'&&current()){session.bookmarks.push({...current(),id:crypto.randomUUID(),note:'',position:logicalTime()});persist();renderQueue();}draw();}
 mini.addEventListener('click',e=>{const button=e.target.closest('[data-audio]');if(button)action(button.dataset.audio);});mini.querySelector('.audio-seek').oninput=e=>{seekTo(Number(e.target.value));};mini.querySelector('.audio-volume').oninput=e=>{session.volume=Number(e.target.value);media.volume=session.volume;persist();};
 native.onMediaPause?.(kind=>{if(kind==='audio'){externalPaused=true;++revision;media.pause();}});
 media.addEventListener('play',()=>{if(externalPaused){media.pause();return;}native.notifyMediaPlaying?.('audio');});
 media.addEventListener('loadedmetadata',()=>{if(restoreAt&&Number.isFinite(media.duration)&&restoreAt<media.duration)media.currentTime=restoreAt;restoreAt=0;draw();});
 for(const event of ['play','pause','volumechange','durationchange','progress','waiting','playing'])media.addEventListener(event,draw);
 media.addEventListener('timeupdate',()=>{draw();if(!saveTimer)saveTimer=setTimeout(()=>{saveTimer=0;persist();},5000);});
 media.addEventListener('play',()=>{const id=current()?.itemId;if(id)recordResourceOpen(id);});setInterval(()=>{const id=current()?.itemId;if(id&&!media.paused&&!media.ended&&media.readyState>=2)native.usageTick(id,5).catch(()=>{});},5000);
 media.addEventListener('pause',persist);media.addEventListener('error',()=>{if(!compatibilityTried&&!resolved.hls&&loadedTrack){compatibilityTried=true;load(true,logicalTime(),true);return;}mini.querySelector('.audio-error').textContent='音频无法播放：文件损坏、编码不支持或远程连接失败';draw();});
 media.addEventListener('ended',()=>{if(externalPaused)return;if(sleepAtEnd){sleepAtEnd=false;return;}if(session.repeat==='one'){load(true,0,resolved.compatible);}else if(AudioContext.sequence(session).indexOf(current()?.queueEntryId)<session.queue.length-1||session.repeat==='all')next();});
 function renderLyrics(){publish();if(!full)return;const host=full.querySelector('.audio-lyrics');host.replaceChildren();if(lyrics.kind!=='synced'){host.textContent=lyrics.kind==='none'?'没有本地歌词':lyrics.text;return;}for(const line of lyrics.lines){const b=document.createElement('button');b.textContent=line.text||'…';b.dataset.time=line.time;b.onclick=()=>{seekTo(line.time);};host.append(b);}}
 function renderQueue(){publish();if(!full)return;const list=full.querySelector('.audio-queue');list.replaceChildren();const totalPages=Math.max(1,Math.ceil(session.queue.length/100));queuePage=Math.min(queuePage,totalPages-1);full.querySelector('.audio-queue-page').textContent=(queuePage+1)+' / '+totalPages;session.queue.slice(queuePage*100,queuePage*100+100).forEach((entry,offset)=>{const index=queuePage*100+offset;const {track}=lookup(entry),row=document.createElement('div');row.className='audio-queue-row'+(index===session.index?' selected':'');const title=document.createElement('button');title.textContent=(index+1)+'. '+(track?.title||'音轨已移除');title.ondblclick=()=>{session.index=index;load(true);renderQueue();};row.append(title);for(const [label,fn]of [['＋',()=>{session.queue.push({...entry,queueEntryId:crypto.randomUUID()});}],['↑',()=>{if(index===0)return;const active=current()?.queueEntryId;[session.queue[index-1],session.queue[index]]=[session.queue[index],session.queue[index-1]];session.index=session.queue.findIndex(e=>e.queueEntryId===active);}],['×',()=>{const active=current()?.queueEntryId;session.queue.splice(index,1);const found=session.queue.findIndex(e=>e.queueEntryId===active);session.index=found<0?Math.min(index,Math.max(0,session.queue.length-1)):found;if(found<0)load(false);}]]){const b=document.createElement('button');b.textContent=label;b.title=label==='↑'?'上移音轨':label==='＋'?'再次加入队列':'从队列移除';b.onclick=()=>{fn();persist();renderQueue();};row.append(b);}list.append(row);});const marks=full.querySelector('.audio-bookmarks');marks.replaceChildren();for(const mark of session.bookmarks.filter(b=>b.trackId===current()?.trackId)){const button=document.createElement('button');button.textContent=clock(mark.position);button.onclick=()=>{seekTo(mark.position);};marks.append(button);}}

 function publish(){if(!native.audioPublish)return;const {item,track}=lookup(current());const pages=Math.max(1,Math.ceil(session.queue.length/100));queuePage=Math.min(queuePage,pages-1);native.audioPublish({sleepDeadline,sleepAtEnd,itemId:item?.id,trackId:track?.id,audioKind:lookup(current()).item?.audio?.kind||'music',appearance:{theme:settings.appearance?.theme,accent:getComputedStyle(document.body).getPropertyValue('--accent').trim()},name:item?.name,title:track?.title,artist:(track?.artists?.length?track.artists:item?.audio?.artists||[]).join(' / '),cover:track?.cover||(item?coverFor(item,'portrait'):''),codec:track?[track.codec,track.sampleRate?track.sampleRate+' Hz':'',track.channels?track.channels+' 声道':''].filter(Boolean).join(' · '):'',paused:media.paused,muted:media.muted,position:logicalTime(),duration:logicalDuration(),seekable:resolved.compatible||media.seekable.length>0,volume:media.volume,repeat:session.repeat,shuffle:session.shuffle,index:session.index,page:queuePage,pages,queue:session.queue.slice(queuePage*100,queuePage*100+100).map((e,i)=>({index:queuePage*100+i,title:lookup(e).track?.title||'音轨已移除'})),lyrics:{...lyrics,text:(lyrics.text||'').slice(0,200000),lines:(lyrics.lines||[]).slice(0,3000)},bookmarks:session.bookmarks.filter(b=>b.trackId===current()?.trackId),error:mini.querySelector('.audio-error').textContent});}
 native.onAudioRequestState?.(publish);
 native.onAudioCommand?.((name,value)=>{const n=Number(value);if(name==='reloadLyrics'){window.audioPlayer.reloadLyrics();return;}if(name==='bookmarkDelete')session.bookmarks=session.bookmarks.filter(b=>b.id!==value);else if(name==='bookmarkNote'){const mark=session.bookmarks.find(b=>b.id===value?.id);if(mark)mark.note=String(value.note||'').slice(0,1000);}else if(name==='seek')seekTo(Math.max(0,n||0));else if(name==='volume'){media.volume=session.volume=Math.max(0,Math.min(1,n||0));mini.querySelector('.audio-volume').value=session.volume;}else if(name==='repeat')session.repeat=['none','one','all'].includes(value)?value:'none';else if(name==='shuffle')session.shuffle=!!value;else if(name==='page')queuePage=Math.max(0,Math.floor(n)||0);else if(name==='sleep'){clearTimeout(sleepTimer);sleepAtEnd=value==='end';sleepDeadline=n>0&&n<=1440?Date.now()+n*60000:0;if(sleepDeadline)sleepTimer=setTimeout(()=>{sleepDeadline=0;media.pause();draw();},n*60000);}else if(['queue','remove','add','up'].includes(name)){const i=Math.floor(n);if(!session.queue[i])return;const active=current()?.queueEntryId;if(name==='queue'){externalPaused=false;session.index=i;load(true);}if(name==='add')session.queue.push({...session.queue[i],queueEntryId:crypto.randomUUID()});if(name==='up'&&i>0)[session.queue[i-1],session.queue[i]]=[session.queue[i],session.queue[i-1]];if(name==='remove')session.queue.splice(i,1);if(name!=='queue'){const found=session.queue.findIndex(e=>e.queueEntryId===active);session.index=found<0?Math.min(i,Math.max(0,session.queue.length-1)):found;if(found<0)load(false);}}else action(name);persist();renderQueue();draw();});

 function openFull(){if(native.audioOpenWindow){publish();native.audioOpenWindow().then(publish).catch(e=>showToast(e.message,'error'));return;}if(full)return;full=document.createElement('div');full.className='app-dialog-backdrop';full.innerHTML='<section class="app-dialog audio-full"><div class="app-dialog-head"><strong class="audio-full-title">声音</strong><button class="audio-close" title="收起播放器，继续播放">×</button></div><h3 class="audio-track-title"></h3><div class="audio-full-controls"><button data-audio="previous">上一轨</button><button data-audio="back">−10 秒</button><button data-audio="toggle">播放</button><button data-audio="forward">+10 秒</button><button data-audio="next">下一轨</button><span class="audio-full-time"></span><input class="audio-full-seek" type="range" min="0" max="1" step="0.1" aria-label="完整播放器进度"></div><div class="audio-full-controls"><button data-audio="mode" title="播放模式"></button><label>睡眠定时<select class="audio-sleep"><option value="0">关闭</option><option value="15">15 分钟</option><option value="30">30 分钟</option><option value="60">60 分钟</option><option value="end">本轨结束</option></select></label><button data-audio="bookmark">添加时间书签</button><button data-audio="lyrics">歌词与偏移</button></div><div class="audio-bookmarks"></div><div class="audio-lyrics"></div><div class="audio-queue"></div><div class="audio-full-controls"><button class="audio-queue-prev">上一页</button><span class="audio-queue-page"></span><button class="audio-queue-next">下一页</button></div></section>';document.body.append(full);const close=()=>{full.remove();full=null;};full.querySelector('.audio-close').onclick=close;full.querySelector('.audio-full-seek').oninput=e=>{if(media.seekable.length)media.currentTime=Number(e.target.value);};full.querySelector('.audio-queue-prev').onclick=()=>{queuePage=Math.max(0,queuePage-1);renderQueue();};full.querySelector('.audio-queue-next').onclick=()=>{queuePage++;renderQueue();};full.addEventListener('contextmenu',e=>{if(e.target===full){e.preventDefault();close();}});full.addEventListener('click',e=>{const b=e.target.closest('[data-audio]');if(b)action(b.dataset.audio);});full.querySelector('.audio-sleep').onchange=e=>{clearTimeout(sleepTimer);sleepAtEnd=e.target.value==='end';const minutes=Number(e.target.value);if(minutes>0)sleepTimer=setTimeout(()=>media.pause(),minutes*60000);};renderQueue();renderLyrics();draw();}
 function importDialog(dropped=[]){return window.audioImportUI.open(dropped);}
 document.addEventListener('dragover',e=>{if(activeView==='audio'&&e.dataTransfer?.types.includes('Files'))e.preventDefault();});
 document.addEventListener('drop',e=>{if(activeView!=='audio'||!e.dataTransfer?.files.length)return;e.preventDefault();e.stopImmediatePropagation();const paths=[...e.dataTransfer.files].map(f=>native.audioDroppedPath(f)).filter(Boolean);if(paths.length)importDialog(paths);},true);
 // Any disguise transition stops sound; leaving disguise never resumes playback.
 new MutationObserver(()=>{if(document.body.classList.contains('is-disguised')){media.pause();hls?.destroy();hls=null;native.audioStop?.();if(full){full.remove();full=null;}if(navigator.mediaSession)navigator.mediaSession.metadata=null;}draw();}).observe(document.body,{attributes:true,attributeFilter:['class']});
 window.addEventListener('beforeunload',()=>{media.pause();persist();native.audioSessionSaveFinal?.(session);hls?.destroy();native.audioStop?.();});
 native.audioSessionLoad().then(value=>{restoring=false;session=AudioContext.normalize({...session,...value});media.volume=session.volume;media.muted=!!session.muted;mini.querySelector('.audio-volume').value=session.volume;draw();}).catch(error=>showToast(error.message,'error'));
 async function command(command,refs,source=null){refs=(refs||[]).map(ref=>LibraryRelations.resolve(state,ref));const kinds=new Set(refs.map(ref=>lookup(ref).item?.audio?.kind));if(kinds.size!==1||kinds.has(undefined))throw Error('请选择同一分区的有效音轨');const kind=[...kinds][0];if(command!=='play'&&session.queue.length&&session.activeContext!==kind)throw Error('音乐和音声使用独立队列，请先明确播放该分区');await persist();session=AudioContext.switchTo(session,kind);const entries=refs.map(ref=>({...ref,queueEntryId:crypto.randomUUID()}));if(command==='play'){session.queue=entries;session.index=0;session.source=source;session.shuffleOrder=session.shuffle?AudioContext.shuffled(session):[];externalPaused=false;await load(true);}else if(command==='next'){session.queue.splice(session.index+1,0,...entries);if(session.shuffle){const order=AudioContext.sequence(session).filter(id=>!entries.some(e=>e.queueEntryId===id)),at=order.indexOf(current()?.queueEntryId);order.splice(at+1,0,...entries.map(e=>e.queueEntryId));session.shuffleOrder=order;}}else if(command==='append')session.queue.push(...entries);await persist();renderQueue();draw();}
 async function resumeContext(kind){await persist();session=AudioContext.switchTo(session,kind);externalPaused=false;await load(true,session.position);renderQueue();}
 window.audioPlayer={command,resumeContext,reloadLyrics:async()=>{const e=current();if(!e)return;const value=await native.audioLyrics(e.itemId,e.trackId);lyrics=parseLyrics(value,Number(lookup(e).track?.lyricsOffsetMs)||0);renderLyrics();},playItem,importDialog,media,pause:()=>media.pause(),getSession:()=>structuredClone(session)};
})();
