/* Read-only audio connections, separate from library/save synchronization. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),Net=require('./audio-network');
function xml(text){if(text.length>2*1024*1024||/<!DOCTYPE|<!ENTITY/i.test(text))throw Error('不接受带实体声明或过大的 WebDAV XML');const root={name:'root',children:[],text:''},stack=[root];let count=0;
 const decode=s=>s.replace(/&(#x[\da-f]+|#\d+|amp|lt|gt|quot|apos);/gi,(_,v)=>{if(v[0]==='#'){const n=v[1].toLowerCase()==='x'?parseInt(v.slice(2),16):Number(v.slice(1));return n>0&&n<=0x10ffff?String.fromCodePoint(n):'';}return {amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"}[v.toLowerCase()];});
 for(const token of text.match(/<!--[\s\S]*?-->|<!\[CDATA\[[\s\S]*?\]\]>|<[^>]*>|[^<]+/g)||[]){if(token.startsWith('<?')||token.startsWith('<!--'))continue;if(token.startsWith('<![CDATA[')){stack.at(-1).text+=token.slice(9,-3);continue;}if(token.startsWith('</')){const name=token.slice(2,-1).trim();if(stack.length<2||stack.pop().full!==name)throw Error('WebDAV XML 标签不匹配');}else if(token.startsWith('<')){const name=token.match(/^<([\w:.-]+)/)?.[1];if(!name||stack.length>32||++count>30000)throw Error('WebDAV XML 结构异常');const node={name:name.split(':').at(-1),full:name,text:'',children:[]};stack.at(-1).children.push(node);if(!token.endsWith('/>'))stack.push(node);}else stack.at(-1).text+=decode(token);}
 if(stack.length!==1)throw Error('WebDAV XML 不完整');return root;
}
const children=(node,name)=>node.children.filter(n=>n.name===name),child=(node,name)=>children(node,name)[0],desc=(node,name)=>node.name===name?[node]:node.children.flatMap(c=>desc(c,name));
function parseDav(body,current,scope){const tree=xml(body),out=[];for(const response of desc(tree,'response')){const href=child(response,'href')?.text;if(!href)continue;let u;try{u=Net.within(new URL(href,current),scope);}catch{continue;}const props=children(response,'propstat').filter(p=>/\s200\s/.test(child(p,'status')?.text||'')).map(p=>child(p,'prop')).filter(Boolean);if(!props.length)continue;const get=name=>props.map(p=>child(p,name)).find(Boolean),directory=Boolean(get('resourcetype')?.children.some(n=>n.name==='collection'));if(u.href.replace(/\/$/,'')===Net.url(current).href.replace(/\/$/,''))continue;const relativePath=u.pathname.slice(Net.url(scope.base).pathname.length);out.push({relativePath,name:get('displayname')?.text||decodeURIComponent(u.pathname.split('/').filter(Boolean).at(-1)||''),directory,size:Number(get('getcontentlength')?.text)||0,mime:get('getcontenttype')?.text||'',modified:get('getlastmodified')?.text||''});}return out;}
function create({dataRoot,safeStorage}){const file=()=>path.join(dataRoot(),'audio-connections.enc.json');function read(){if(!fs.existsSync(file()))return {version:1,connections:[]};const v=JSON.parse(fs.readFileSync(file(),'utf8'));if(v.version!==1||!Array.isArray(v.connections))throw Error('远程连接配置损坏，未覆盖');return v;}function write(v){fs.mkdirSync(dataRoot(),{recursive:true});fs.writeFileSync(file()+'.tmp',JSON.stringify(v));fs.renameSync(file()+'.tmp',file());}function available(){return safeStorage.isEncryptionAvailable()&&safeStorage.getSelectedStorageBackend?.()!=='basic_text';}
 function list(){return read().connections.map(c=>({id:c.id,name:c.name,kind:c.kind,base:c.base,available:available()}));}
 function save(value){if(!available())throw Error('系统安全存储不可用，不能保存远程连接');if(!['http','webdav'].includes(value.kind))throw Error('连接类型无效');const u=value.kind==='webdav'?require('./webdav-address')({webdavUrl:value.url}):Net.url(value.url);if(value.kind==='webdav'&&(u.search||u.hash))throw Error('WebDAV 根目录地址不能含查询参数');if(value.kind==='webdav'&&!u.pathname.endsWith('/'))u.pathname+='/';const data=read(),id=value.id||crypto.randomUUID(),old=data.connections.find(c=>c.id===id);if(value.id&&!old)throw Error('连接不存在');const extras=(Array.isArray(value.origins)?value.origins:[]).slice(0,8).map(o=>Net.url(o).origin);const payload={url:u.href,username:String(value.username||'').slice(0,500),password:String(value.password||'').slice(0,2000),origins:[u.origin,...new Set(extras)]};const c={id,name:String(value.name||u.hostname).slice(0,200),kind:value.kind,base:u.origin+(value.kind==='webdav'?u.pathname:'/'),encrypted:safeStorage.encryptString(JSON.stringify(payload)).toString('base64')};data.connections=data.connections.filter(c=>c.id!==id);data.connections.push(c);write(data);return {id,name:c.name,kind:c.kind,base:c.base};}
 function connection(id){const c=read().connections.find(c=>c.id===id);if(!c)throw Error('远程连接不存在，请重新配置');let p;try{if(!available())throw Error();p=JSON.parse(safeStorage.decryptString(Buffer.from(c.encrypted,'base64')));}catch{throw Error('此电脑无法解密连接，请重新输入地址和凭据');}const base=c.kind==='webdav'?require('./webdav-address')({webdavUrl:p.url}):Net.url(p.url),scope={base:base.href,origins:p.origins||[base.origin],...c.kind==='webdav'?{root:base.pathname}:{},authorization:p.username||p.password?'Basic '+Buffer.from(p.username+':'+p.password).toString('base64'):''};return {...c,url:base.href,scope};}
 async function browse(id,relative='',signal){const c=connection(id);if(c.kind!=='webdav')throw Error('此连接不是 WebDAV');const directory=Net.within(new URL(relative,c.url),c.scope);if(!directory.pathname.endsWith('/'))directory.pathname+='/';const target=directory.href;const r=await Net.request(target,c.scope,{method:'PROPFIND',headers:{Depth:'1','Content-Type':'application/xml; charset=utf-8'},body:'<?xml version="1.0"?><d:propfind xmlns:d="DAV:"><d:prop><d:displayname/><d:resourcetype/><d:getcontentlength/><d:getcontenttype/><d:getlastmodified/></d:prop></d:propfind>',signal});if(r.status!==207){await r.body?.cancel();throw Error('WebDAV 浏览失败（'+r.status+'）：'+(r.status===400?'服务器拒绝请求，请核对 WebDAV 根目录（InfiniCLOUD 使用 /dav/）':r.status===401?'认证失败，请检查连接 ID 与应用密码':r.status===403?'无目录访问权限':r.status===404?'目录不存在':r.status===429?'请求被限流':r.status>=500?'上游服务故障':'HTTP 请求失败'));}return parseDav((await Net.bytes(r,2*1024*1024)).toString('utf8'),target,c.scope).slice(0,5000);}
 function resolve(source){if(source.kind==='http'&&!source.connectionId){const u=Net.url(source.url);return {url:u.href,scope:{origins:[u.origin]}};}const c=connection(source.connectionId);return {url:source.kind==='webdav'?Net.within(new URL(source.relativePath,c.url),c.scope).href:c.url,scope:c.scope};}
 return {list,save,browse,resolve,connection,remove(id){const data=read();data.connections=data.connections.filter(c=>c.id!==id);write(data);}};
}
module.exports={create,xml,parseDav};
