/* Local audio authorization and low-frequency session persistence are independent of readers. */
const fs=require('node:fs'),path=require('node:path'),{Readable}=require('node:stream'),{randomBytes}=require('node:crypto');
const Local=require('./audio-local'),Audio=require('./audio-model');
const MIME={mp3:'audio/mpeg',flac:'audio/flac',wav:'audio/wav',m4a:'audio/mp4',aac:'audio/aac',ogg:'audio/ogg',opus:'audio/ogg',aiff:'audio/aiff',aif:'audio/aiff',wma:'audio/x-ms-wma',ape:'audio/ape'};
function create({ipcMain,protocol,dialog,windowFor,loadLibrary,saveLibrary,dataRoot,disguised,safeStorage,coverStore}){
 const metadataCandidates=new Map(),metadataJobs=new Map(),jobs=new Map(),previews=new Map(),grants=new Map(),playJobs=new Map(),Net=require('./audio-network'),streams=Net.createStreams(),decoder=require('./audio-decoder').create();
 const extras=require('./audio-extras').create({ipcMain,dataRoot,safeStorage,loadLibrary,saveLibrary,coverStore,dialog,windowFor,disguised});
 const playerBridge=require('./player-stream-bridge').create();
 const sessionFile=()=>path.join(dataRoot(),'audio-session.json');
 function cleanState(value,nested=false){const v=value||{};return {version:2,activeContext:['music','asmr','radio','other'].includes(v.activeContext)?v.activeContext:'music',...(!nested?{contexts:Object.fromEntries(['music','asmr','radio','other'].filter(k=>v.contexts?.[k]).map(k=>[k,cleanState(v.contexts[k],true)]))}:{}),shuffleOrder:(Array.isArray(v.shuffleOrder)?v.shuffleOrder:[]).filter(x=>typeof x==='string').slice(0,10000),source:v.source&&typeof v.source==='object'?{kind:String(v.source.kind||'').slice(0,40),id:String(v.source.id||'').slice(0,150)}:null,muted:Boolean(v.muted),queue:(Array.isArray(v.queue)?v.queue:[]).slice(0,10000).filter(e=>e&&typeof e.trackId==='string'&&typeof e.itemId==='string').map(e=>({queueEntryId:String(e.queueEntryId||'').slice(0,150),itemId:e.itemId.slice(0,150),trackId:e.trackId.slice(0,150)})),index:Math.max(0,Math.floor(Number(v.index)||0)),position:Math.max(0,Number(v.position)||0),volume:Math.max(0,Math.min(1,Number(v.volume)||0)),repeat:['none','all','one'].includes(v.repeat)?v.repeat:'none',shuffle:Boolean(v.shuffle),progress:(Array.isArray(v.progress)?v.progress:[]).slice(-10000).filter(p=>p&&typeof p.trackId==='string').map(p=>({trackId:p.trackId.slice(0,150),position:Math.max(0,Number(p.position)||0)})),bookmarks:(Array.isArray(v.bookmarks)?v.bookmarks:[]).slice(-2000).map((b,index)=>({id:String(b.id||require('node:crypto').createHash('sha256').update(JSON.stringify([b.itemId,b.trackId,b.position,index])).digest('hex')).slice(0,150),note:String(b.note||'').slice(0,1000),itemId:String(b.itemId||'').slice(0,150),trackId:String(b.trackId||'').slice(0,150),position:Math.max(0,Number(b.position)||0)}))};}
 ipcMain.handle('audio:sessionLoad',()=>{if(!fs.existsSync(sessionFile()))return {volume:1,queue:[]};try{const original=JSON.parse(fs.readFileSync(sessionFile(),'utf8')),first=loadLibrary().items.find(i=>i.id===original.queue?.[0]?.itemId);return cleanState(require('./audio-context').normalize(original,first?.audio?.kind));}catch{throw Error('播放记录损坏，已保留原文件');}});
 function saveSession(value){if(fs.existsSync(sessionFile())){try{JSON.parse(fs.readFileSync(sessionFile(),'utf8'));}catch{throw Error('播放记录损坏，停止写入');}}if(fs.existsSync(sessionFile())&&JSON.parse(fs.readFileSync(sessionFile(),'utf8')).version!==2)fs.copyFileSync(sessionFile(),sessionFile()+'.before-v2-'+Date.now()+'.bak',fs.constants.COPYFILE_EXCL);const safe=cleanState(value);fs.mkdirSync(dataRoot(),{recursive:true});fs.writeFileSync(sessionFile()+'.tmp',JSON.stringify(safe));fs.renameSync(sessionFile()+'.tmp',sessionFile());return true;}
 ipcMain.handle('audio:sessionSave',(_,value)=>saveSession(value));
 ipcMain.on('audio:sessionSaveFinal',(event,value)=>{try{event.returnValue=saveSession(value);}catch{event.returnValue=false;}});
 ipcMain.handle('audio:pickPaths',async(event,mode)=>{if(disguised()||!['files','folder'].includes(mode))throw Error('导入参数无效');const selected=await dialog.showOpenDialog(windowFor(event),{title:'选择本地音频',properties:mode==='folder'?['openDirectory','multiSelections']:['openFile','multiSelections'],filters:[{name:'音频',extensions:Object.keys(MIME)},{name:'所有文件',extensions:['*']}]});return selected.canceled?[]:selected.filePaths;});
 ipcMain.handle('audio:pickScan',async(event,mode,kind)=>{
  if(disguised())throw Error('当前不可用');if(!['files','folder'].includes(mode)||!['music','asmr','radio','other'].includes(kind))throw Error('导入参数无效');
  const selected=await dialog.showOpenDialog(windowFor(event),{title:'选择本地音频',properties:mode==='folder'?['openDirectory','multiSelections']:['openFile','multiSelections'],filters:[{name:'音频文件',extensions:Object.keys(MIME)},{name:'所有文件',extensions:['*']}]});if(selected.canceled)return null;
  return scanPaths(event,selected.filePaths,kind);
 });
 async function scanPaths(event,paths,kind,scanOptions={}){  jobs.get(event.sender.id)?.abort();const job=new AbortController();jobs.set(event.sender.id,job);const live={items:[]};previews.set(event.sender.id,live);let tail=Promise.resolve();const existingItems=loadLibrary().items;
  try{const result=await Local.scan(paths,{kind,coverStore,signal:job.signal,onCandidate:item=>{live.items.push(item);if(!event.sender.isDestroyed())event.sender.send('audio:scanProgress',{item});if((scanOptions.online||scanOptions.liveMetadata)&&!existingItems.some(old=>Audio.same(old,item)))tail=tail.then(async()=>{job.signal.throwIfAborted();try{const result=await previewMetadata(event,item.id,Boolean(scanOptions.liveMetadata));item._previewMatched=true;item._previewPrepared=Boolean(result.prepared);item._previewCandidates=result.candidates||[];if(!event.sender.isDestroyed())event.sender.send('audio:scanProgress',{item,prepared:result.prepared,candidates:result.candidates});}catch(error){if(job.signal.aborted)throw error;item._previewError=error.message;}}).catch(()=>{});},onProgress:value=>{if(!event.sender.isDestroyed())event.sender.send('audio:scanProgress',value);}});await tail;if(jobs.get(event.sender.id)!==job||job.signal.aborted)throw Error('扫描已取消');result.items=result.items.map(item=>live.items.find(v=>v.id===item.id)||item);result.items=require('./audio-scan-groups').reconcile(result.items,loadLibrary().items);previews.set(event.sender.id,result);return result;}finally{if(jobs.get(event.sender.id)===job)jobs.delete(event.sender.id);}}
 ipcMain.handle('audio:scanDropped',(event,paths,kind,scanOptions={})=>{if(disguised()||!Array.isArray(paths)||paths.length>5000||paths.some(p=>typeof p!=='string'||!path.isAbsolute(p))||!['music','asmr','radio','other'].includes(kind))throw Error('导入参数无效');return scanPaths(event,paths,kind,scanOptions);});
 ipcMain.handle('audio:cancelMetadata',event=>{metadataJobs.get(event.sender.id)?.abort();return true;});
 ipcMain.on('audio:cancel',event=>{for(const key of metadataCandidates.keys())if(key.startsWith(event.sender.id+':'))metadataCandidates.delete(key);jobs.get(event.sender.id)?.abort();metadataJobs.get(event.sender.id)?.abort();previews.delete(event.sender.id);});
 async function importPreview(event,ids,edits={}){if(!Array.isArray(ids)||ids.length>5000)throw Error('导入列表无效');const candidates=previews.get(event.sender.id)?.items||[],selected=new Set(ids),lib=loadLibrary();let added=0,merged=0;const groups=new Map(),chosen=[];for(const candidate of candidates.filter(i=>selected.has(i.id))){const edit=edits?.[candidate.id],group=typeof edit?.group==='string'?edit.group.slice(0,200):'';if(group){const prior=groups.get(group);if(prior){prior.audio=Audio.merge(prior.audio,candidate.audio);prior.localFiles=[...prior.localFiles,...candidate.localFiles];continue;}candidate.name=group;candidate.audio.groupingManual=true;candidate.audio.collectionKind=candidate.audio.kind==='asmr'?'work':'album';groups.set(group,candidate);}chosen.push(candidate);}for(const item of chosen){delete item._previewFields;delete item._previewMatched;delete item._previewPrepared;delete item._previewCandidates;delete item._previewError;if(typeof edits?.[item.id]==='string'&&edits[item.id].trim())item.name=edits[item.id].trim().slice(0,2000);let matches=lib.items.filter(i=>Audio.same(i,item)),existing=matches[0];if(existing&&item.audio.groupingManual&&matches.length>1){for(const other of matches.slice(1))Object.assign(lib,require('./library-relations').merge(lib,existing.id,other.id));existing=lib.items.find(i=>i.id===existing.id);}if(existing){Object.assign(existing,require('./local-model').fillMissing(existing,item));existing.audio=Audio.merge(existing.audio,item.audio);if(item.audio.groupingManual){existing.audio.groupingManual=true;existing.audio.collectionKind=item.audio.collectionKind;existing.name=item.name;}existing.localFiles=require('./local-model').mergeFiles(existing.localFiles||[],item.localFiles||[]);if(!existing.localPath)existing.localPath=item.localPath;merged++;}else{lib.items.push(item);added++;}}const saved=saveLibrary(lib);previews.set(event.sender.id,{items:candidates.filter(i=>!selected.has(i.id))});return {library:saved,added,merged};}
 async function previewMetadata(event,id,details=false,candidateId='',name='',importOnline=false){
 if(disguised()||!extras.preferences().online&&importOnline!==true)throw Error('声音联网未开启');const item=previews.get(event.sender.id)?.items.find(i=>i.id===id);if(!item)throw Error('预览已过期，请重新检查文件');if(typeof name==='string'&&name.trim()&&name.trim()!==item.name){item.name=name.trim().slice(0,500);for(const key of item._previewFields||[])delete item[key];item._previewFields=[];delete item.metadataSource;}if(item.audio.kind!=='music')return {item,candidates:[],message:'此类型保留本地资料，不套用音乐查询'};
 metadataJobs.get(event.sender.id)?.abort();const job=new AbortController();metadataJobs.set(event.sender.id,job);const key=event.sender.id+':'+id;
 try{let rows=metadataCandidates.get(key);if(!candidateId){rows=await extras.metadata.search(item,job.signal,extras.preferences().chinese);job.signal.throwIfAborted();metadataCandidates.set(key,rows);if(metadataCandidates.size>500)metadataCandidates.delete(metadataCandidates.keys().next().value);}
 const norm=v=>String(v||'').normalize('NFKC').toLowerCase().replace(/[\p{P}\p{Z}]/gu,'');const matches=(rows||[]).filter(r=>norm(r.name)===norm(item.name)&&(r.artists||[]).some(a=>(item.audio.artists||[]).some(b=>norm(a)===norm(b)))&&r.entityType==='track'&&item.audio.tracks.length===1&&item.audio.tracks[0].durationSeconds>0&&Math.abs((r.duration||0)-item.audio.tracks[0].durationSeconds)<=2);
 const selected=candidateId?(rows||[]).find(r=>r.id===candidateId):details&&matches.length===1?matches[0]:null;
 if(selected){const detail=await extras.metadata.detail(selected,job.signal),cover=await extras.metadata.cover(detail,job.signal).catch(()=>'' );job.signal.throwIfAborted();for(const [field,value]of Object.entries({publisher:detail.publisher,releaseDate:detail.date,genres:detail.genres,cover})){if(!item.lockedFields?.includes(field)&&(!item[field]||Array.isArray(item[field])&&!item[field].length)&&value){item[field]=value;item._previewFields=[...(item._previewFields||[]),field];}}if(!item.audio.artists.length)item.audio.artists=detail.artists||[];item.metadataSource=detail.source||selected.source;return {item,candidates:[],prepared:true};}
 return {item,candidates:(rows||[]).slice(0,100),providers:rows?.providers||[],message:rows?.length?'请选择准确作品 / 发行版本':rows?.failures?.length?rows.failures.map(v=>v.source+'：'+v.message).join('；'):'0 条结果：未找到资料'};
 }finally{if(metadataJobs.get(event.sender.id)===job)metadataJobs.delete(event.sender.id);}
 }
 ipcMain.handle('audio:previewMetadata',previewMetadata);
 ipcMain.handle('audio:import',importPreview);
 ipcMain.handle('audio:importFiles',async(event,paths,kind)=>{if(disguised()||!Array.isArray(paths)||paths.length>5000||!['music','asmr','radio','other'].includes(kind))throw Error('文件导入参数无效');for(const p of paths){if(typeof p!=='string'||!path.isAbsolute(p)||!(await fs.promises.stat(p)).isFile())throw Error('请选择文件，文件夹请使用扫描入口');}const previous=previews.get(event.sender.id);try{const result=await scanPaths(event,paths,kind);if(!result)throw Error('已取消导入');return {...await importPreview(event,result.items.map(i=>i.id)),warnings:result.warnings};}finally{if(previous&&!event.sender.isDestroyed())previews.set(event.sender.id,previous);}});
 ipcMain.handle('audio:lyrics',async(_,itemId,trackId)=>{const saved=extras.userLyrics(trackId);if(saved)return saved;const item=loadLibrary().items.find(i=>i.id===itemId&&i.type==='audio'),track=item?.audio?.tracks.find(t=>t.id===trackId);return item&&track?require('./audio-local-lyrics').read(item,track):{kind:'none',text:''};});
 ipcMain.handle('audio:resolve',async(event,itemId,trackId,options={})=>{options=options&&typeof options==='object'?options:{};if(disguised())throw Error('当前不可播放');const item=loadLibrary().items.find(i=>i.id===itemId&&i.type==='audio'),track=item?.audio?.tracks.find(t=>t.id===trackId),source=item?.audio?.sources.find(s=>s.id===(track?.preferredSourceId||track?.sourceRefs[0]));if(!source)throw Error('未找到音轨来源');playJobs.get(event.sender.id)?.abort();const playJob=new AbortController();playJobs.set(event.sender.id,playJob);streams.stop();decoder.stop();if(source.kind!=='local'){const target=extras.remote.resolve(source),info=await Net.probe(target.url,target.scope,playJob.signal);playJob.signal.throwIfAborted();return {url:streams.grant(target.url,target.scope,info.hls),hls:info.hls,range:info.range,title:track.title,duration:track.durationSeconds,resumePolicy:item.audio.resumePolicy};}const stat=await fs.promises.stat(source.localPath).catch(()=>null);if(!stat?.isFile())throw Error('音频文件不存在，请重新定位来源');if(!Local.extensions.test(source.localPath))throw Error('该来源不是支持的音频文件');await Local.probe(source.localPath,playJob.signal);playJob.signal.throwIfAborted();for(const [token,g]of grants)if(g.owner===event.sender.id)grants.delete(token);const token=randomBytes(24).toString('hex');const start=Number.isFinite(Number(options.start))?Math.max(0,Math.min(864000,Number(options.start))):0;grants.set(token,{owner:event.sender.id,file:source.localPath,compatible:options.compatibility===true,start});return {compatible:options.compatibility===true,offset:options.compatibility===true?start:0,url:'um-audio://local/'+token,title:track.title,duration:track.durationSeconds,resumePolicy:item.audio.resumePolicy};});
 protocol.handle('um-audio',async request=>{try{const url=new URL(request.url);if(url.hostname==='remote')return streams.respond(request);const g=grants.get(url.pathname.slice(1));if(!g||url.hostname!=='local'||!['GET','HEAD'].includes(request.method))return new Response(null,{status:403});if(g.compatible)return decoder.response(g.file,g.start,request);const stat=await fs.promises.stat(g.file);const range=require('./local-services').parseRange(request.headers.get('range'),stat.size);if(!range)return new Response(null,{status:416,headers:{'Content-Range':'bytes */'+stat.size}});const headers={'Content-Type':MIME[path.extname(g.file).slice(1).toLowerCase()]||'application/octet-stream','Content-Length':String(range.end-range.start+1),'Accept-Ranges':'bytes','Cache-Control':'no-store'};if(range.status===206)headers['Content-Range']=`bytes ${range.start}-${range.end}/${stat.size}`;const stream=request.method==='HEAD'?null:fs.createReadStream(g.file,{start:range.start,end:range.end});if(stream){const abort=()=>stream.destroy();request.signal?.addEventListener('abort',abort,{once:true});stream.once('close',()=>request.signal?.removeEventListener('abort',abort));}return new Response(stream?Readable.toWeb(stream):null,{status:range.status,headers});}catch{return new Response(null,{status:404});}});
 ipcMain.on('audio:stop',()=>{for(const job of playJobs.values())job.abort();playJobs.clear();streams.stop();decoder.stop();grants.clear();});
 return {resolvePlayer:async(reference,signal)=>{if(disguised())throw Error('当前不可播放');const ids=require('./player-source').parse(reference);if(!ids)throw Error('音轨引用无效');const item=loadLibrary().items.find(i=>i.id===ids[0]&&i.type==='audio'),track=item?.audio?.tracks.find(t=>t.id===ids[1]),source=item?.audio?.sources.find(s=>s.id===(track?.preferredSourceId||track?.sourceRefs?.[0]));if(!source||source.kind==='local')throw Error('远程音轨来源已改变或不存在');return playerBridge.open(extras.remote.resolve(source),signal);},lyrics:extras.lyricsService,stop(){void playerBridge.close();extras.stop();for(const job of playJobs.values())job.abort();playJobs.clear();streams.stop();decoder.stop();for(const job of jobs.values())job.abort();jobs.clear();for(const job of metadataJobs.values())job.abort();metadataJobs.clear();metadataCandidates.clear();previews.clear();grants.clear();}};
}
module.exports={create};
