/* Bounded requests; redirects and playlist subrequests never expand a grant's origins. */
const {randomBytes}=require('node:crypto');
function url(value){let u;try{u=new URL(String(value||'').trim());}catch{throw Error('请填写完整的 HTTP(S) 地址（http:// 或 https://）');}if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error('仅允许不含账号密码的 HTTP(S) 地址');u.hash='';return u;}
function within(value,scope){const u=url(value);if(!scope.origins.includes(u.origin)&&!(u.protocol==='https:'&&!u.port&&scope.httpsHosts?.some(h=>u.hostname===h||u.hostname.endsWith('.'+h))))throw Error('目标不在已授权的服务器范围内');if(scope.root&&u.origin===scope.origins[0]){let p;try{p=decodeURIComponent(u.pathname);}catch{throw Error('路径编码无效');}if(p.includes('\\')||p.split('/').includes('..')||!p.startsWith(decodeURIComponent(scope.root)))throw Error('路径超出已选择的音频根目录');}return u;}
async function request(value,scope,{method='GET',headers={},body,signal,fetcher=fetch}={}){
 let u=within(value,scope);for(let hop=0;hop<5;hop++){
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(new DOMException('请求超时','TimeoutError')),15000);const signals=[controller.signal,...signal?[signal]:[]];let response;
  try{response=await fetcher(u,{method,headers:{...headers,...scope.authorization&&u.origin===scope.origins[0]?{Authorization:scope.authorization}:{}},body,redirect:'manual',signal:AbortSignal.any(signals)});}catch(error){signal?.throwIfAborted();controller.signal.throwIfAborted();throw Object.assign(Error('音频服务器连接失败',{cause:error}),{code:'UPSTREAM'});}finally{clearTimeout(timer);}
  if([301,302,303,307,308].includes(response.status)){const location=response.headers.get('location');await response.body?.cancel();if(!location)throw Error('服务器重定向缺少目标');const next=new URL(location,u);if(scope.httpsHosts?.some(h=>next.hostname===h||next.hostname.endsWith('.'+h)))next.protocol='https:';u=within(next,scope);continue;}
  return response;
 }throw Error('服务器重定向次数过多');
}
async function readTimed(reader){let timer;try{return await Promise.race([reader.read(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new DOMException('读取超时','TimeoutError')),15000);})]);}finally{clearTimeout(timer);}}
async function bytes(response,max){if(Number(response.headers.get('content-length'))>max){await response.body?.cancel();throw Error('服务器返回内容超过安全大小');}const reader=response.body?.getReader();if(!reader)return Buffer.alloc(0);const chunks=[];let total=0;try{while(true){const {done,value}=await readTimed(reader);if(done)break;total+=value.length;if(total>max)throw Error('服务器返回内容超过安全大小');chunks.push(Buffer.from(value));}return Buffer.concat(chunks);}finally{await reader.cancel().catch(()=>{});}}
async function probe(value,scope,signal){const r=await request(value,scope,{headers:{Range:'bytes=0-4095'},signal});if(!r.ok){await r.body?.cancel();throw Error(r.status===401||r.status===403?'认证失败或链接已过期，请更新连接':'音频服务器返回 '+r.status);}const reader=r.body?.getReader();let head=Buffer.alloc(0);try{while(head.length<4096&&reader){const part=await readTimed(reader);if(part.done)break;head=Buffer.concat([head,Buffer.from(part.value).subarray(0,4096-head.length)]);}}finally{await reader?.cancel().catch(()=>{});}const type=(r.headers.get('content-type')||'').split(';')[0].toLowerCase(),hls=head.toString('utf8').trimStart().startsWith('#EXTM3U');const magic=/^(ID3|fLaC|OggS|RIFF)/.test(head.toString('latin1',0,4))||head.toString('latin1',4,8)==='ftyp'||head[0]===255&&(head[1]&224)===224;
 if(!hls&&!type.startsWith('audio/')&&!magic)throw Error('地址不是可识别的音频或 HLS；网页、登录页和分享链接不能播放');return {hls,mime:hls?'application/vnd.apple.mpegurl':type||'application/octet-stream',range:r.status===206};}
function rewriteHls(text,base,scope,grant){if(text.length>1024*1024||!text.trimStart().startsWith('#EXTM3U'))throw Error('HLS 清单无效');let childPlaylist=false;return text.split(/\r?\n/).map(line=>{if(line.startsWith('#EXT-X-STREAM-INF'))childPlaylist=true;if(line.startsWith('#'))return line.replace(/URI="([^"]+)"/g,(_,uri)=>'URI="'+grant(within(new URL(uri,base),scope).href,/^#EXT-X-MEDIA|^#EXT-X-I-FRAME/.test(line))+'"');if(!line.trim())return line;const target=within(new URL(line.trim(),base),scope).href,isPlaylist=childPlaylist;childPlaylist=false;return grant(target,isPlaylist);}).join('\n');}
function createStreams({urlForToken=token=>'um-audio://remote/'+token}={}){const grants=new Map(),controllers=new Set();function grant(target,scope,playlist=false){for(const [key,g]of grants)if(g.target===target&&g.scope===scope&&g.playlist===playlist)return urlForToken(key);if(grants.size>=6000){const first=[...grants].find(([,g])=>!g.playlist);if(first)grants.delete(first[0]);else throw Error('清单引用过多');}const token=randomBytes(24).toString('hex');grants.set(token,{target,scope,playlist});return urlForToken(token);}
 async function respond(requestValue){const token=new URL(requestValue.url).pathname.slice(1),g=grants.get(token);if(!g||!['GET','HEAD'].includes(requestValue.method))return new Response(null,{status:403});const controller=new AbortController();controllers.add(controller);const signal=AbortSignal.any([controller.signal,requestValue.signal]);try{const r=await request(g.target,g.scope,{method:requestValue.method,headers:requestValue.headers.get('range')?{Range:requestValue.headers.get('range')}:{},signal});if(r.status===401||r.status===403){await r.body?.cancel();controllers.delete(controller);return new Response('连接认证失败或已过期',{status:r.status});}const h=new Headers();for(const k of ['content-type','content-length','content-range','accept-ranges'])if(r.headers.has(k))h.set(k,r.headers.get(k));h.set('Cache-Control','no-store');if(requestValue.method==='HEAD'){controllers.delete(controller);await r.body?.cancel();return new Response(null,{status:r.status,headers:h});}
 if(r.ok&&(g.playlist||/mpegurl/i.test(h.get('content-type')||''))){const body=(await bytes(r,1024*1024)).toString('utf8'),rewritten=rewriteHls(body,r.url||g.target,g.scope,(u,p)=>grant(u,g.scope,p));controllers.delete(controller);return new Response(rewritten,{headers:{'Content-Type':'application/vnd.apple.mpegurl','Cache-Control':'no-store'}});}
 if(!r.body){controllers.delete(controller);return new Response(null,{status:r.status,headers:h});}const reader=r.body.getReader();const stream=new ReadableStream({async pull(c){let timer;try{const chunk=await Promise.race([reader.read(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('网络音频长时间无响应')),30000);})]);if(chunk.done){controllers.delete(controller);c.close();}else c.enqueue(chunk.value);}catch(e){controller.abort();controllers.delete(controller);c.error(e);}finally{clearTimeout(timer);}},cancel(){controller.abort();controllers.delete(controller);return reader.cancel();}});return new Response(stream,{status:r.status,headers:h});
 }catch{controller.abort();controllers.delete(controller);return new Response('音频网络请求失败或越过授权范围',{status:502});}}
 return {grant,respond,stop(){for(const c of controllers)c.abort();controllers.clear();grants.clear();},count:()=>controllers.size};}
module.exports={url,within,request,bytes,probe,rewriteHls,createStreams};
