(()=>{
 const views={all:'全部声音',albums:'专辑',songs:'歌曲',playlists:'歌单',works:'音声',radio:'电台',other:'其他音频'};let playlistFilterState=null,view='all';try{view=localStorage.getItem('audioSubview')||'all';}catch{}if(!views[view])view='all';
 let reorderControllers=[],savingOrder=false;
 const songOrderKey='audioSongOrder';
 function songOrder(){try{return JSON.parse(localStorage.getItem(songOrderKey)||'[]');}catch{return [];}}
 function manual(){localStorage.setItem('librarySort:'+librarySorting.key(),JSON.stringify({...librarySorting.preferences(),manual:true}));}
 async function saveOrder(next,setManual=true){const grid=$('libraryGrid'),closed=new Set([...grid.querySelectorAll('.audio-playlist:not([open])')].map(n=>n.dataset.id)),focus=document.activeElement?.closest('[data-id]')?.dataset.id;state=await native.saveLibrary(next);if(setManual)manual();ReorderMotion.preserve(grid,()=>{renderLibrary();for(const p of grid.querySelectorAll('.audio-playlist'))p.open=!closed.has(p.dataset.id);if(focus)[...grid.querySelectorAll('[data-id]')].find(n=>n.dataset.id===focus)?.focus({preventScroll:true});});}
 function bindOrder(host,commit){reorderControllers.push(installQueueReorder(host,async ids=>{if(savingOrder)throw Error('排序正在保存，请稍后再试');savingOrder=true;try{await commit(ids);}finally{savingOrder=false;}},error=>showToast('排序保存失败：'+error.message,'error')));}
 const refs=item=>AudioContext.order(item.audio.tracks||[]).map(t=>({itemId:item.id,trackId:t.id}));
 async function run(command,entries,source){try{await audioPlayer.command(command,entries,source);}catch(e){showToast(e.message,'error');}}
 async function save(next){state=await native.saveLibrary(next);renderLibrary();}
 function addToPlaylist(entries){const d=workspaceDialog('加入歌单'),select=document.createElement('select');for(const p of state.playlists||[]){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;select.append(o);}d.body.append(select);d.actions.append(workspaceButton('加入',async()=>{try{await save(LibraryRelations.playlist(state,'add',{id:select.value,entries}));d.close();}catch(e){d.status.textContent=e.message;}}));if(!select.options.length)d.status.textContent='还没有歌单，请先在歌单页创建。';}
 function renamePlaylist(id){const d=workspaceDialog(id?'重命名歌单':'新建歌单'),input=document.createElement('input');input.value=state.playlists?.find(p=>p.id===id)?.name||'';input.placeholder='歌单名称';d.body.append(input);d.actions.append(workspaceButton('保存',async()=>{try{await save(LibraryRelations.playlist(state,id?'rename':'create',{id,name:input.value}));d.close();}catch(e){d.status.textContent=e.message;}}));}
 function actions(entries,item,source){const host=document.createElement('div');host.className='audio-row-actions';for(const [label,command]of [['立即播放','play'],['下一首播放','next'],['加入队列','append']])host.append(workspaceButton(label,()=>run(command,entries,source)));if(item?.audio?.kind==='music')host.append(workspaceButton('加入歌单',()=>addToPlaylist(entries)));return host;}
 function songs(host,rows,playlist){const entryKeys=playlist?AudioBrowserOrder.entryIds(playlist.entries):null;for(const {item,track,entry}of rows){const row=document.createElement('article');row.className='audio-song-row';row.draggable=true;row.tabIndex=0;row.dataset.id=playlist?entryKeys[playlist.entries.indexOf(entry)]:AudioBrowserOrder.trackId({item,track});row.title='拖动排序；Alt + 上下方向键调整位置';const label=document.createElement('button');label.className='audio-song-title';label.textContent=track.title;label.onclick=()=>run('play',[{itemId:item.id,trackId:track.id}],playlist?{kind:'playlist',id:playlist.id}:{kind:'single',id:track.id});const small=document.createElement('small');small.textContent=(track.artists?.join(' / ')||item.audio.artists?.join(' / ')||'艺术家未知')+ (track.title!==item.name?' · '+item.name:'');const info=document.createElement('div');info.append(label,small);const image=document.createElement('img');image.className='audio-song-cover';image.draggable=false;image.src=track.cover||coverFor(item,'portrait')||'assets/icon.svg';image.alt='';image.onerror=()=>{image.onerror=null;image.src='assets/icon.svg';};row.append(image,info,actions([{itemId:item.id,trackId:track.id}],item,playlist?{kind:'playlist',id:playlist.id}:undefined));row.oncontextmenu=e=>{e.preventDefault();const d=workspaceDialog(track.title);d.body.append(actions([{itemId:item.id,trackId:track.id}],item,playlist?{kind:'playlist',id:playlist.id}:undefined));};if(playlist){row.append(workspaceButton('移除',()=>save(LibraryRelations.playlist(state,'remove',{id:playlist.id,entryId:entry.id}))));}if(window.audioCompletion)row.append(workspaceButton('补全资料',()=>audioCompletion.track(item.id,track.id)));host.append(row);}bindOrder(host,async ids=>{if(playlist){const current=state.playlists.find(p=>p.id===playlist.id);if(!current)throw Error('歌单已不存在');const keys=AudioBrowserOrder.entryIds(current.entries),order=AudioBrowserOrder.merge(keys,ids),byId=new Map(keys.map((id,i)=>[id,current.entries[i]]));await saveOrder({...state,playlists:state.playlists.map(p=>p.id===playlist.id?{...p,entries:order.map(id=>byId.get(id)),updatedAt:new Date().toISOString()}:p)},false);}else{const all=state.items.filter(i=>i.type==='audio'&&i.audio?.kind==='music').flatMap(item=>(item.audio.tracks||[]).map(track=>({item,track}))),ordered=AudioBrowserOrder.apply(all,songOrder(),AudioBrowserOrder.trackId).map(AudioBrowserOrder.trackId);localStorage.setItem(songOrderKey,JSON.stringify(AudioBrowserOrder.merge(ordered,ids)));manual();}});}
 function render(items){for(const controller of reorderControllers)controller.destroy();reorderControllers=[];const playlistMode=activeView==='audio'&&view==='playlists';$('filterToggle').classList.toggle('hidden',playlistMode);$('addBtn').classList.toggle('hidden',playlistMode);if(playlistMode){if(playlistFilterState===null)playlistFilterState=$('filters').classList.contains('hidden');$('filters').classList.add('hidden');}else if(playlistFilterState!==null){$('filters').classList.toggle('hidden',playlistFilterState);playlistFilterState=null;}document.querySelector('.resource-count-unit').textContent=activeView==='audio'?(view==='playlists'?'个歌单':view==='songs'?'首歌曲':'项资源'):'项资源';let nav=$('audioSubview');if(!nav){nav=document.createElement('nav');nav.id='audioSubview';nav.className='audio-subviews';$('librarySearchHeader').after(nav);}nav.hidden=activeView!=='audio';if(activeView!=='audio')return false;nav.replaceChildren();for(const [id,label]of Object.entries(views)){const b=workspaceButton(label,()=>{view=id;try{localStorage.setItem('audioSubview',id);}catch{}renderLibrary();});b.classList.toggle('active',id===view);b.setAttribute('aria-pressed',String(id===view));if(['albums','works','radio'].includes(id))b.classList.add('audio-group-start');nav.append(b);}const commands=document.createElement('div');commands.className='audio-view-commands';nav.append(commands);
  if(!['songs','playlists'].includes(view))return false;const grid=$('libraryGrid');grid.replaceChildren();grid.className='audio-browser-list';$('libraryEmpty').classList.add('hidden');
  if(view==='songs'){const rows=items.flatMap(item=>(item.audio.tracks||[]).map(track=>({item,track}))).filter(r=>[r.track.title,...r.track.artists||[],r.item.name].join(' ').toLowerCase().includes($('searchInput').value.toLowerCase()));const manualRows=AudioBrowserOrder.apply(rows,songOrder(),AudioBrowserOrder.trackId),ordered=LibrarySort.sort(manualRows.map((r,i)=>({...r,id:AudioBrowserOrder.trackId(r),name:r.track.title,rating:r.track.rating,createdAt:r.item.createdAt,updatedAt:r.item.updatedAt,releaseDate:r.item.releaseDate,sortOrder:i})),librarySorting.preferences());songs(grid,ordered);commands.append(workspaceButton('播放当前全部歌曲',()=>{const byId=new Map(ordered.map(r=>[AudioBrowserOrder.trackId(r),{itemId:r.item.id,trackId:r.track.id}]));run('play',[...grid.children].map(n=>byId.get(n.dataset.id)).filter(Boolean),{kind:'selection'});}));$('resultCount').textContent=rows.length;if(!rows.length)grid.textContent='还没有歌曲，请导入音乐。';}
  else{commands.append(workspaceButton('新建歌单',()=>renamePlaylist()));const lists=LibrarySort.sort((state.playlists||[]).filter(p=>p.name.toLowerCase().includes($('searchInput').value.toLowerCase())),librarySorting.preferences());$('resultCount').textContent=lists.length;for(const p of lists){const details=document.createElement('details');details.className='audio-playlist';details.draggable=true;details.tabIndex=0;details.dataset.id=p.id;details.open=true;const summary=document.createElement('summary');summary.textContent=p.name+' · '+p.entries.length+' 首';details.append(summary);const valid=p.entries.map(entry=>{const r=LibraryRelations.resolve(state,entry),item=state.items.find(i=>i.id===r.itemId),track=item?.audio?.tracks.find(t=>t.id===r.trackId);return {entry,item,track};}).filter(r=>r.track),entries=valid.map(r=>({itemId:r.item.id,trackId:r.track.id}));const buttons=document.createElement('div');buttons.className='audio-row-actions';buttons.append(workspaceButton('播放歌单',()=>run('play',entries,{kind:'playlist',id:p.id})),workspaceButton('重命名',()=>renamePlaylist(p.id)),workspaceButton('删除歌单',async()=>{if(await askConfirm('只删除歌单，不删除歌曲和原文件。',{title:'删除歌单'}))await save(LibraryRelations.playlist(state,'delete',{id:p.id}));}));if(window.audioCompletion)buttons.append(workspaceButton('补全歌单资料',()=>audioCompletion.playlist(p.id)));details.append(buttons);const tracks=document.createElement('div');tracks.className='audio-playlist-tracks';details.append(tracks);songs(tracks,valid,p);if(valid.length!==p.entries.length){const missing=document.createElement('p');missing.textContent=(p.entries.length-valid.length)+' 首歌曲来源已移除，引用仍保留';details.append(missing);}grid.append(details);}bindOrder(grid,async ids=>{const all=LibrarySort.sort(state.playlists||[],{field:'custom'}),order=AudioBrowserOrder.merge(all.map(p=>p.id),ids),rank=new Map(order.map((id,i)=>[id,i]));await saveOrder({...state,playlists:state.playlists.map(p=>({...p,sortOrder:rank.get(p.id)}))});});if(!lists.length)grid.textContent='创建歌单后，在歌曲行选择“加入歌单”。';}return true;
 }
 function matches(item){if(activeView!=='audio'||view==='all')return true;const kind=item.audio?.kind||'music';if(view==='albums')return kind==='music'&&item.audio.collectionKind==='album';if(['songs','playlists'].includes(view))return kind==='music';if(view==='works')return kind==='asmr';if(view==='radio')return kind==='radio';return kind==='other';}
 window.audioBrowser={setView(id){if(!views[id])return;view=id;try{localStorage.setItem('audioSubview',id);}catch{}renderLibrary();},get view(){return view;},render,matches,addToPlaylist,actions};
})();
