/* Presentation window only; it never owns an audio element or network stream. */
const path=require('node:path');
function create({BrowserWindow,ipcMain}){let win=null,owner=null,state=null;
 ipcMain.handle('audio:windowOpen',async event=>{owner=event.sender;if(win&&!win.isDestroyed()){win.show();win.focus();return;}win=new BrowserWindow({width:880,height:760,minWidth:600,minHeight:500,frame:false,title:'声音 · 悦森盒 YueDen',backgroundColor:'#0c121b',icon:path.join(__dirname,'assets/icon.ico'),webPreferences:{preload:path.join(__dirname,'audio-window-preload.js'),contextIsolation:true,sandbox:true,nodeIntegration:false}});win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());const windowState=()=>win?.webContents.send('window:state',{maximized:win?.isMaximized()});win.on('maximize',windowState);win.on('unmaximize',windowState);win.webContents.on('did-finish-load',windowState);win.once('closed',()=>{win=null;});await win.loadFile(path.join(__dirname,'audio-window.html'));if(!owner.isDestroyed())owner.send('audio:requestState');});
 ipcMain.on('audio:windowState',(event,value)=>{if(event.sender!==owner||!value||typeof value!=='object')return;if(JSON.stringify(value).length>1024*1024)return;state=value;if(win&&!win.isDestroyed())win.webContents.send('audio:state',state);});
 ipcMain.handle('audio:windowInit',()=>state);
 ipcMain.on('audio:windowCommand',(event,command,value)=>{if(event.sender!==win?.webContents||!owner||owner.isDestroyed())return;if(!['mode','toggle','next','previous','back','forward','mute','bookmark','bookmarkNote','bookmarkDelete','reloadLyrics','lyrics','seek','volume','repeat','shuffle','queue','remove','up','add','page','sleep'].includes(command))return;if(command==='bookmarkNote'){if(!value||typeof value.id!=='string'||value.id.length>150||typeof value.note!=='string'||value.note.length>1000)return;value={id:value.id,note:value.note};}else if(value!=null&&!['string','number','boolean'].includes(typeof value)||typeof value==='string'&&value.length>150)return;owner.send('audio:command',{command,value});});
 return {close(){win?.close();win=null;state=null;},hide(){win?.hide();state=null;}};
}
module.exports={create};
