/* Metadata/lyrics and read-only remote libraries; never calls backup synchronization. */
const fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),Model=require('./audio-model'),Net=require('./audio-network');
function create({ipcMain,dataRoot,safeStorage,loadLibrary,saveLibrary,coverStore,dialog,windowFor,disguised}){
 const remote=require('./audio-remote').create({dataRoot,safeStorage}),metadata=require('./audio-providers').create({dataRoot,coverStore,music:require('./audio-metadata').create({dataRoot,coverStore})}),jobs=new Map(),candidates=new Map();
 const searchResult=rows=>({items:[...rows],providers:rows.providers||[],failures:rows.failures||[]});
 const prefsFile=()=>path.join(dataRoot(),'audio-preferences.json'),lyricsFile=id=>path.join(dataRoot(),'audio-lyrics',require('node:crypto').createHash('sha256').update(String(id)).digest('hex')+'.json');
 function read(file,fallback){if(!fs.existsSync(file))return fallback;try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{throw Error('声音配置损坏，原文件已保留');}}
 function write(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file+'.tmp',JSON.stringify(value));fs.renameSync(file+'.tmp',file);}
 const preferences=()=>{const value=read(prefsFile(),{});return {...value,chinese:true,online:value.defaultsVersion===2?value.online!==false:true};};
 function itemTrack(itemId,trackId){const item=loadLibrary().items.find(i=>i.id===itemId&&i.type==='audio'),track=item?.audio?.tracks.find(t=>t.id===trackId);if(!item)throw Error('声音条目已不存在');return {item,track};}
 function start(owner){jobs.get(owner)?.abort();const job=new AbortController();jobs.set(owner,job);return job;}
 ipcMain.handle('audio:preferences',()=>preferences());
 ipcMain.handle('audio:setPreferences',(_,value)=>{const next={defaultsVersion:2,online:Boolean(value?.online),chinese:true};write(prefsFile(),next);if(!next.online)for(const job of jobs.values())job.abort();return next;});
 ipcMain.on('audio:cancelExtras',event=>{jobs.get(event.sender.id)?.abort();candidates.delete(event.sender.id);});
 ipcMain.handle('audio:search',async(event,itemId)=>{if(disguised())throw Error('当前不可查询');if(!preferences().online)throw Error('请先开启声音联网资料；只发送作品名称、艺术家、专辑和时长，不上传文件或路径');const {item}=itemTrack(itemId),job=start(event.sender.id);const result=await metadata.search(item,job.signal,preferences().chinese);job.signal.throwIfAborted();candidates.set(event.sender.id,{itemId,items:result});return searchResult(result);});
 ipcMain.handle('audio:searchDraft',async(event,value)=>{if(disguised()||!preferences().online)throw Error('声音联网未开启');const item={name:String(value?.name||'').slice(0,500),audio:Model.normalize(value?.audio||{})};if(!item.name.trim())throw Error('请先输入名称');const job=start(event.sender.id),result=await metadata.search(item,job.signal,preferences().chinese);job.signal.throwIfAborted();candidates.set(event.sender.id,{items:result});return searchResult(result);});
 ipcMain.handle('audio:metadataDetails',async(event,id)=>{if(disguised()||!preferences().online)throw Error('声音联网未开启');const candidate=candidates.get(event.sender.id)?.items.find(row=>row.id===id);if(!candidate)throw Error('候选已过期，请重新搜索');const job=start(event.sender.id),detail=await metadata.detail(candidate,job.signal),cover=await metadata.cover(detail,job.signal).catch(()=>'');job.signal.throwIfAborted();return {...detail,cover};});
 ipcMain.handle('audio:applyMetadata',async(event,itemId,candidateId)=>{const bundle=candidates.get(event.sender.id),candidate=bundle?.itemId===itemId&&bundle.items.find(i=>i.id===candidateId);if(!candidate)throw Error('资料候选已过期，请重新查询');if(!preferences().online)throw Error('声音联网已关闭');const job=start(event.sender.id),detail=await metadata.detail(candidate,job.signal),cover=await metadata.cover(detail,job.signal).catch(()=>''),lib=loadLibrary(),item=lib.items.find(i=>i.id===itemId);if(!item||job.signal.aborted)throw Error('已取消或条目已移除');const fields={publisher:detail.publisher,releaseDate:detail.date,genres:detail.genres,cover};item.fieldSources={...item.fieldSources};for(const [field,value]of Object.entries(fields))if(!item.lockedFields?.includes(field)&&(!item[field]||Array.isArray(item[field])&&!item[field].length)&&value){item[field]=value;item.fieldSources[field]=detail.source||'MusicBrainz';}if(!item.lockedFields?.includes('artists')&&!item.audio.artists.length)item.audio.artists=detail.artists||[];if(!item.lockedFields?.includes('albumArtists')&&!item.audio.albumArtists.length)item.audio.albumArtists=detail.artists||[];if(!item.lockedFields?.includes('edition')&&!item.audio.edition)item.audio.edition=detail.edition||'';if(detail.releaseId&&!item.audio.identifiers?.musicbrainzRelease)item.audio.identifiers={...item.audio.identifiers,musicbrainzRelease:detail.releaseId};for(const track of item.audio.tracks){const matches=(detail.tracks||[]).filter(t=>metadataMatch(track,t));if(matches.length===1){if(!track.lockedFields?.includes('artists')&&!track.artists.length)track.artists=matches[0].artists;if(!track.lockedFields?.includes('durationSeconds')&&!track.durationSeconds)track.durationSeconds=matches[0].duration;if(detail.provider==='musicbrainz'&&!track.identifiers?.musicbrainz)track.identifiers={...track.identifiers,musicbrainz:matches[0].id};}}if(!item.lockedFields?.includes('storeUrl')&&!item.storeUrl&&detail.storeUrl)item.storeUrl=detail.storeUrl;item.metadataSource=detail.source||'MusicBrainz';item.updatedAt=new Date().toISOString();candidates.delete(event.sender.id);return saveLibrary(lib);});
 function metadataMatch(a,b){return require('./audio-capabilities').mapTracks([a],[b])[0].status==='match';}
 ipcMain.handle('audio:searchTrack',async(event,itemId,trackId)=>{if(disguised()||!preferences().online)throw Error('请在设置中允许声音联网补全');const {item,track}=itemTrack(itemId,trackId);if(!track)throw Error('音轨不存在');const job=start(event.sender.id),result=await metadata.search({...item,name:track.title,audio:{...item.audio,artists:track.artists?.length?track.artists:item.audio.artists,collectionKind:'single'}},job.signal,preferences().chinese);job.signal.throwIfAborted();candidates.set(event.sender.id,{itemId,trackId,signature:JSON.stringify(track),items:result});return searchResult(result);});
 ipcMain.handle('audio:applyTrackMetadata',async(event,itemId,trackId,candidateId)=>{const bundle=candidates.get(event.sender.id),candidate=bundle?.itemId===itemId&&bundle.trackId===trackId&&bundle.items.find(v=>v.id===candidateId);if(!candidate||!preferences().online||disguised())throw Error('候选已失效');const job=start(event.sender.id),detail=await metadata.detail(candidate,job.signal),cover=await metadata.cover(detail,job.signal).catch(()=>''),lib=loadLibrary(),item=lib.items.find(i=>i.id===itemId),track=item?.audio?.tracks.find(t=>t.id===trackId);job.signal.throwIfAborted();if(!track||JSON.stringify(track)!==bundle.signature)throw Error('音轨已修改，请重新核对候选');if(!track.lockedFields?.includes('artists')&&!track.artists?.length)track.artists=detail.artists||[];if(!track.lockedFields?.includes('durationSeconds')&&!track.durationSeconds)track.durationSeconds=detail.duration||0;track.identifiers={...track.identifiers};if(detail.provider==='musicbrainz'&&detail.recordingId&&!track.identifiers.musicbrainz)track.identifiers.musicbrainz=detail.recordingId;if(!track.lockedFields?.includes('cover')&&!track.cover&&cover)track.cover=cover;track.metadataSource=detail.source;track.metadataConfirmed=true;return saveLibrary(lib);});
 ipcMain.handle('audio:completeLyrics',async(event,itemId,ids)=>{if(disguised()||!preferences().online)throw Error('请在设置中允许声音联网补全');const {item}=itemTrack(itemId);if(!Array.isArray(ids)||ids.length>1000||ids.some(id=>typeof id!=='string'))throw Error('音轨列表无效');const job=start(event.sender.id),entries=item.audio.tracks.filter(t=>ids.includes(t.id)).map(track=>({id:track.id,track,signature:JSON.stringify(track)}));return require('./lyrics-batch').run(entries,{signal:job.signal,existing:async e=>{const saved=read(lyricsFile(e.id),null);if(saved)return saved;if(e.track.lockedFields?.includes('lyrics')||item.lockedFields?.includes('lyrics'))return {locked:true};return require('./audio-local-lyrics').read(item,e.track);},query:(e,signal)=>metadata.lyrics(item,e.track,signal),valid:e=>{const live=loadLibrary().items.find(i=>i.id===itemId)?.audio?.tracks.find(t=>t.id===e.id);return live&&JSON.stringify(live)===e.signature;},write:(e,result)=>write(lyricsFile(e.id),result),onProgress:value=>{if(!event.sender.isDestroyed())event.sender.send('audio:completionProgress',value);}});});
 ipcMain.handle('audio:onlineLyrics',async(event,itemId,trackId,query)=>{if(!preferences().online)throw Error('声音联网已关闭');const {item,track}=itemTrack(itemId,trackId);if(!track)throw Error('音轨已不存在');const job=start(event.sender.id);const requested={...track,title:typeof query?.title==='string'?query.title.slice(0,300):track.title,artists:typeof query?.artist==='string'?[query.artist.slice(0,300)]:track.artists};return metadata.lyrics(item,requested,job.signal,query?.source,typeof query?.candidateId==='string'?query.candidateId.slice(0,100):undefined);});
 ipcMain.handle('audio:saveLyrics',(_,itemId,trackId,value)=>{const {track}=itemTrack(itemId,trackId);if(!track)throw Error('音轨已不存在');const text=String(value?.text||'');if(text.length>2*1024*1024)throw Error('歌词过大');const next={text,source:'用户选择',kind:text?'user':['instrumental','not-applicable'].includes(value?.kind)?value.kind:'none',offset:Math.max(-3600000,Math.min(3600000,Number(value?.offset)||0)),updatedAt:new Date().toISOString()};write(lyricsFile(trackId),next);return next;});
 ipcMain.handle('audio:pickLyrics',async event=>{const choice=await dialog.showOpenDialog(windowFor(event),{title:'选择歌词文件',properties:['openFile'],filters:[{name:'歌词',extensions:['lrc','txt']},{name:'所有文件',extensions:['*']}]});if(choice.canceled)return null;const file=choice.filePaths[0],stat=await fs.promises.stat(file);if(!stat.isFile()||stat.size>2*1024*1024)throw Error('请选择小于 2 MB 的歌词文件');return require('./lyrics-decoder').decode(await fs.promises.readFile(file));});
 ipcMain.handle('audio:connections',()=>remote.list());ipcMain.handle('audio:saveConnection',(_,v)=>remote.save(v));ipcMain.handle('audio:removeConnection',(_,id)=>remote.remove(id));
 ipcMain.handle('audio:testConnection',async(event,id)=>{const c=remote.connection(id),job=start(event.sender.id);return c.kind==='webdav'?remote.browse(id,'',job.signal):Net.probe(c.url,c.scope,job.signal);});
 ipcMain.handle('audio:browse',async(event,id,relative)=>{const job=start(event.sender.id);return remote.browse(id,String(relative||''),job.signal);});
 ipcMain.handle('audio:importRemote',async(event,id,paths,kind='music')=>{if(!Array.isArray(paths)||paths.length>5000||!['music','asmr','radio','other'].includes(kind))throw Error('远程导入参数无效');const job=start(event.sender.id),connection=remote.connection(id),files=[];let directories=0;const visited=new Set();
  async function walk(relative,depth){job.signal.throwIfAborted();if(visited.has(relative))return;visited.add(relative);if(depth>8||files.length>=5000||++directories>500)throw Error('所选目录过大，请选择更小的范围');for(const row of await remote.browse(id,relative,job.signal)){if(row.directory)await walk(row.relativePath,depth+1);else if(/\.(mp3|flac|wav|m4a|aac|ogg|opus|m3u8)$/i.test(row.name))files.push(row);}}
  if(connection.kind==='http'){const info=await Net.probe(connection.url,connection.scope,job.signal);files.push({relativePath:'',name:connection.name,mime:info.mime});}else for(const row of paths){if(row.directory)await walk(String(row.relativePath),0);else files.push({relativePath:String(row.relativePath),name:String(row.name||'远程音频'),mime:String(row.mime||'')});}
  const lib=loadLibrary(),groups=new Map();let added=0;for(const file of files){job.signal.throwIfAborted();remote.resolve({kind:connection.kind,connectionId:id,relativePath:file.relativePath});if(lib.items.some(i=>i.type==='audio'&&i.audio.sources.some(s=>s.connectionId===id&&(s.relativePath||'')===file.relativePath)))continue;
 const folder=connection.kind==='webdav'?file.relativePath.slice(0,file.relativePath.lastIndexOf('/')+1):'',groupKey=folder||file.relativePath||id;
 let item=groups.get(groupKey);if(!item){const folderName=folder?decodeURIComponent(folder.split('/').filter(Boolean).at(-1)):'';item={id:randomUUID(),type:'audio',name:folderName||file.name.replace(/\.(mp3|flac|wav|m4a|aac|ogg|opus|m3u8)$/i,''),status:'未听',audio:{kind,collectionKind:kind==='asmr'?'work':folder?'album':'single',sources:[],tracks:[]}};groups.set(groupKey,item);}
 const sid=randomUUID();item.audio.sources.push({id:sid,kind:connection.kind,connectionId:id,relativePath:file.relativePath,mimeType:file.mime});item.audio.tracks.push({id:randomUUID(),title:file.name.replace(/\.(mp3|flac|wav|m4a|aac|ogg|opus|m3u8)$/i,''),sourceRefs:[sid]});}
 for(const item of groups.values()){item.audio.tracks.sort((a,b)=>a.title.localeCompare(b.title,'zh',{numeric:true}));item.audio=Model.normalize(item.audio);lib.items.push(item);added++;}return {library:saveLibrary(lib),added};});

 return {lyricsService:{preferences,query:(item,track,signal,source,candidateId)=>metadata.lyrics(item,track,signal,source,candidateId),read:trackId=>read(lyricsFile(trackId),null),save:(trackId,result,options={})=>{const previous=read(lyricsFile(trackId),null);if(previous?.source==='用户选择'&&!options.replace)throw Error('已有用户手工歌词，在线结果不会覆盖');write(lyricsFile(trackId),{...result,...(options.replace?{source:'用户选择'}:{}),updatedAt:new Date().toISOString()});}},metadata,remote,userLyrics:trackId=>read(lyricsFile(trackId),null),stop(){for(const job of jobs.values())job.abort();jobs.clear();candidates.clear();},preferences};
}
module.exports={create};
