/* Theme-native dialogs for explicit metadata selection and read-only connections. */
(()=>{
 function dialog(title){const host=document.createElement('div');host.className='app-dialog-backdrop audio-dialog';host.innerHTML='<section class="app-dialog audio-full"><div class="app-dialog-head"><strong></strong><button class="audio-close" aria-label="关闭">×</button></div><div class="audio-dialog-body"></div><p class="audio-panel-status" role="status"></p></section>';host.querySelector('strong').textContent=title;appModalStack.open(host,()=>host.querySelector('.audio-close').click());let finish;const done=new Promise(resolve=>{finish=resolve;});const obj={done,host,body:host.querySelector('.audio-dialog-body'),status:host.querySelector('.audio-panel-status'),closed:false,close(){if(obj.closed)return;obj.closed=true;native.audioCancelExtras();appModalStack.remove(host);finish();}};host.querySelector('.audio-close').onclick=obj.close;host.oncontextmenu=e=>{if(e.target===host){e.preventDefault();obj.close();}};return obj;}
 async function consent(){const prefs=await native.audioPreferences();if(!prefs.online){showToast('请在设置中允许声音联网补全','error');return false;}return true;}
 let lookup=null;
 function cancelLookup(){const old=lookup;lookup=null;if(old){native.audioCancelExtras();old.resolve();$('metadataBtn').textContent='补全资料';}}
 function valid(job){return lookup===job&&(!job.fromEditor||(editorId===job.itemId&&$('fieldType').value==='audio'&&!$('editorBackdrop').classList.contains('hidden')&&$('fieldName').value===job.name));}
 async function metadata(itemId,fromEditor=false){window.audioCompletion?.stopBatch();
  if(lookup){cancelMetadataLookup();return;}const name=fromEditor?$('fieldName').value:state.items.find(i=>i.id===itemId)?.name;if(!name?.trim()){showToast('请先输入名称');return;}
  if(!await consent())return;if(fromEditor&&(editorId!==itemId||$('fieldType').value!=='audio'||$('editorBackdrop').classList.contains('hidden')||$('fieldName').value!==name))return;
  cancelMetadataLookup();let resolve;const done=new Promise(r=>resolve=r),job={itemId,fromEditor,name,resolve,busy:false};lookup=job;$('metadataBtn').textContent='停止获取';
  let failures=[],providerStates=[];
  const show=(rows=[],loading=false,message='请选择准确的发行版本，只补全缺失字段。')=>showCandidates({type:'audio',loading,integrated:rows,sources:[['qq','QQ 音乐'],['netease','网易云音乐'],['kugou','酷狗音乐'],['deezer','Deezer'],['musicbrainz','MusicBrainz']].map(([id,label])=>({id,label,state:loading?'loading':providerStates.find(v=>v.id===id)?.state||(rows.some(v=>v.provider===id)?'ok':'empty'),items:rows.filter(v=>v.provider===id),message:providerStates.find(v=>v.id===id)?.message||(failures.find(f=>f.source===label)?.message||message)}))});
  show([],true,'正在查询对应专辑或歌曲资料，可随时关闭。');
  try{const bundle=fromEditor?await native.audioSearchDraft({name,audio:window.audioEditor.value()}):await native.audioSearch(itemId);if(!valid(job))return;
   const rows=bundle.items;failures=bundle.failures||[];providerStates=bundle.providers||[];show(rows.map(row=>({...row,mediaType:'audio',developer:row.artists.join(' / '),releaseDate:row.date,storeRegion:row.country,storeSection:row.edition,metadataSource:row.source||'MusicBrainz',cover:row.cover||(/^[a-f\d-]{36}$/i.test(row.releaseId||'')?'https://coverartarchive.org/release/'+row.releaseId+'/front-250':'')})));$('metadataBtn').textContent='补全资料';
  }catch(e){if(valid(job)){show([],false,e.message);document.querySelector('.candidate-hint').textContent=e.message;$('metadataBtn').textContent='自动获取信息';}}
  return done;
 }
 async function chooseCandidate(row){const job=lookup;if(!job||job.busy||!valid(job))return;job.busy=true;document.querySelector('.candidate-hint').textContent='正在获取资料与封面…';
  try{if(job.fromEditor){const detail=await native.audioMetadataDetails(row.id);if(!valid(job))return;const mapping=window.audioCompletion?.mapTracks(window.audioEditor.value().tracks||[],detail.tracks||[]);if(detail.entityType==='album'&&mapping?.length){if(!await audioCompletion.confirmAlbum(mapping,detail))return;}window.audioEditor.mergeMetadata(detail);job.lyricsIds=detail.entityType==='track'&&audioEditor.value().tracks.length===1?[audioEditor.value().tracks[0].id]:mapping?.filter(m=>m.status==='match').map(m=>m.trackId)||[];
    for(const [id,value]of [['fieldPublisher',detail.publisher],['fieldReleaseDate',detail.date],['fieldGenres',(detail.genres||[]).join(', ')]])if(!state.items.find(i=>i.id===job.itemId)?.lockedFields?.includes({fieldPublisher:'publisher',fieldReleaseDate:'releaseDate',fieldGenres:'genres'}[id])&&!$(id).value.trim()&&value){$(id).value=value;const field={fieldPublisher:'publisher',fieldReleaseDate:'releaseDate',fieldGenres:'genres'}[id];editorMetadata.fieldSources={...editorMetadata.fieldSources,[field]:detail.source||'MusicBrainz'};}editorMetadata.metadataSource=detail.source||'MusicBrainz';if(!state.items.find(i=>i.id===job.itemId)?.lockedFields?.includes('storeUrl')&&!$('fieldStoreUrl').value&&detail.storeUrl){$('fieldStoreUrl').value=detail.storeUrl;updateLinkButtons();}
    const covers=getEditorCovers();if(!state.items.find(i=>i.id===job.itemId)?.lockedFields?.includes('cover')&&detail.cover&&!covers.cover&&!covers.coverPortrait&&!covers.coverLandscape){fillCoverFields({...covers,cover:detail.cover});editorMetadata.fieldSources={...editorMetadata.fieldSources,cover:detail.provider==='musicbrainz'?'Cover Art Archive':detail.source};updateCoverPreview(detail.cover);}
    updateEditorSaveCue(true,'audio-metadata');requestAnimationFrame(syncOverflowFields);
   }else{const detail=await native.audioMetadataDetails(row.id);if(!valid(job))return;const mapping=audioCompletion.mapTracks(state.items.find(i=>i.id===job.itemId)?.audio?.tracks||[],detail.tracks||[]);if(detail.entityType==='album'&&mapping.length&&!await audioCompletion.confirmAlbum(mapping,detail))return;job.lyricsIds=detail.entityType==='track'&&state.items.find(i=>i.id===job.itemId)?.audio?.tracks.length===1?[state.items.find(i=>i.id===job.itemId).audio.tracks[0].id]:mapping.filter(m=>m.status==='match').map(m=>m.trackId);const saved=await native.audioApplyMetadata(job.itemId,row.id);if(!valid(job))return;state=saved;render();}
   const pendingIds=job.lyricsIds;cancelMetadataLookup();if(pendingIds?.length){if(job.fromEditor)audioCompletion.defer(job.itemId,pendingIds);else audioCompletion.lyrics(job.itemId,pendingIds);}
  }catch(e){if(valid(job))document.querySelector('.candidate-hint').textContent=e.message;}finally{job.busy=false;}
 }
 async function lyrics(itemId,trackId){const item=state.items.find(i=>i.id===itemId),track=item?.audio?.tracks.find(t=>t.id===trackId);return openAudioLyrics({itemId,trackId,title:track?.title||'',artist:track?.artists?.[0]||item?.audio?.artists?.[0]||'',api:{lyrics:native.audioLyrics,onlineLyrics:native.audioOnlineLyrics,saveLyrics:native.audioSaveLyrics,pickLyrics:native.audioPickLyrics,cancelLyrics:native.audioCancelExtras},onSave:()=>window.audioPlayer.reloadLyrics()});}
 async function remote(){const d=dialog('远程声音收藏');d.body.innerHTML='<p class="audio-help">只读浏览和播放，不上传资源库、设置或存档。没有音频缓存时，离线不能播放。</p><div class="audio-connection-list"></div><details class="audio-new-connection"><summary>添加连接 / 更新链接</summary><div class="field-row"><label class="field">连接类型<select class="connection-kind"><option value="webdav">只读 WebDAV</option><option value="http">HTTP(S) 直链 / HLS</option></select></label><label class="field">名称<input class="connection-name"></label></div><label class="field">服务器音频根目录或完整音频地址<input class="connection-url" placeholder="https://服务器/dav/" autocomplete="off"></label><div class="field-row"><label class="field">用户名<input class="connection-user" autocomplete="off"></label><label class="field">密码<input class="connection-password" type="password" autocomplete="new-password"></label></div><label class="field">额外授权 CDN 源（可选，逗号分隔）<input class="connection-origins" placeholder="https://cdn.example.com"></label><p class="audio-help">HTTP 不加密连接。认证仅发送到主服务器，不转发到 CDN。签名过期后请在此更新链接。</p><button class="add-button connection-save">保存并测试连接</button></details><div class="audio-full-controls"><button class="remote-up">上一级</button><button class="remote-refresh">刷新目录</button><span class="remote-path"></span><label>类型<select class="remote-kind"><option value="music">音乐</option><option value="asmr">ASMR / 音声</option><option value="radio">电台</option><option value="other">其他音频</option></select></label><button class="add-button remote-import">导入所选</button></div><div class="remote-entries"></div>';let active=null,current='',entries=[],editingId='';const listing=d.body.querySelector('.audio-connection-list'),entryHost=d.body.querySelector('.remote-entries');
  async function browse(relative=''){if(!active)return;d.status.textContent='正在只读浏览…';try{if(active.kind==='http'){await native.audioTestConnection(active.id);entries=[];entryHost.textContent='直链连接已选择，点击“导入所选”探测并添加。';d.status.textContent='不会自动下载音频';return;}entries=await native.audioBrowse(active.id,relative);if(d.closed)return;current=relative;d.body.querySelector('.remote-path').textContent=decodeURIComponent(relative)||'/';entryHost.replaceChildren();entries.forEach((row,index)=>{if(!row.directory&&!/\.(mp3|flac|wav|m4a|aac|ogg|opus|m3u8)$/i.test(row.name))return;const label=document.createElement('div');label.className='remote-entry';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.dataset.index=index;const button=document.createElement('button');button.textContent=(row.directory?'▱ ':'♪ ')+row.name;button.onclick=()=>row.directory?browse(row.relativePath):checkbox.checked=!checkbox.checked;label.append(checkbox,button);entryHost.append(label);});d.status.textContent=entries.length+' 个目录项；选择需要索引的文件或目录。';}catch(e){if(!d.closed)d.status.textContent='远程不可用：'+e.message+'。已有收藏仍保留。';}}
  async function connections(){listing.replaceChildren();for(const c of await native.audioConnections()){const row=document.createElement('div');row.className='audio-full-controls';const button=document.createElement('button');button.textContent=c.name+' · '+(c.kind==='webdav'?'WebDAV':'直链');button.onclick=()=>{active=c;browse('');};const edit=document.createElement('button');edit.textContent='更新';edit.onclick=()=>{editingId=c.id;d.body.querySelector('details').open=true;d.body.querySelector('.connection-kind').value=c.kind;d.body.querySelector('.connection-name').value=c.name;d.body.querySelector('.connection-url').value=c.base;d.status.textContent='请重新输入完整地址与凭据，原加密密码不会回显。';};const remove=document.createElement('button');remove.textContent='移除连接';remove.onclick=async()=>{await native.audioRemoveConnection(c.id);if(active?.id===c.id){active=null;entryHost.replaceChildren();}await connections();d.status.textContent='连接已移除，收藏条目仍保留；重新配置后可重新定位来源。';};row.append(button,edit,remove);listing.append(row);}}
  d.body.querySelector('.connection-save').onclick=async()=>{try{const get=cls=>d.body.querySelector('.'+cls).value;active=await native.audioSaveConnection({id:editingId||undefined,kind:get('connection-kind'),name:get('connection-name'),url:get('connection-url'),username:get('connection-user'),password:get('connection-password'),origins:get('connection-origins').split(',').map(s=>s.trim()).filter(Boolean)});d.body.querySelector('.connection-password').value='';editingId='';await connections();await browse('');}catch(e){d.status.textContent=e.message;}};d.body.querySelector('.remote-refresh').onclick=()=>browse(current);d.body.querySelector('.remote-up').onclick=()=>browse(current.replace(/[^/]+\/$/,'').replace(/[^/]+$/,''));d.body.querySelector('.remote-import').onclick=async()=>{if(!active)return;const rows=[...entryHost.querySelectorAll('input:checked')].map(e=>entries[Number(e.dataset.index)]);d.status.textContent='正在检查并导入所选音频…';try{const result=await native.audioImportRemote(active.id,rows,d.body.querySelector('.remote-kind').value);if(d.closed)return;state=result.library;render();d.status.textContent='导入完成：新增 '+result.added+'，已有来源已跳过。';}catch(e){d.status.textContent=e.message;}};await connections();}

 async function relocate(source,changed){const d=dialog('重新定位远程来源');d.body.innerHTML='<p>选择已配置的连接。原音轨 ID、资料与进度保持不变。</p><label class="field">连接<select class="relocate-connection"></select></label><label class="field">根目录下的相对路径<input class="relocate-relative"></label><button class="add-button">应用到当前条目</button>';const select=d.body.querySelector('select'),relative=d.body.querySelector('input');const rows=(await native.audioConnections()).filter(c=>c.kind===source.kind);for(const c of rows){const o=document.createElement('option');o.value=c.id;o.textContent=c.name;select.append(o);}select.value=rows.some(c=>c.id===source.connectionId)?source.connectionId:rows[0]?.id||'';relative.value=source.relativePath||'';relative.closest('label').classList.toggle('hidden',source.kind!=='webdav');d.body.querySelector('button').onclick=()=>{if(!select.value){d.status.textContent='请先在远程音频库中配置连接';return;}source.connectionId=select.value;if(source.kind==='webdav')source.relativePath=relative.value;delete source.url;changed();d.close();};}
 window.audioPanels={metadata,cancelLookup,hasLookup:()=>Boolean(lookup),chooseCandidate,lyrics,remote,relocate};
})();
