/* Shared presentation hosted by the originating window, no audio engine. */
window.openAudioLyrics=async({itemId,trackId,title='',artist='',api,onSave=()=>{}})=>{
 const host=document.createElement('div');host.className='app-dialog-backdrop audio-dialog';
 host.innerHTML='<section class="app-dialog audio-full"><div class="app-dialog-head"><strong>歌词与时间偏移</strong><button class="audio-close" aria-label="关闭">×</button></div><div class="audio-dialog-body"><div class="field-row"><label class="field">歌曲名称<input class="lyrics-title"></label><label class="field">艺术家<input class="lyrics-artist"></label></div><div class="audio-full-controls"><select class="lyrics-source"><option value="auto">自动选择</option><option value="lrclib">LRCLIB</option><option value="netease">网易云音乐</option><option value="ovh">lyrics.ovh</option></select><button data-action="local">选择本地歌词</button><button data-action="online">联网查询歌词</button><label>偏移（毫秒）<input class="lyrics-offset" type="number" min="-3600000" max="3600000" step="100" value="0"></label></div><textarea class="lyrics-editor" rows="10" aria-label="歌词文本"></textarea><button class="add-button lyrics-save">保存所选歌词</button></div><p class="audio-panel-status" role="status"></p></section>';
 document.body.append(host);const q=s=>host.querySelector(s),status=q('.audio-panel-status'),input=q('.lyrics-editor');q('.lyrics-title').value=title;q('.lyrics-artist').value=artist;let closed=false,kind='user',ticket=0,candidateId;const versions=document.createElement('select');versions.className='lyrics-versions';versions.hidden=true;q('.audio-dialog-body').prepend(versions);for(const field of ['.lyrics-title','.lyrics-artist','.lyrics-source'])q(field).addEventListener('change',()=>{candidateId=undefined;versions.hidden=true;});versions.onchange=()=>{candidateId=versions.value;q('[data-action=online]').click();};
 const close=()=>{closed=true;ticket++;api.cancelLyrics();host.remove();};q('.audio-close').onclick=close;host.oncontextmenu=e=>{if(e.target===host){e.preventDefault();close();}};host.onkeydown=e=>{if(e.key==='Escape'){e.stopPropagation();close();}};
 try{const old=await api.lyrics(itemId,trackId);if(!closed){input.value=old.text||'';q('.lyrics-offset').value=old.offset||0;kind=old.kind;}}catch(e){status.textContent=e.message;}
 q('[data-action=local]').onclick=async()=>{try{const text=await api.pickLyrics();if(!closed&&text!=null){input.value=text;kind='user';}}catch(e){status.textContent=e.message;}};
 q('[data-action=online]').onclick=async()=>{const id=++ticket;status.textContent='正在按歌曲名称查询歌词…';try{const r=await api.onlineLyrics(itemId,trackId,{title:q('.lyrics-title').value,artist:q('.lyrics-artist').value,source:q('.lyrics-source').value,candidateId});if(closed||id!==ticket)return;if(r.choices?.length){versions.replaceChildren();const hint=document.createElement('option');hint.textContent='请选择准确的发行版本';hint.value='';versions.append(hint);for(const row of r.choices){const o=document.createElement('option');o.value=row.id;o.textContent=row.title+' · '+row.album+' · '+Math.round(row.duration)+'秒';versions.append(o);}versions.hidden=false;status.textContent='有多个同名版本，请选择后查询';return;}versions.hidden=true;input.value=r.text||'';kind=r.kind;status.textContent=r.mismatch?'版本或时长待核对，请确认再保存':(r.source?r.source+' · ':'')+(r.kind==='none'?'未找到歌词':r.kind==='not-applicable'?'此类声音不自动匹配歌曲歌词':r.kind==='instrumental'?'纯音乐':'已找到歌词，保存后使用');}catch(e){if(!closed&&id===ticket)status.textContent=e.message;}};
 q('.lyrics-save').onclick=async()=>{try{await api.saveLyrics(itemId,trackId,{text:input.value,offset:Number(q('.lyrics-offset').value),kind});if(!closed){onSave();close();}}catch(e){status.textContent=e.message;}};
};
