/* One player surface. It owns listeners, object URLs, decoding engines and progress. */
let mediaSession=null,mediaEpoch=0,mediaOpenIntent=0,mediaClosing=Promise.resolve();
const mediaScripts=new Map();
function mediaScript(src){if(mediaScripts.has(src))return mediaScripts.get(src);const promise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>{mediaScripts.delete(src);reject(Error('播放组件加载失败，请检查安装文件是否完整'));};document.head.appendChild(s);});mediaScripts.set(src,promise);return promise;}
const mediaTime=v=>{const n=Math.max(0,Math.floor(Number(v)||0));return (n>=3600?Math.floor(n/3600)+':':'')+String(Math.floor(n/60)%60).padStart(2,'0')+':'+String(n%60).padStart(2,'0');};
function readerMessage(session,text,error=false){if(mediaSession!==session)return;const el=$('readerMessage');el.textContent=text;el.classList.toggle('is-error',error);el.classList.toggle('hidden',!text);}
async function persistReader(session){if(!session?.data||session.data.launched)return;session.controller?.capture?.();const value={...session.progress,member:readerFileKey(session.file),options:session.options,positions:session.positions,bookmarks:session.bookmarks,annotationSchema:session.annotationSchema||0,kind:session.data.type};try{await native.saveReaderProgress(session.data.id,value);await native.readerPreferences?.(session.data.type,session.options);return true;}catch(error){if(mediaSession===session)readerMessage(session,'阅读进度未能保存：'+error.message,true);return false;}}
async function closeMedia(keepIntent=false){if(!keepIntent)++mediaOpenIntent;const session=mediaSession;if(!session)return mediaClosing;const backdrop=$('readerBackdrop');session.loadAbort?.abort();session.prefetch?.controller.abort();session.prefetch=null;session.wheelOff?.();session.controller?.capture?.();mediaSession=null;++mediaEpoch;clearInterval(session.timer);try{session.controller?.dispose?.();}catch(error){console.warn('阅读组件释放失败',error.message);}session.keyOff?.();mediaClosing=(async()=>{await persistReader({...session,controller:null});await native.closeReader?.();if(document.fullscreenElement?.closest?.('#readerBackdrop'))await document.exitFullscreen().catch(()=>{});backdrop?.remove();document.body.classList.remove('reader-is-immersive');})();return mediaClosing;}
async function openMedia(id){
 if(native.launchReader&&!window.UNIFIED_READER_WINDOW){try{const result=await native.launchReader(id);await native.usageOpened?.(id);if(typeof refreshUsage==='function')await refreshUsage();return result;}catch(e){showToast(e.message,'error');return;}}
 const intent=++mediaOpenIntent;await closeMedia(true);if(intent!==mediaOpenIntent)return;const epoch=++mediaEpoch,session={epoch,data:null,options:{},positions:{},bookmarks:[]};mediaSession=session;
 const backdrop=document.createElement('div');backdrop.className='reader-backdrop';backdrop.id='readerBackdrop';backdrop.innerHTML='<section class="reader-shell"><header class="reader-header"><button id="readerBack" class="secondary-button" type="button">← 返回资源库</button><strong id="readerTitle">正在打开…</strong><button type="button" class="secondary-button" id="readerFullscreen" title="沉浸（F，Esc退出）">沉浸</button></header><div id="readerMessage" class="reader-message" role="status">正在读取本地资源…</div><div class="reader-layout"><aside id="readerContents"></aside><main class="reader-main"><div id="readerToolbar"></div><div id="readerViewport"></div><div id="readerControls"></div></main></div><footer class="reader-footer"><span id="readerPosition"></span><button type="button" class="text-button" id="readerBookmark">☆ 添加书签</button><button type="button" class="text-button" id="readerOpenExternal">用系统应用打开</button></footer></section>';document.body.appendChild(backdrop);const contentsToggle=document.createElement('button');contentsToggle.type='button';contentsToggle.className='secondary-button';contentsToggle.textContent='目录';contentsToggle.setAttribute('aria-expanded','true');contentsToggle.onclick=()=>{const hidden=backdrop.querySelector('.reader-layout').classList.toggle('contents-collapsed');contentsToggle.setAttribute('aria-expanded',String(!hidden));requestAnimationFrame(()=>session.controller?.resize?.());};$('readerFullscreen').before(contentsToggle);
 $('readerBack').onclick=()=>window.UNIFIED_READER_WINDOW?native.close():closeMedia();if(window.UNIFIED_READER_WINDOW)$('readerBack').textContent='关闭阅读窗口';$('readerFullscreen').onclick=()=>readerFullscreen();
 $('readerBookmark').onclick=async()=>{const controller=session.controller;controller?.capture?.();const position=structuredClone(session.positions[readerFileKey(session.file)]||{}),page=controller?.currentPage?.(),text=(await controller?.text?.()||'').trim().split(/\r?\n/).find(line=>line.trim())?.trim().replace(/\s+/g,' ').slice(0,24)||'';if(mediaSession!==session||controller!==session.controller)return;const mark={member:readerFileKey(session.file),position,label:(text||'书签')+(page?' · 第 '+page+' 页':'')};session.bookmarks.push(mark);readerNotice('书签已添加');renderReaderContents(session);persistReader(session);};
 $('readerOpenExternal').onclick=()=>{if(session.file?.path)native.openExternal(session.file.path);};
 try{const data=await native.openReader(id);if(mediaSession!==session)return;if(data.launched){mediaSession=null;backdrop.remove();return;}session.data=data;await native.readerSetActive?.(data.id);session.progress=data.progress||{};session.options={theme:settings.appearance?.theme==='paper'?'light':'dark',font:18,lineHeight:1.9,flow:'page',comicMode:'single',direction:'ltr',fit:'height',zoom:1,...session.progress.options,...await native.readerPreferences?.(data.type)};session.positions=session.progress.positions||{};session.bookmarks=session.progress.bookmarks||[];initialiseReaderAnnotations(session);
  $('readerTitle').textContent=data.name;installReaderTabs(session);session.index=Math.max(0,data.files.findIndex(f=>readerFileKey(f)===session.progress.member));native.usageOpened?.(id).catch(()=>{});session.timer=setInterval(()=>{persistReader(session);const video=$('readerViewport')?.querySelector('video');if(!window.UNIFIED_READER_WINDOW&&(video?!video.paused&&!video.ended&&video.readyState>=2:document.hasFocus()&&!document.hidden))native.usageTick?.(id,5).catch(()=>{});},5000);await loadReaderFile(session,session.index);if(mediaSession!==session)return;if(data.warnings?.length)readerMessage(session,data.warnings.join('；'));
  const key=event=>{if(mediaSession!==session||event.target.closest?.('input,textarea,select,[role=slider],[contenteditable],.reader-settings-dialog'))return;if(event.key==='Escape'&&backdrop.classList.contains('reader-immersive')){event.preventDefault();backdrop.classList.remove('reader-immersive');document.body.classList.remove('reader-is-immersive');session.controller?.resize?.();return;}if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();document.fullscreenElement?document.exitFullscreen():window.UNIFIED_READER_WINDOW?native.close():closeMedia();return;}if(event.key.toLowerCase()==='f'){event.preventDefault();event.stopImmediatePropagation();readerFullscreen();return;}session.controller?.key?.(event);};document.addEventListener('keydown',key,true);session.keyOff=()=>document.removeEventListener('keydown',key,true);
 }catch(error){if(mediaSession===session){readerMessage(session,error.message,true);$('readerTitle').textContent='无法打开资源';$('readerViewport').innerHTML='<div class="reader-empty">请返回条目检查本地路径，或选择受支持的资源文件。</div>';$('readerBookmark').disabled=true;}}
}
document.addEventListener('fullscreenchange',()=>requestAnimationFrame(()=>mediaSession?.controller?.resize?.()));
function readerFullscreen(){const shell=$('readerBackdrop');if(!shell)return;const on=shell.classList.toggle('reader-immersive');document.body.classList.toggle('reader-is-immersive',on);requestAnimationFrame(()=>mediaSession?.controller?.resize?.());return Promise.resolve();}
function renderReaderContents(session,toc=session.toc||[]){session.toc=toc;const host=$('readerContents');host.replaceChildren();if(!renderReaderAnnotationTabs(session,host))return;const heading=document.createElement('h3');heading.textContent=['movie','anime'].includes(session.data.type)?'季 / 集':'';if(heading.textContent)host.appendChild(heading);
 let activeContents=host;const thumbs=session.controller?.thumbnails?.(),visual=!!thumbs,groups=new Map();
 session.data.files.forEach((file,index)=>{const image=LocalModel.images.test('.'+file.format),key=image?(file.key?.includes('#entry=')?file.path:String(file.path||'').replace(/[/\\\\][^/\\\\]+$/,'')):readerFileKey(file);if(!groups.has(key))groups.set(key,{key,file,index,image,indices:[]});groups.get(key).indices.push(index);});
 for(const {key,file,index,image,indices}of groups.values()){
 if(['movie','anime'].includes(session.data.type)){const b=document.createElement('button');b.textContent=file.name;b.onclick=()=>loadReaderFile(session,index);host.append(b);continue;}
 const group=document.createElement('details'),summary=document.createElement('summary');group.className='reader-chapter-group reader-volume';summary.textContent=image?(String(key).split(/[/\\\\]/).pop()||session.data.name):file.name;group.append(summary);group.open=session.options.volumeExpanded?.[key]===true;host.append(group);
 group.ontoggle=()=>{if(group.open===(session.options.volumeExpanded?.[key]===true))return;session.options.volumeExpanded??={};session.options.volumeExpanded[key]=group.open;if(group.open&&!image&&index!==session.index){loadReaderFile(session,index);return;}persistReader(session);};
 if(indices.includes(session.index))activeContents=group;
 const pages=image&&thumbs?indices.map(i=>thumbs[i]).filter(Boolean):index===session.index?thumbs:null;
 if(pages){const grid=document.createElement('div');grid.className='reader-thumbnails reader-volume-thumbnails';let populated=false;const populate=()=>{if(populated||!group.open)return;populated=true;for(const [ordinal,item]of pages.entries()){const button=document.createElement('button'),img=document.createElement('img'),number=document.createElement('span');button.type='button';button.title='第 '+(ordinal+1)+' 页';img.loading='lazy';img.alt='';number.textContent=ordinal+1;button.append(img,number);grid.append(button);button.onclick=()=>Promise.resolve(item.open()).catch(e=>readerNotice(e.message));if(item.url)img.src=item.url;else if(item.load){const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){observer.disconnect();item.load().then(url=>{if(img.isConnected)img.src=url;}).catch(()=>img.alt='预览不可用');}},{root:host,rootMargin:'80px'});observer.observe(img);session.loadAbort.signal.addEventListener('abort',()=>observer.disconnect(),{once:true});}}};group.addEventListener('toggle',populate);group.append(grid);populate();}
 }
 const chapters=(rows,parent)=>{for(const chapter of rows){const b=document.createElement('button');b.type='button';b.className='reader-chapter';b.textContent=chapter.label;b.onclick=chapter.open;if(chapter.children?.length){const group=document.createElement('details'),summary=document.createElement('summary');group.className='reader-chapter-group';const title=document.createElement('span');title.textContent=chapter.label;title.tabIndex=0;title.setAttribute('role','button');title.title='跳转本卷；左侧箭头展开或收起';title.onclick=event=>{event.preventDefault();chapter.open?.();};title.onkeydown=event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();event.stopPropagation();chapter.open?.();}};summary.append(title);summary.className='reader-chapter-heading';group.open=session.options.tocExpanded?.[chapter.href||chapter.label]===true;group.ontoggle=()=>{session.options.tocExpanded??={};session.options.tocExpanded[chapter.href||chapter.label]=group.open;persistReader(session);};group.append(summary);chapters(chapter.children,group);parent.append(group);}else parent.append(b);}};if(!visual||session.file.format==='pdf')chapters(toc,activeContents);

}
async function loadReaderFile(session,index,positionRestored=false){
 if(mediaSession!==session||index<0||index>=session.data.files.length)return;session.loadAbort?.abort();session.loadAbort=new AbortController();if(!positionRestored)session.controller?.capture?.();try{session.controller?.dispose?.();}catch(error){console.warn('阅读组件释放失败',error.message);}session.wheelOff?.();session.controller=null;const serial=session.loadSerial=(session.loadSerial||0)+1;session.index=index;session.file=session.data.files[index];session.toc=[];$('readerViewport').className='reader-viewport';$('readerViewport').replaceChildren();$('readerControls').replaceChildren();$('readerToolbar').replaceChildren();$('readerToolbar').className='';readerMessage(session,'正在加载…');renderReaderContents(session);
 const loadSignal=session.loadAbort.signal;const valid=()=>mediaSession===session&&session.loadSerial===serial&&!loadSignal.aborted;
 try{const ext=session.file.format;const controller=['movie','anime'].includes(session.data.type)?await createVideoEngine(session,valid):['manga','document','unknown_collection'].includes(session.data.type)&&LocalModel.images.test('.'+ext)?await createComicEngine(session,valid):await createBookEngine(session,valid);if(!valid()){controller?.dispose?.();return;}session.controller=controller;installReaderWorkbench(session);if(session.prefetch?.key===readerFileKey(session.file)){session.prefetch.controller.abort();session.prefetch=null;}session.wheelOff=installReaderWheel(session,$('readerViewport'));persistReader(session);}catch(error){if(valid()){readerMessage(session,error.message,true);$('readerViewport').innerHTML='<div class="reader-empty">无法读取当前文件。可从左侧切换其他资源，或使用系统应用打开。</div>';}}
}
function subtitleVtt(text){const source=String(text).replace(/^\ufeff/,'').replace(/\r\n/g,'\n');return /^WEBVTT/.test(source)?source:'WEBVTT\n\n'+source.replace(/^(\d+)\s*\n(?=\d{1,2}:\d{2})/gm,'').replace(/(\d{1,2}:\d{2}:\d{2}),(\d{3})/g,'$1.$2');}
function shiftedSubtitles(text,offset){const source=subtitleVtt(text);if(!offset)return source;const seconds=t=>t.split(':').reduce((sum,v)=>sum*60+Number(v),0),stamp=t=>{const n=Math.max(0,t);return String(Math.floor(n/3600)).padStart(2,'0')+':'+String(Math.floor(n/60)%60).padStart(2,'0')+':'+(n%60).toFixed(3).padStart(6,'0');};return source.split(/\n\s*\n/).filter(block=>{const times=block.match(/([\d:.]+)\s*-->\s*([\d:.]+)/);return !times||seconds(times[2])>offset;}).map(block=>block.replace(/([\d:.]+)\s*-->\s*([\d:.]+)/,(m,a,b)=>stamp(seconds(a)-offset)+' --> '+stamp(seconds(b)-offset))).join('\n\n');}
async function createVideoEngine(session,valid){
 const video=document.createElement('video');video.playsInline=true;video.preload='metadata';video.className='unified-video';$('readerViewport').appendChild(video);
 $('readerControls').innerHTML='<div class="video-timeline"><span id="videoElapsed">00:00</span><input id="videoSeek" type="range" min="0" max="1000" value="0" aria-label="播放进度"><span id="videoDuration">00:00</span></div><div class="video-buttons"><button id="videoPrevious" title="上一集">上一集</button><button id="videoPlay" title="播放 / 暂停（空格）">▶ 播放</button><button id="videoNext" title="下一集">下一集</button><button id="videoMute" title="静音（M）">音量</button><input id="videoVolume" type="range" min="0" max="1" step=".05" aria-label="音量"><select id="videoRate" aria-label="播放速度">'+[.5,.75,1,1.25,1.5,2,3].map(v=>'<option value="'+v+'">'+v+'×</option>').join('')+'</select><button id="videoSubtitle">外挂字幕</button><button id="videoPip">画中画</button><label><input id="videoAuto" type="checkbox" checked>自动连播</label></div>';
 const updateControls=()=>{if(valid())PlaybackControls.update($('readerControls'),{paused:video.paused,muted:video.muted,volume:video.volume,video:true});};video.addEventListener('volumechange',updateControls);updateControls();
 const previous=session.positions[readerFileKey(session.file)]||{},urls=[];let hls=null,dash=null,disposed=false;video.volume=session.options.volume??.8;video.playbackRate=session.options.rate||1;$('videoVolume').value=video.volume;$('videoRate').value=video.playbackRate;$('videoAuto').checked=session.options.autoNext!==false;$('videoAuto').onchange=()=>session.options.autoNext=$('videoAuto').checked;
 const play=()=>video.paused?video.play().catch(error=>readerMessage(session,'请点击播放；若仍失败，可能是编码不受支持：'+error.message,true)):video.pause();
 $('videoPlay').onclick=play;$('videoMute').onclick=()=>{video.muted=!video.muted;PlaybackControls.update($('readerControls'),{paused:video.paused,muted:video.muted,volume:video.volume,video:true});};$('videoVolume').oninput=e=>{video.volume=Number(e.target.value);video.muted=false;session.options.volume=video.volume;};$('videoRate').onchange=e=>{video.playbackRate=Number(e.target.value);session.options.rate=video.playbackRate;};
 let subtitle=null,compatible=null,offset=0,converting=false,compatibilityTried=false,seekTimer=null;const duration=()=>compatible?.duration||video.duration,time=()=>offset+(video.currentTime||0);
 const seek=target=>{const t=Math.max(0,Math.min(Number.isFinite(duration())?duration()-.1:Infinity,target));if(compatible){offset=t;video.src=compatible.url+'?start='+t;video.load();}else video.currentTime=t;};
 $('videoSeek').oninput=e=>{const target=Number(e.target.value)/1000*duration();if(!Number.isFinite(target))return;if(compatible){clearTimeout(seekTimer);seekTimer=setTimeout(()=>seek(target),140);}else seek(target);};$('videoPrevious').disabled=session.index===0;$('videoNext').disabled=session.index===session.data.files.length-1;
 $('videoPrevious').onclick=()=>loadReaderFile(session,session.index-1);$('videoNext').onclick=()=>loadReaderFile(session,session.index+1);
 $('videoPip').disabled=!document.pictureInPictureEnabled;$('videoPip').onclick=()=>video.requestPictureInPicture().catch(error=>readerMessage(session,'画中画暂不可用：'+error.message,true));
 const applySubtitle=()=>{if(!subtitle||!valid())return;const url=URL.createObjectURL(new Blob([shiftedSubtitles(subtitle.text,offset)],{type:'text/vtt'}));urls.push(url);video.querySelectorAll('track').forEach(t=>t.remove());const track=document.createElement('track');track.kind='subtitles';track.label=subtitle.name;track.src=url;track.default=true;video.appendChild(track);track.onload=()=>{if(track.track)track.track.mode='showing';};};
 $('videoSubtitle').onclick=async()=>{try{const result=await native.pickSubtitle();if(!result||!valid())return;subtitle=result;applySubtitle();}catch(error){readerMessage(session,error.message,true);}};
 video.addEventListener('loadedmetadata',()=>{if(!valid())return;applySubtitle();if(!compatible&&previous.time>0&&previous.time<video.duration-2)video.currentTime=previous.time;$('videoDuration').textContent=Number.isFinite(duration())?mediaTime(duration()):'直播';readerMessage(session,'');video.play().catch(()=>{});});
 video.addEventListener('timeupdate',()=>{if(!valid())return;$('videoElapsed').textContent=mediaTime(time());$('videoSeek').value=Number.isFinite(duration())?time()/duration()*1000:0;$('readerPosition').textContent=session.file.name+' · '+mediaTime(time())+(compatible?' · 兼容解码':'');});
 const unlistenAudioPause=native.onMediaPause?.(kind=>{if(kind==='video')video.pause();});
 video.addEventListener('play',()=>{native.notifyMediaPlaying?.('video');if(valid())PlaybackControls.update($('readerControls'),{paused:false,muted:video.muted,volume:video.volume,video:true});});video.addEventListener('pause',()=>{if(valid()){PlaybackControls.update($('readerControls'),{paused:true,muted:video.muted,volume:video.volume,video:true});persistReader(session);}});
 video.addEventListener('waiting',()=>readerMessage(session,'正在缓冲…'));video.addEventListener('playing',()=>readerMessage(session,''));
 video.addEventListener('error',async()=>{if(disposed||!valid()||converting)return;if(compatibilityTried||!session.file.url.startsWith('um-media:')||!native.compatibleVideo){readerMessage(session,'无法播放：文件可能损坏、加密，或编码 / 网络不受支持。可用系统应用打开。',true);return;}compatibilityTried=true;converting=true;readerMessage(session,'正在启用兼容解码，可随时关闭窗口或切换资源；原文件不会改动…');try{const info=await native.compatibleVideo(session.file.url);if(!valid()||disposed)return;compatible=info;seek(previous.time||0);}catch(e){if(valid())readerMessage(session,'兼容播放失败：'+e.message,true);}finally{converting=false;}});
 video.addEventListener('ended',()=>{if(valid()&&$('videoAuto').checked&&session.index+1<session.data.files.length)loadReaderFile(session,session.index+1);});
 const ext=session.file.format,url=session.file.url;
 if(ext==='m3u8'&&!video.canPlayType('application/vnd.apple.mpegurl')){await mediaScript('vendor/hls.min.js');if(!valid())return {dispose(){}};if(!Hls.isSupported())throw Error('当前内核不支持 HLS MediaSource');hls=new Hls({enableWorker:true});hls.on(Hls.Events.ERROR,(_,data)=>{if(data.fatal&&valid())readerMessage(session,'HLS 播放失败：请检查网络、跨域权限或视频编码。',true);});hls.loadSource(url);hls.attachMedia(video);}
 else if(ext==='mpd'){await mediaScript('vendor/dash.all.min.js');if(!valid())return {dispose(){}};dash=dashjs.MediaPlayer().create();dash.initialize(video,url,true);dash.on('error',()=>{if(valid())readerMessage(session,'DASH 播放失败：请检查网络、跨域权限或视频编码。',true);});}
 else if(url.startsWith('um-media:')&&native.compatibleVideo){try{const info=await native.compatibleVideo(url);if(!valid())return {dispose(){}};if(info.videoCodec==='hevc'||['avi','wmv','flv','mpg','mpeg','vob','m2ts','mts','ts'].includes(ext)||info.audioCodec&&!['aac','mp3','opus','vorbis','flac'].includes(info.audioCodec)){compatible=info;compatibilityTried=true;video.dataset.compatibility='true';seek(previous.time||0);}else video.src=url;}catch(e){if(valid())video.src=url;}}
 else video.src=url;
 return {capture(){if(video.readyState>0)session.positions[readerFileKey(session.file)]={time:time(),duration:Number.isFinite(duration())?duration():0};},key(event){if(event.code==='Space'){event.preventDefault();play();}else if(['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();seek(time()+(event.key==='ArrowRight'?5:-5));}else if(['ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();video.volume=Math.max(0,Math.min(1,video.volume+(event.key==='ArrowUp' ? .05 : -.05)));$('videoVolume').value=video.volume;}else if(event.key.toLowerCase()==='m')$('videoMute').click();},dispose(){unlistenAudioPause?.();disposed=true;clearTimeout(seekTimer);hls?.destroy();dash?.reset();video.pause();video.removeAttribute('src');video.load();native.stopCompatibleVideo?.();urls.forEach(u=>URL.revokeObjectURL(u));}};
}
window.addEventListener('beforeunload',event=>{const session=mediaSession;if(!session||session.closing)return;session.closing=true;event.preventDefault();event.returnValue=false;persistReader(session).finally(()=>native.close());});
