const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('unifiedAPI', {
  cacheSize:()=>ipcRenderer.invoke('cache:size'),clearNetworkCache:()=>ipcRenderer.invoke('cache:clear'),
  openMetadataDiagnosticLogs:()=>ipcRenderer.invoke('metadataDiagnostics:open'),
  playerShow:()=>ipcRenderer.invoke('player:show'),playerSnapshot:()=>ipcRenderer.invoke('player:snapshot'),
  playerCommand:value=>ipcRenderer.invoke('player:command',value),playerAction:(name,value)=>ipcRenderer.invoke('player:action',name,value),
  playerResource:(refs,mode,source)=>ipcRenderer.invoke('player:resource',refs,mode,source),
  onPlayerState:callback=>{const listener=(_,value)=>callback(value);ipcRenderer.on('player:state',listener);return()=>ipcRenderer.removeListener('player:state',listener)},
  usageSnapshot:()=>ipcRenderer.invoke('usage:snapshot'),usageOpened:id=>ipcRenderer.invoke('usage:opened',id),usageTick:(id,seconds)=>ipcRenderer.invoke('usage:tick',id,seconds),
  notifyMediaPlaying:kind=>ipcRenderer.send(kind==='audio'?'audio:playing':'reader:playing'),
  onMediaPause:callback=>{const listener=(_,kind)=>callback(kind);ipcRenderer.on('media:pause',listener);return()=>ipcRenderer.removeListener('media:pause',listener);},
  audioPreviewMetadata:(id,details,candidateId,name,importOnline=false)=>ipcRenderer.invoke('audio:previewMetadata',id,details,candidateId,name,importOnline),audioImportFiles:(paths,kind)=>ipcRenderer.invoke('audio:importFiles',paths,kind),audioOpenWindow:()=>ipcRenderer.invoke('audio:windowOpen'),
  audioPublish:v=>ipcRenderer.send('audio:windowState',v),
  onAudioCommand:cb=>ipcRenderer.on('audio:command',(_,payload)=>cb(payload.command,payload.value)),
  onAudioRequestState:cb=>ipcRenderer.on('audio:requestState',()=>cb()),
  audioDroppedPath:file=>require('electron').webUtils.getPathForFile(file),
  audioScanDropped:(paths,kind,options)=>ipcRenderer.invoke('audio:scanDropped',paths,kind,options),
  audioStop:()=>ipcRenderer.send('audio:stop'),
  audioPreferences:()=>ipcRenderer.invoke('audio:preferences'),audioSetPreferences:v=>ipcRenderer.invoke('audio:setPreferences',v),
  audioPickPaths:mode=>ipcRenderer.invoke('audio:pickPaths',mode),
  audioSearchTrack:(id,track)=>ipcRenderer.invoke('audio:searchTrack',id,track),audioApplyTrackMetadata:(id,track,candidate)=>ipcRenderer.invoke('audio:applyTrackMetadata',id,track,candidate),audioCompleteLyrics:(id,tracks)=>ipcRenderer.invoke('audio:completeLyrics',id,tracks),onAudioCompletion:cb=>{const fn=(_,v)=>cb(v);ipcRenderer.on('audio:completionProgress',fn);return()=>ipcRenderer.removeListener('audio:completionProgress',fn);},
  audioSearchDraft:value=>ipcRenderer.invoke('audio:searchDraft',value),audioMetadataDetails:id=>ipcRenderer.invoke('audio:metadataDetails',id),
  audioSearch:id=>ipcRenderer.invoke('audio:search',id),audioApplyMetadata:(id,candidate)=>ipcRenderer.invoke('audio:applyMetadata',id,candidate),audioCancelExtras:()=>ipcRenderer.send('audio:cancelExtras'),
  audioOnlineLyrics:(id,track,query)=>ipcRenderer.invoke('audio:onlineLyrics',id,track,query),audioSaveLyrics:(id,track,v)=>ipcRenderer.invoke('audio:saveLyrics',id,track,v),audioPickLyrics:()=>ipcRenderer.invoke('audio:pickLyrics'),
  audioTestConnection:id=>ipcRenderer.invoke('audio:testConnection',id),
  audioConnections:()=>ipcRenderer.invoke('audio:connections'),audioConnectionDetails:id=>ipcRenderer.invoke('audio:connectionDetails',id),audioSaveConnection:v=>ipcRenderer.invoke('audio:saveConnection',v),audioRemoveConnection:id=>ipcRenderer.invoke('audio:removeConnection',id),audioBrowse:(id,relative)=>ipcRenderer.invoke('audio:browse',id,relative),audioImportRemote:(id,rows,kind)=>ipcRenderer.invoke('audio:importRemote',id,rows,kind),
  audioLyrics:(itemId,trackId)=>ipcRenderer.invoke('audio:lyrics',itemId,trackId),
  audioPickScan:(mode,kind)=>ipcRenderer.invoke('audio:pickScan',mode,kind),
  audioCancel:()=>ipcRenderer.send('audio:cancel'),
  audioImport:(ids,edits)=>ipcRenderer.invoke('audio:import',ids,edits),
  audioResolve:(itemId,trackId,options)=>ipcRenderer.invoke('audio:resolve',itemId,trackId,options),
  audioSessionSaveFinal:v=>ipcRenderer.sendSync('audio:sessionSaveFinal',v),
  audioSessionLoad:()=>ipcRenderer.invoke('audio:sessionLoad'),
  audioSessionSave:value=>ipcRenderer.invoke('audio:sessionSave',value),
  onAudioScan:callback=>{const listener=(_,v)=>callback(v);ipcRenderer.on('audio:scanProgress',listener);return()=>ipcRenderer.removeListener('audio:scanProgress',listener);},
  loadLibrary: () => ipcRenderer.invoke('library:load'),
  inspectDropped:paths=>ipcRenderer.invoke('local:inspectDropped',paths),
  cancelImportMetadata:type=>ipcRenderer.invoke(type==='audio'?'audio:cancelMetadata':'local:cancelMetadata'),
  previewDropped:(paths,type,options)=>ipcRenderer.invoke('local:previewDropped',paths,type,options),
  pickImportFiles:type=>ipcRenderer.invoke('local:pickFiles',type),
  pickImportRoots:()=>ipcRenderer.invoke('local:pickRoots'),
  previewLocal:(roots,type,options)=>ipcRenderer.invoke('local:preview',roots,type,options),
  cancelLocal:()=>ipcRenderer.send('local:cancel'),
  localMetadata:(id,type,name,onProgress)=>{const key=String(id),listener=(_,value)=>{if(value?.id===key)onProgress?.(value.bundle);};if(onProgress)ipcRenderer.on('local:metadataProgress',listener);return ipcRenderer.invoke('local:metadata',id,type,name).finally(()=>{if(onProgress)ipcRenderer.removeListener('local:metadataProgress',listener);});},
  prepareLocalCandidate:candidate=>ipcRenderer.invoke('local:prepareCandidate',candidate),
  resolveLocalMetadataCandidate:(id,candidate)=>ipcRenderer.invoke('local:resolveCandidate',id,candidate),
  onLocalProgress:callback=>{const listener=(_,value)=>callback(value);ipcRenderer.on('local:progress',listener);return()=>ipcRenderer.removeListener('local:progress',listener);},
  openReader:id=>ipcRenderer.invoke('reader:open',id),
  launchReader:id=>ipcRenderer.invoke('reader:launch',id),
  compatibleVideo:url=>ipcRenderer.invoke('reader:compatibility',url),
  stopCompatibleVideo:()=>ipcRenderer.invoke('reader:stopCompatibility'),
  closeReader:()=>ipcRenderer.invoke('reader:close'),
  saveReaderProgress:(id,value)=>ipcRenderer.invoke('reader:progress',id,value),
  recentReading:()=>ipcRenderer.invoke('reader:recent'),
  pickSubtitle:()=>ipcRenderer.invoke('reader:subtitle'),
  saveLibrary: (state) => ipcRenderer.invoke('library:save', state),
  loadSettings: () => ipcRenderer.invoke('settings:load'),
  saveSettings: (settings) => ipcRenderer.invoke('settings:save', settings),
  searchMetadata: (type, query) => ipcRenderer.invoke('metadata:search', type, query),
  searchMetadataSources: (type, query) => ipcRenderer.invoke('metadata:searchSources', type, query),
  startMetadataSearch: (id,type,query) => ipcRenderer.invoke('metadata:start',id,type,query),
    openMetadataVerification: (host,type,query,sourceId,startUrl) => ipcRenderer.invoke('metadata:openVerification',host,type,query,sourceId,startUrl),
  cancelMetadataSearch: id => ipcRenderer.send('metadata:cancel',id),
  prepareMetadataCandidate: candidate => ipcRenderer.invoke('metadata:prepareCandidate',candidate),
  resolveMetadataCandidate: (id,candidate) => ipcRenderer.invoke('metadata:resolveCandidate',id,candidate),
  integrateMetadataSources: (type,primary,sources,query='') => ipcRenderer.invoke('metadata:integrate',type,primary,sources,query),
  resolveLibraryCover: urls => ipcRenderer.invoke('metadata:libraryCover',urls),
  previewMetadataCover: (urls,id) => ipcRenderer.invoke('metadata:previewCover',urls,id),
  onMetadataProgress: callback => { const listener=(_,value)=>callback(value);ipcRenderer.on('metadata:progress',listener);return ()=>ipcRenderer.removeListener('metadata:progress',listener); },
  pickCoverImage: () => ipcRenderer.invoke('cover:pick'),
  refreshCoverMetadata: (type, name, appid) => ipcRenderer.invoke('metadata:refreshCovers', type, name, appid),
  openExternal: (url) => ipcRenderer.invoke('external:open', url),
  openDisguiseVideo: (query, index) => ipcRenderer.invoke('disguise:openVideo', query, index),
  pickLocalScanPaths: () => ipcRenderer.invoke('local:pickPaths'),
  readerFonts:()=>ipcRenderer.invoke('reader:fonts'),pickResourcePath: (kind,initial) => ipcRenderer.invoke('resource:pickPath', kind,initial),
  revealLocal: file => ipcRenderer.invoke('local:reveal',file),
  scanLocalGames: (paths) => ipcRenderer.invoke('local:scan', paths),
  syncSteamPlaytime: () => ipcRenderer.invoke('steam:syncPlaytime'),
  refreshItemMetadata: (item,jobId) => ipcRenderer.invoke('metadata:refreshItem', item,jobId),
  cancelMetadataRefresh:jobId=>ipcRenderer.send('metadata:refreshCancel',jobId),
  exportData: (state) => ipcRenderer.invoke('data:export', state),
  importData: () => ipcRenderer.invoke('data:import'),
  restoreData: (bundle) => ipcRenderer.invoke('data:restore', bundle),
  minimize: () => ipcRenderer.invoke('window:minimize'),
  toggleMaximize: () => ipcRenderer.invoke('window:toggleMaximize'),
  windowState: () => ipcRenderer.invoke('window:state'),
  onWindowState: callback => {const listener=(_,value)=>callback(value);ipcRenderer.on('window:state',listener);return ()=>ipcRenderer.removeListener('window:state',listener);},
  close: () => ipcRenderer.invoke('window:close'),
  pickSavePaths: () => ipcRenderer.invoke('saves:pickPaths'),
  detectSavePaths: item => ipcRenderer.invoke('saves:detectPaths',item),
  persistSavePaths: (itemId,paths) => ipcRenderer.invoke('saves:persistPaths',itemId,paths),
  backupSaves: (itemId, paths, options) => ipcRenderer.invoke('saves:backup', itemId, paths, options),
  listBackups: (itemId) => ipcRenderer.invoke('saves:list', itemId),
  listAllBackups: () => ipcRenderer.invoke('saves:listAll'),
  listRemoteBackups: (itemId,settings) => ipcRenderer.invoke('saves:listRemote',itemId,settings),
  updateBackupNote: (itemId, backupId, note) => ipcRenderer.invoke('saves:updateNote', itemId, backupId, note),
  restoreBackup: (itemId, backupId) => ipcRenderer.invoke('saves:restore', itemId, backupId),
  restoreRemoteBackup: (itemId,backupId,settings) => ipcRenderer.invoke('saves:restoreRemote',itemId,backupId,settings),
  deleteBackup: (itemId, backupId, options) => ipcRenderer.invoke('saves:delete', itemId, backupId, options),
  deleteRemoteBackup: (itemId,backupId,settings) => ipcRenderer.invoke('saves:deleteRemote',itemId,backupId,settings),
  deleteBackups: (rows, options) => ipcRenderer.invoke('saves:deleteMany', rows, options),
  syncBackupSnapshot: (itemId, backupId, settings, context) => ipcRenderer.invoke('saves:syncOne', itemId, backupId, settings, context),
  openBackupFolder: (itemId, gameName) => ipcRenderer.invoke('saves:openFolder', itemId, gameName),
  testWebdav: (settings) => ipcRenderer.invoke('webdav:test', settings),
  syncWebdav: (settings, direction, resolution, expectedVersion) => { const args=[settings,direction];if(resolution!==undefined)args.push(resolution);if(expectedVersion!==undefined){if(args.length<3)args.push(null);args.push(expectedVersion);}return ipcRenderer.invoke('webdav:sync',...args); },
  setDisguise: (enabled) => ipcRenderer.invoke('disguise:set', enabled),
  onDisguiseState: (callback) => ipcRenderer.on('disguise:state', (_, state) => callback(state)),
});
