/* Tab references share the existing reader engine: switch saves/disposes, never two engines. */
const readerTabs=new Map();let readerTabSwitch=false;
function installReaderTabs(session){
 if(!window.UNIFIED_READER_WINDOW||!native.readerCatalog)return;
 readerTabs.set(session.data.id,session.data.name);
 const tabs=document.createElement('nav');tabs.className='reader-tabs';tabs.setAttribute('aria-label','阅读标签');$('readerBackdrop').querySelector('.reader-header').after(tabs);
 async function select(id){if(readerTabSwitch||id===mediaSession?.data?.id)return;readerTabSwitch=true;try{await openMedia(id);}finally{readerTabSwitch=false;}}
 for(const [id,name]of readerTabs){const row=document.createElement('span');row.className='reader-tab';row.classList.toggle('active',id===session.data.id);const b=document.createElement('button');b.textContent=name;b.title=name;b.onclick=()=>select(id);const x=document.createElement('button');x.textContent='×';x.setAttribute('aria-label','关闭 '+name);x.onclick=()=>{if(readerTabSwitch)return;readerTabs.delete(id);if(id===session.data.id){const next=readerTabs.keys().next().value;if(next)select(next);else native.close();}else row.remove();};row.append(b,x);tabs.append(row);}
 const add=document.createElement('button');add.textContent='＋';add.setAttribute('aria-label','打开阅读资源');tabs.append(add);
 add.onclick=async()=>{try{const items=await native.readerCatalog(),body=document.createElement('div');body.className='reader-catalog';const search=document.createElement('input');search.placeholder='搜索已入库的书籍、漫画';const list=document.createElement('div');list.className='reader-search-results';body.append(search,list);const dialog=readerToolDialog('打开阅读资源',body);const draw=()=>{list.replaceChildren();for(const item of items.filter(i=>i.type===session.data.type&&i.name.toLocaleLowerCase().includes(search.value.toLocaleLowerCase()))){const row=document.createElement('div');row.className='reader-catalog-row';const b=document.createElement('button');b.textContent=item.name;b.onclick=()=>{dialog.remove();select(item.id);};const win=document.createElement('button');win.textContent='打开';win.onclick=()=>native.launchReader(item.id);const split=document.createElement('button');split.textContent='分屏';split.onclick=()=>native.readerWindowCommand('split',item.id);row.append(b,win,split);list.append(row);}if(!list.children.length)list.textContent='没有匹配的已入库资源';};search.oninput=draw;draw();search.focus();}catch(e){readerNotice(e.message);}};
}
