/* Shared, cancellable full-text search. All external/book text stays text-only. */
function groupReaderSearchResults(rows){const groups=new Map();for(const row of rows){const key=row.contextKey||JSON.stringify([row.chapter,row.label]);if(groups.has(key))groups.get(key).count++;else groups.set(key,{...row,count:1});}return [...groups.values()];}
function openReaderSearch(session,engine){
 const body=document.createElement('div');body.className='reader-search';
 const row=document.createElement('div');row.className='reader-search-bar';const input=document.createElement('input');input.placeholder='输入关键词，搜索当前卷全文';input.setAttribute('aria-label','搜索文本');input.type='search';
 const go=document.createElement('button');go.textContent='查找';const cancel=document.createElement('button');cancel.textContent='停止';cancel.hidden=true;row.append(input,go,cancel);
 const status=document.createElement('p');status.setAttribute('role','status');status.textContent='输入后按 Enter，或点击查找。';const results=document.createElement('div');results.className='reader-search-results';body.append(row,status,results);const dialog=readerToolDialog('全文搜索',body);let serial=0;
 const valid=id=>id===serial&&dialog.isConnected&&!session.loadAbort.signal.aborted;
 function paint(rows,q){rows=groupReaderSearchResults(rows);results.replaceChildren();for(const [index,hit]of rows.entries()){const button=document.createElement('button');button.className='reader-search-hit';const heading=document.createElement('small');heading.textContent=(index+1)+'. '+(hit.chapter||'匹配位置')+(hit.count>1?' · '+hit.count+' 处命中':'');const excerpt=document.createElement('span'),text=String(hit.label||''),lower=text.toLocaleLowerCase(),needle=q.toLocaleLowerCase();let at=0,next;while((next=lower.indexOf(needle,at))>=0){excerpt.append(document.createTextNode(text.slice(at,next)));const mark=document.createElement('mark');mark.textContent=text.slice(next,next+q.length);excerpt.append(mark);at=next+q.length;}excerpt.append(document.createTextNode(text.slice(at)));button.append(heading,excerpt);button.onclick=async()=>{try{await hit.open();if(dialog.isConnected)dialog.remove();}catch(error){status.textContent='跳转失败：'+error.message;}};results.append(button);}}
 async function search(){const q=input.value.trim(),id=++serial;if(!q){results.replaceChildren();status.textContent='请输入关键词';return;}go.disabled=true;cancel.hidden=false;results.replaceChildren();status.textContent='正在搜索…';try{const rows=await engine.search(q,()=>valid(id),(rows,done,total)=>{if(!valid(id))return;paint(rows,q);status.textContent='已检查 '+done+'/'+total+' 章 · '+groupReaderSearchResults(rows).length+' 个段落';});if(!valid(id))return;paint(rows,q);status.textContent=rows.length>=200?'已显示前 200 处，请增加关键词缩小范围':rows.length?'找到 '+groupReaderSearchResults(rows).length+' 个段落，点击结果跳转':'没有找到匹配文字';}catch(error){if(valid(id))status.textContent='搜索失败：'+error.message;}finally{if(valid(id)){go.disabled=false;cancel.hidden=true;}}}
 cancel.onclick=()=>{++serial;go.disabled=false;cancel.hidden=true;status.textContent='已停止，已找到的结果仍可打开';};go.onclick=search;input.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();search();}};input.oninput=()=>{++serial;go.disabled=false;cancel.hidden=true;status.textContent=input.value.trim()?'按 Enter 查找新关键词':'请输入关键词';results.replaceChildren();};input.focus();
}
