const path=require('node:path');
function createReaderWindows({BrowserWindow,ipcMain,loadLibrary,loadSettings,localServices,player,usage}){
 const windows=new Map(),owners=new Map();const {screen,app,Tray,Menu,Notification}=require('electron');const stateStore=require('./reader-progress-store').createProgressStore(()=>path.join(app.getPath('userData'),'reader-window-state.json'));const trays=new Map();
 const owned=event=>{const win=BrowserWindow.fromWebContents(event.sender);if(!win||!owners.has(event.sender.id))throw Error('不是活动阅读窗口');return win;};
 require('./reader-ocr').installReaderOcr(ipcMain,owned);require('./reader-lookup').installReaderLookup(ipcMain,owned);
 ipcMain.handle('reader:capture',async(event,rect)=>{const win=owned(event);if(!rect||!['x','y','width','height'].every(k=>Number.isFinite(rect[k])))throw Error('截图范围无效');const [width,height]=win.getContentSize(),x=Math.max(0,Math.floor(rect.x)),y=Math.max(0,Math.floor(rect.y));const area={x,y,width:Math.min(width-x,Math.ceil(rect.width)),height:Math.min(height-y,Math.ceil(rect.height))};if(area.width<1||area.height<1)throw Error('阅读区域不可见');let image=await event.sender.capturePage(area);const size=image.getSize(),scale=Math.min(1,2200/Math.max(size.width,size.height));if(scale<1)image=image.resize({width:Math.round(size.width*scale),height:Math.round(size.height*scale)});return image.toDataURL();});
 const preferenceKeys=['theme','themeOverrides','font','fontFamily','lineHeight','paragraphGap','pageMargins','align','flow','comicMode','direction','fit','zoom','pair','seamless','pdfFit','pdfZoom','annotationPrefs','volume','rate','autoNext','imageEffects','pdfCrop','spreadMode'];
 ipcMain.handle('reader:preferences',async(event,type,value)=>{owned(event);if(!['book','manga','movie','anime','document'].includes(type))return {};const key='preferences-'+type;if(value!==undefined){if(!value||typeof value!=='object'||JSON.stringify(value).length>65536)throw Error('阅读选项无效');await stateStore.save(key,Object.fromEntries(preferenceKeys.filter(k=>value[k]!==undefined).map(k=>[k,value[k]])));}return stateStore.read()[key]||{};});
 const safeBounds=raw=>{const fallback=screen.getPrimaryDisplay().workArea,b=raw&&['x','y','width','height'].every(k=>Number.isFinite(raw[k]))?raw:{...fallback,width:1180,height:820};const area=screen.getDisplayMatching(b).workArea;return {width:Math.max(650,Math.min(area.width,b.width)),height:Math.max(440,Math.min(area.height,b.height)),x:Math.max(area.x,Math.min(b.x,area.x+area.width-Math.min(area.width,b.width))),y:Math.max(area.y,Math.min(b.y,area.y+area.height-Math.min(area.height,b.height)))};};
 ipcMain.handle('reader:catalog',event=>{owned(event);return loadLibrary().items.filter(i=>['book','manga','document'].includes(i.type)).map(i=>({id:i.id,name:i.name,type:i.type}));});
 ipcMain.handle('reader:windowCommand',async(event,command,value)=>{const win=owned(event);switch(command){case 'topmost':if(typeof value!=='boolean')throw Error('参数无效');win.setAlwaysOnTop(value);break;case 'progress':if(!Number.isFinite(value))throw Error('进度无效');win.setProgressBar(value<0?-1:Math.max(0,Math.min(1,value)));break;case 'mini':if(win.umRestoreBounds){win.setBounds(safeBounds(win.umRestoreBounds));delete win.umRestoreBounds;}else{win.umRestoreBounds=win.getBounds();win.setSize(650,440);}break;case 'tray':{if(!trays.has(win.id)){const tray=new Tray(path.join(__dirname,'assets/icon.ico'));tray.setToolTip('悦森盒 YueDen · 阅读');tray.setContextMenu(Menu.buildFromTemplate([{label:'显示阅读窗口',click:()=>win.show()},{label:'关闭阅读窗口',click:()=>win.close()}]));tray.on('double-click',()=>win.show());trays.set(win.id,tray);}win.hide();break;}case 'notify':if(!Notification.isSupported())return false;new Notification({title:'悦森盒 YueDen · 阅读',body:String(value||'').slice(0,120),icon:path.join(__dirname,'assets/icon.ico')}).show();break;case 'split':{const area=screen.getDisplayMatching(win.getBounds()).workArea;win.setBounds({...area,width:Math.floor(area.width/2)});if(typeof value!=='string')throw Error('请选择对照资源');return launch(event,value,{x:area.x+Math.floor(area.width/2),y:area.y,width:Math.ceil(area.width/2),height:area.height});}default:throw Error('未知窗口操作');}return true;});
 ipcMain.handle('reader:activeItem',(event,id)=>{const win=owned(event),item=loadLibrary().items.find(i=>i.id===id);if(!item||item.type!==win.umResourceType)throw Error('资源类型与窗口不符');owners.set(event.sender.id,id);win.umUsage?.sample();win.setTitle(item.name+' · 悦森盒 YueDen');return true;});
 ipcMain.handle('reader:init',event=>{const id=owners.get(event.sender.id);if(!id)throw Error('阅读窗口已关闭');return {id,appearance:loadSettings().appearance||{}};});
 const launch=async(event,id,bounds)=>{
  if(loadSettings().disguiseEnabled)throw Error('请从当前页面选择可用资源');
  const item=loadLibrary().items.find(v=>v.id===id);if(!item)throw Error('资源已不存在');
  if(player&&['movie','anime','audio'].includes(item.type))return player.openResource(id);
  if(['game','software','unknown_application'].includes(item.type))return localServices.prepare(event.sender.id,id);
  const previous=!bounds&&[...windows.values()].find(w=>!w.isDestroyed()&&w.umResourceType===item.type);if(previous&&!previous.isDestroyed()){if(previous.isMinimized())previous.restore();previous.show();previous.focus();if(owners.get(previous.webContents.id)!==id){owners.set(previous.webContents.id,id);previous.umUsage?.sample();previous.setTitle(item.name+' · 悦森盒 YueDen');previous.webContents.send('reader:activate',id);}return {windowId:previous.id};}
  const win=new BrowserWindow({...safeBounds(bounds||stateStore.read().reader?.bounds),minWidth:650,minHeight:440,frame:false,show:false,title:item.name+' · 悦森盒 YueDen',backgroundColor:'#0c121b',icon:path.join(__dirname,'assets/icon.ico'),webPreferences:{preload:path.join(__dirname,'reader-preload.js'),sandbox:true,nodeIntegration:false,contextIsolation:true}});
  win.umResourceType=item.type;windows.set(win.id,win);owners.set(win.webContents.id,id);const owner=win.webContents.id;
  win.umUsage=usage?.timeline(()=>!win.isDestroyed()&&['book','manga'].includes(item.type)?{id:owners.get(owner),active:win.isVisible()&&!win.isMinimized()&&win.isFocused(),playing:false}:null);
  const usageError=error=>console.error('阅读时长未保存：',error);
  const usageTimer=setInterval(()=>{void win.umUsage?.flush().catch(usageError);},5000);
  for(const event of ['focus','blur','show','hide','minimize','restore'])win.on(event,()=>win.umUsage?.sample());
  win.once('closed',()=>{clearInterval(usageTimer);void win.umUsage?.close().catch(usageError);});
  const state=()=>{if(!win.webContents.isDestroyed())win.webContents.send('window:state',{maximized:win.isMaximized()});};const remember=()=>{clearTimeout(win.umSaveTimer);win.umSaveTimer=setTimeout(()=>{if(!win.isDestroyed()&&!win.umRestoreBounds)stateStore.save('reader',{bounds:win.getNormalBounds()}).catch(()=>{});},400);};win.on('move',remember);win.on('resize',remember);win.on('maximize',state);win.on('unmaximize',state);win.webContents.on('did-finish-load',state);
  win.webContents.on('will-navigate',e=>e.preventDefault());win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.once('ready-to-show',()=>win.show());win.once('closed',()=>{windows.delete(win.id);owners.delete(owner);trays.get(win.id)?.destroy();trays.delete(win.id);clearTimeout(win.umSaveTimer);localServices.revoke(owner);});
  await win.loadFile(path.join(__dirname,'reader.html'));return {windowId:win.id};
 };ipcMain.handle('reader:launch',(event,id)=>launch(event,id));
 return {closeAll(){for(const win of windows.values())if(!win.isDestroyed()){win.hide();win.close();}},appearance(){for(const win of windows.values())if(!win.isDestroyed())win.webContents.send('reader:appearance',loadSettings().appearance||{});}};
}
module.exports={createReaderWindows};
