window.usageData={};
async function refreshUsage(){try{window.usageData=await native.usageSnapshot();if(typeof state!=='undefined')state.items=state.items.map(item=>UsageModel.fill(item,window.usageData));}catch(e){showToast('使用记录读取失败：'+e.message,'error');}return window.usageData;}
async function openResourceLink(url,id){const result=await native.openExternal(url);if(id)await recordResourceOpen(id);return result;}
async function recordResourceOpen(id){try{window.usageData[id]=await native.usageOpened(id);}catch(e){showToast('最近打开记录未保存：'+e.message,'error');}}
function resourceUsageHours(item){return UsageModel.hours(item,window.usageData);}
let usageSelected='game';
const usageColors={game:'#56bba0',movie:'#638cda',anime:'#af80d1',manga:'#d99a4d',book:'#cb738e',audio:'#53adbf'};
function usageArc(start,end){const point=(r,a)=>[120+r*Math.cos(a-Math.PI/2),120+r*Math.sin(a-Math.PI/2)].join(' '),large=end-start>Math.PI?1:0;return 'M '+point(96,start)+' A 96 96 0 '+large+' 1 '+point(96,end)+' L '+point(65,end)+' A 65 65 0 '+large+' 0 '+point(65,start)+' Z';}
function selectUsageType(type){if(!UsageModel.types.includes(type))return;const panel=$('usagePanel');usageSelected=type;panel.querySelectorAll('[data-usage-type]').forEach(el=>{const selected=el.dataset.usageType===type;el.classList.toggle('selected',selected);if(el.tagName==='BUTTON')el.setAttribute('aria-pressed',String(selected));});renderUsageBars(panel);}
function renderUsageBars(panel){const groups=UsageModel.rankings(state.items,window.usageData,usageSelected),label=TYPE_NAMES[usageSelected],signature=JSON.stringify([usageSelected,...Object.values(groups).flat().map(r=>[r.item.id,r.item.name,coverFor(r.item),r.hours.toFixed(1)])]);const host=panel.querySelector('.usage-rankings');if(host.dataset.signature===signature)return;host.dataset.signature=signature;host.style.setProperty('--usage-color',usageColors[usageSelected]);host.innerHTML=['recent','longest'].map(kind=>{const rows=groups[kind],max=Math.max(...rows.map(r=>r.hours),0.1);return '<section class="usage-ranking" aria-label="'+esc(label+(kind==='recent'?'最近使用':'时长最长'))+'"><h3>'+esc(label)+' · '+(kind==='recent'?'最近使用':'时长最长')+'<small>最多 5 项</small></h3><div class="usage-bars">'+(rows.length?rows.map((r,i)=>{const cover=coverFor(r.item);return '<div class="usage-bar-row" style="--order:'+i+'"><div class="usage-resource" title="'+esc(r.item.name)+'"><span>'+esc(r.item.name)+'</span>'+(cover?'<img src="'+esc(cover)+'" alt="" loading="lazy">':'<span class="usage-cover-empty" aria-hidden="true">'+esc(label.slice(0,1))+'</span>')+'</div><div class="usage-bar-area"><span class="usage-bar" style="width:'+Math.max(0,Math.min(100,r.hours/max*100))+'%"></span><strong>'+r.hours.toFixed(1)+'h</strong></div></div>';}).join(''):'<p class="usage-empty">'+(kind==='recent'?'暂无最近使用记录':'暂无时长记录')+'</p>')+'</div></section>';}).join('');host.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.style.visibility='hidden';},{once:true}));}
function renderUsageChart(){let panel=$('usagePanel');if(!panel){panel=document.createElement('article');panel.id='usagePanel';panel.className='panel usage-panel';$('insights').closest('.insights-panel').before(panel);}const rows=UsageModel.groups(state.items,window.usageData),total=rows.reduce((n,r)=>n+r.hours,0);let at=0;const paths=rows.filter(r=>r.hours>0).map(r=>{const start=at;at+=r.hours/total*Math.PI*2;return '<path class="usage-segment" data-usage-type="'+r.type+'" tabindex="0" role="button" aria-label="'+esc(TYPE_NAMES[r.type])+' '+r.hours.toFixed(1)+'小时" d="'+usageArc(start,Math.min(at,start+Math.PI*2-0.00001))+'" fill="'+usageColors[r.type]+'"><title>'+esc(TYPE_NAMES[r.type])+' '+r.hours.toFixed(1)+'h · '+(r.hours/total*100).toFixed(1)+'%</title></path>';}).join('');panel.innerHTML='<div class="panel-title"><div><span class="eyebrow">资源使用</span><h2>时长统计</h2></div></div><div class="usage-layout"><div class="usage-overview"><svg class="usage-donut" viewBox="0 0 240 240" aria-label="各类资源时长占比"><circle cx="120" cy="120" r="80" fill="none" stroke="var(--line)" stroke-width="31"/>'+paths+'<text x="120" y="113" class="usage-total">'+total.toFixed(1)+'h</text><text x="120" y="137" class="usage-total-label">累计时长</text></svg><div class="usage-legend">'+rows.map(r=>'<button type="button" data-usage-type="'+r.type+'" aria-pressed="false"><span class="legend-dot" style="background:'+usageColors[r.type]+'"></span><span>'+esc(TYPE_NAMES[r.type])+'</span><strong>'+r.hours.toFixed(1)+'h</strong><small>'+(total?r.hours/total*100:0).toFixed(1)+'%</small></button>').join('')+'</div></div><div class="usage-rankings" aria-live="polite"></div></div><p class="usage-explanation">按当前资源分别记录：阅读窗口前台使用，媒体窗口前台使用与实际播放的重叠时间只计一次。各资源与已有填写／平台时长取较大值；手填阅读时长保留。</p>';panel.querySelectorAll('[data-usage-type]').forEach(el=>{el.addEventListener('click',()=>selectUsageType(el.dataset.usageType));if(el.classList.contains('usage-segment')){el.addEventListener('pointerenter',()=>selectUsageType(el.dataset.usageType));el.addEventListener('focus',()=>selectUsageType(el.dataset.usageType));el.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();selectUsageType(el.dataset.usageType);}});}});selectUsageType(usageSelected);}
window.addEventListener('focus',()=>{if(typeof state==='undefined')return;void refreshUsage().then(()=>{if(activeView==='dashboard')renderUsageChart();});});
