const {xml,parseDav}=require('./audio-remote');
const address=require('./webdav-address');
function segments(value){const parts=String(value||'').replaceAll('\\','/').split('/').filter(Boolean);if(parts.some(p=>p==='.'||p==='..'))throw Error('WebDAV 目录不能包含 . 或 ..');return parts;}
function endpoint(settings,relative='',root=false){const url=address(settings),parts=[...root?[]:segments(settings.webdavRemotePath),...segments(relative)];url.pathname+=parts.map(encodeURIComponent).join('/');return url;}
function headers(settings,extra={}){return {...extra,...settings.webdavUsername?{Authorization:'Basic '+Buffer.from(settings.webdavUsername+':'+(settings.webdavPassword||'')).toString('base64')}: {}};}
function failure(method,status){const detail=status===400?'请求被服务器拒绝，请核对 WebDAV 目录地址（InfiniCLOUD 使用 /dav/）':status===401?'认证失败，请核对连接 ID 和应用专用密码':status===403?'服务器拒绝访问，请核对目录权限':status===404?'远端目录或文件不存在':status===429?'服务被限流，请稍后重试':status>=500?'上游服务故障':status===412?'远端已发生变化，未覆盖，请重新同步':'HTTP 请求失败';return Error('WebDAV '+method+' '+detail+'（'+status+'）');}
async function xmlText(response){const reader=response.body?.getReader();if(!reader)return response.text();const decoder=new TextDecoder();let result='',bytes=0;try{while(true){const value=await reader.read();if(value.done)break;bytes+=value.value.byteLength;if(bytes>2*1024*1024){await reader.cancel('response too large');throw Error('WebDAV 目录响应超过读取上限');}result+=decoder.decode(value.value,{stream:true});}return result+decoder.decode();}finally{reader.releaseLock();}}
function create({fetch:fetcher=globalThis.fetch,timeout=15000}={}){
 async function request(settings,method,relative='',body=null,contentType='',extra={},signal,root=false){const url=endpoint(settings,relative,root);if(['PROPFIND','MKCOL'].includes(method)&&!url.pathname.endsWith('/'))url.pathname+='/';const timed=AbortSignal.timeout(timeout),combined=signal?AbortSignal.any([signal,timed]):timed;try{return await fetcher(url,{method,body,headers:headers(settings,{...extra,...body!=null?{'Content-Type':contentType||(Buffer.isBuffer(body)?'application/octet-stream':'application/json; charset=utf-8')}: {}}),signal:combined,redirect:'error'});}catch(error){if(signal?.aborted)throw Error('WebDAV 请求已取消');if(timed.aborted)throw Error('WebDAV '+method+' 请求超时');throw Error('WebDAV '+method+' 网络连接失败：'+(error.cause?.code||error.name||'连接中断'));}}
 async function collection(settings,relative,root=false){const response=await request(settings,'PROPFIND',relative,null,'',{Depth:'0'},undefined,root);if(response.status===404){await response.body?.cancel();return false;}if(!response.ok){await response.body?.cancel();throw failure('PROPFIND',response.status);}const tree=xml(await xmlText(response)),find=(node,name)=>node.name===name?[node]:node.children.flatMap(c=>find(c,name));if(!find(tree,'multistatus').length||!find(tree,'propstat').some(p=>find(p,'status').some(s=>/\s200\s/.test(s.text))&&find(p,'collection').length))throw Error('服务器未返回有效的 WebDAV 目录；请使用账户提供的 WebDAV 连接地址');return true;}
 async function ensurePath(settings){if(!await collection(settings,'',true))throw Error('WebDAV 根目录不存在，请核对连接地址');let relative='';for(const part of segments(settings.webdavRemotePath)){relative+=(relative?'/':'')+part;const scoped={...settings,webdavRemotePath:''};if(await collection(scoped,relative))continue;const made=await request(scoped,'MKCOL',relative);await made.body?.cancel();if(!made.ok&&made.status!==405)throw failure('MKCOL',made.status);if(!await collection(scoped,relative))throw Error('WebDAV 目录创建后仍不可访问');}}
 async function ensureDirectories(settings,relative){let current='';for(const part of segments(relative)){current+=(current?'/':'')+part;if(await collection(settings,current))continue;const response=await request(settings,'MKCOL',current);await response.body?.cancel();if(!response.ok&&response.status!==405)throw failure('MKCOL',response.status);if(!await collection(settings,current))throw Error('WebDAV 子目录不可访问');}}
 async function listFiles(settings,start='saves'){const queue=[start],files=[],seen=new Set(),scope={base:endpoint(settings).href,origins:[address(settings).origin],root:endpoint(settings).pathname};if(!scope.base.endsWith('/'))scope.base+='/';if(!scope.root.endsWith('/'))scope.root+='/';while(queue.length){const relative=queue.shift();if(seen.has(relative))continue;seen.add(relative);if(seen.size>500)throw Error('WebDAV 存档目录超过本次枚举上限');const response=await request(settings,'PROPFIND',relative,null,'',{Depth:'1'});if(response.status===404){await response.body?.cancel();continue;}if(!response.ok){await response.body?.cancel();throw failure('PROPFIND',response.status);}const current=endpoint(settings,relative);if(!current.pathname.endsWith('/'))current.pathname+='/';for(const row of parseDav(await xmlText(response),current.href,scope)){const key=decodeURIComponent(row.relativePath).replace(/\/$/,'');if(!key.startsWith(start+'/'))continue;if(row.directory)queue.push(key);else files.push(key);if(files.length>10000)throw Error('WebDAV 存档数量超过本次枚举上限');}}return [...new Set(files)];}
 return {request,ensurePath,ensureDirectories,listFiles};
}
function describe(error){return ['AbortError','TimeoutError'].includes(error?.name)?'WebDAV 请求超时，当前操作已停止':error?.message||'WebDAV 同步失败';}
module.exports={create,address,endpoint,headers,failure,describe};
